force-app/main/default/objects/Advance__c/Advance__c.object-meta.xml
<CustomObject>
    <label>Advance</label>
    <nameField>
        <displayFormat>ADV-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Advance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Use</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <summarizedField>Invoice_Line_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <label>GST Amount</label>
    <summarizedField>Invoice_Line_Item__c.GST_Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoice_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Advance__c/Invoice_Advance__c.object-meta.xml
<CustomObject>
    <label>Invoice Advance</label>
    <nameField>
        <displayFormat>IADV-{0000}</displayFormat>
        <label>Invoice Advance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Advances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Advance__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Advance</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Advance__c.Status__c</field>
            <operation>equals</operation>
            <value>New</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Advance__c</referenceTo>
    <relationshipLabel>Invoice Advances</relationshipLabel>
    <relationshipName>Invoice_Advances</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Advance__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Advances</relationshipLabel>
    <relationshipName>Invoice_Advances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Advance__c/fields/Invoice_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Line_Item__c</fullName>
    <label>Invoice Line Item</label>
    <referenceTo>Invoice_Line_Item__c</referenceTo>
    <relationshipLabel>Invoice Advances</relationshipLabel>
    <relationshipName>Invoice_Advances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Advance__c/fields/Previous_Advance__c.field-meta.xml
<CustomField>
    <fullName>Previous_Advance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Advance</label>
    <referenceTo>Advance__c</referenceTo>
    <relationshipLabel>Invoice Advances (Previous Advance)</relationshipLabel>
    <relationshipName>Previous_Advances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/GST_Code__c.field-meta.xml
<CustomField>
    <fullName>GST_Code__c</fullName>
    <label>GST Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoice_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/GST_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>02</fullName>
        <label>0% (Oversea)</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <default>true</default>
        <label>7%</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>0% (Local)</label>
    </customValue>
    <masterLabel>GST Code</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Invoice_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Invoice Generation - In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Unpaid</fullName>
    </customValue>
    <customValue>
        <fullName>Partial</fullName>
    </customValue>
    <customValue>
        <fullName>Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled - Credit Note</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled - Debit Note</fullName>
    </customValue>
    <customValue>
        <fullName>Refunded</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Invoice Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InvoiceAdvanceTriggerHandler.cls
/**
 * @description       : 
 * @author            : Mark Alvin Tayag (mtayag@salesforce.com)
 * @group             : 
 * @last modified on  : 11-13-2020
 * @last modified by  : Mark Alvin Tayag (mtayag@salesforce.com)
 * Modifications Log 
 * Ver   Date         Author                                     Modification
 * 1.0   11-12-2020   Mark Alvin Tayag (mtayag@salesforce.com)   Initial Version
**/
public without sharing class InvoiceAdvanceTriggerHandler {

    public static void updateAmount(Boolean isInsert, List<Invoice_Advance__c> advList, Map<Id, Invoice_Advance__c> mapOldAdvList, Map<Id, Invoice_Advance__c> mapNewAdvList) {
        List<Invoice_Advance__c> invAdvList = new List<Invoice_Advance__c>();
        Map<Id, Invoice_Advance__c> invAdvMap = new Map<Id, Invoice_Advance__c>();

        for (Invoice_Advance__c invAdv : [SELECT Id, Invoice_Line_Item__r.Invoice__c, Advance__c, Advance__r.Amount__c, Advance__r.GST_Amount__c, Advance__r.GST_Code__c FROM Invoice_Advance__c WHERE Id =: mapNewAdvList.keySet()]) {

            if (!isInsert) {
                Invoice_Advance__c oldInvAdv = mapOldAdvList.get(invAdv.Id);
    
                if (oldInvAdv.Advance__c == invAdv.Advance__c) {
                    break;
                }
            }
            invAdv.Invoice__c = invAdv.Invoice_Line_Item__r.Invoice__c;
            invAdv.Amount__c = invAdv.Advance__r.Amount__c;
            invAdv.GST_Amount__c = invAdv.Advance__r.GST_Amount__c;
            invAdv.GST_Code__c = invAdv.Advance__r.GST_Code__c;
            invAdv.Previous_Advance__c = invAdv.Advance__c;
            invAdvList.add(invAdv);
        }

        if (invAdvList.size() > 0) {
            update invAdvList;
        }
    }

    public static void onInsert(List<Invoice_Advance__c> advList) {
        List<Id> advances = new List<Id>();
        for (Invoice_Advance__c invAdv : advList) {
            advances.add(invAdv.Advance__c);
        }

        if (advances.size() > 0) {
            updateAdvanceOnInsert(advances);
        }
    }

    @future
    public static void updateAdvanceOnInsert(List<Id> advanceIds) {
        List<Advance__c> advances = new List<Advance__c>();
        for (Id advanceId : advanceIds) {
            Advance__c advanceNew = new Advance__c();
            advanceNew.Id = advanceId;
            advanceNew.Status__c = 'In Use';

            advances.add(advanceNew);
        }

        if (advances.size() > 0) {
            update advances;
        }
    }

    public static void updateAdvance(Map<Id, Invoice_Advance__c> oldMap, List<Invoice_Advance__c> advList) {
        
        List<Advance__c> advances = new List<Advance__c>();
        for (Invoice_Advance__c invAdv : advList) {
            Invoice_Advance__c oldAdv = oldMap.get(invAdv.Id);
            if (invAdv.Advance__c != oldAdv.Advance__c) {
                Advance__c advance = new Advance__c();
                advance.Id = oldAdv.Advance__c;
                advance.Status__c = 'New';

                advances.add(advance);

                Advance__c advanceNew = new Advance__c();
                advanceNew.Id = invAdv.Advance__c;
                advanceNew.Status__c = 'In Use';

                advances.add(advanceNew);
            }
        }

        if (advances.size() > 0) {
            update advances;
        }
    }

    //Release Advance
    public static void afterDelete(List<Invoice_Advance__c> advList) {
        List<Advance__c> advances = new List<Advance__c>();
        for (Invoice_Advance__c invAdv : advList) {
            Advance__c adv = new Advance__c();
            adv.Id = invAdv.Advance__c;
            adv.Status__c = 'New';
            advances.add(adv);
        }
        update advances;
    }
}