force-app/main/default/objects/Advance__c/Advance__c.object-meta.xml
<CustomObject>
    <label>Advance</label>
    <nameField>
        <displayFormat>ADV-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Advance__c/fields/Advance_No__c.field-meta.xml
<CustomField>
    <fullName>Advance_No__c</fullName>
    <externalId>true</externalId>
    <label>Advance No</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Use</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <summarizedField>Invoice_Line_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <label>GST Amount</label>
    <summarizedField>Invoice_Line_Item__c.GST_Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Nett_Amount__c.field-meta.xml
<CustomField>
    <fullName>Nett_Amount__c</fullName>
    <label>Nett Amount</label>
    <summarizedField>Invoice_Line_Item__c.Nett_Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Nett_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Nett_GST_Amount__c</fullName>
    <label>Nett GST Amount</label>
    <summarizedField>Invoice_Line_Item__c.Nett_GST_Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoice_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Utilized_Advance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Utilized_Advance_Amount__c</fullName>
    <label>Utilized Advance Amount</label>
    <summarizedField>Invoice_Line_Item__c.Utilized_Advance_Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Utilized_Advance_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Utilized_Advance_GST_Amount__c</fullName>
    <label>Utilized Advance GST Amount</label>
    <summarizedField>Invoice_Line_Item__c.Utilized_Advance_GST_Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice_Advance__c/Invoice_Advance__c.object-meta.xml
<CustomObject>
    <label>Invoice Advance</label>
    <nameField>
        <displayFormat>IADV-{0000}</displayFormat>
        <label>Invoice Advance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Advances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Advance__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Advance</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Advance__c.Status__c</field>
            <operation>equals</operation>
            <value>New</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Advance__c</referenceTo>
    <relationshipLabel>Invoice Advances</relationshipLabel>
    <relationshipName>Invoice_Advances</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Advance__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Advances</relationshipLabel>
    <relationshipName>Invoice_Advances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Advance__c/fields/Invoice_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Line_Item__c</fullName>
    <label>Invoice Line Item</label>
    <referenceTo>Invoice_Line_Item__c</referenceTo>
    <relationshipLabel>Invoice Advances</relationshipLabel>
    <relationshipName>Invoice_Advances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>(MVP 1.0) - Invoice Line item display text</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/GST_Code__c.field-meta.xml
<CustomField>
    <fullName>GST_Code__c</fullName>
    <label>GST Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Nett_Amount__c.field-meta.xml
<CustomField>
    <fullName>Nett_Amount__c</fullName>
    <formula>Amount__c- Discount_Amount__c- Utilized_Advance_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nett Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Nett_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Nett_GST_Amount__c</fullName>
    <formula>GST_Amount__c-Discount_GST_Amount__c-Utilized_Advance_GST_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nett GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoice_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Utilized_Advance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Utilized_Advance_Amount__c</fullName>
    <label>Utilized Advance Amount</label>
    <summarizedField>Invoice_Advance__c.Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Advance__c.Invoice_Line_Item__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Utilized_Advance_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Utilized_Advance_GST_Amount__c</fullName>
    <label>Utilized Advance GST Amount</label>
    <summarizedField>Invoice_Advance__c.GST_Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Advance__c.Invoice_Line_Item__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/globalValueSets/GST_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>02</fullName>
        <label>0% (Oversea)</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <default>true</default>
        <label>7%</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>0% (Local)</label>
    </customValue>
    <masterLabel>GST Code</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Invoice_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Invoice Generation - In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Unpaid</fullName>
    </customValue>
    <customValue>
        <fullName>Partial</fullName>
    </customValue>
    <customValue>
        <fullName>Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled - Credit Note</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled - Debit Note</fullName>
    </customValue>
    <customValue>
        <fullName>Refunded</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Invoice Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InvoiceAdvanceTriggerHandlerTest.cls
/**
 * @description       : 
 * @author            : Mark Alvin Tayag (mtayag@salesforce.com)
 * @group             : 
 * @last modified on  : 11-13-2020
 * @last modified by  : Mark Alvin Tayag (mtayag@salesforce.com)
 * Modifications Log 
 * Ver   Date         Author                                     Modification
 * 1.0   11-13-2020   Mark Alvin Tayag (mtayag@salesforce.com)   Initial Version
**/
@IsTest
public without sharing class InvoiceAdvanceTriggerHandlerTest {
    @TestSetup
    static void testSetup(){
        //Prepare Data
        Advance__c advance = new Advance__c();
        advance.Amount__c = 100;
        advance.GST_Amount__c = 7;
        advance.GST_Code__c = '12';
        advance.Advance_No__c = '888888888';
        advance.Status__c = 'New';

        Advance__c advance2 = new Advance__c();
        advance2.Amount__c = 200;
        advance2.GST_Amount__c = 14;
        advance2.GST_Code__c = '12';
        advance2.Advance_No__c = '99999999';
        advance2.Status__c = 'New';

        List<Advance__c> advList = new List<Advance__c> { advance, advance2 };
        insert advList;
    }

    @IsTest
    static void utilizeAdvance(){
        

        Invoice__c invoice = TestDataFactory.createInvoice();
        insert invoice;

        Invoice_Line_Item__c lineItem = new Invoice_Line_Item__c();
        lineItem.Invoice__c = invoice.Id;
        lineItem.Amount__c = 500;
        lineItem.GST_Amount__c = 35;
        lineItem.Invoice__c = invoice.Id;
        insert lineItem;

        Advance__c advance = [SELECT Id, Amount__c, GST_Amount__c FROM Advance__c WHERE Advance_No__c = '888888888'];

        Test.startTest();
        Invoice_Advance__c invAdv = new Invoice_Advance__c();
        invAdv.Invoice_Line_Item__c = lineItem.Id;
        invAdv.Advance__c = advance.Id;
        invAdv.Description__c = 'Test Advance';
        insert invAdv;
        Test.stopTest();

        Invoice_Line_Item__c lineItemAfter = [SELECT Nett_Amount__c, 
                                                    Nett_GST_Amount__c, 
                                                    Utilized_Advance_Amount__c, 
                                                    Utilized_Advance_GST_Amount__c
                                              FROM Invoice_Line_Item__c
                                              WHERE Id =: lineItem.Id];

        Advance__c advanceAfter = [SELECT Status__c FROM Advance__c WHERE Id=:advance.Id];
        System.assertEquals('In Use', advanceAfter.Status__c);

        System.assertEquals(lineItem.Amount__c - advance.Amount__c, lineItemAfter.Nett_Amount__c);
        System.assertEquals(lineItem.GST_Amount__c - advance.GST_Amount__c, lineItemAfter.Nett_GST_Amount__c);
    }
}