force-app/main/default/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>APPLOG-{0000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Log</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Log__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Class Name</description>
    <label>Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/RequestedBy__c.field-meta.xml
<CustomField>
    <fullName>RequestedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the user who made the request that made this call back</description>
    <label>RequestedBy</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Application_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>Stacktrace__c</fullName>
    <label>Stacktrace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Awaiting Response&quot;</defaultValue>
    <description>This will be updated by the callback to Processing, Success or Failure</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Response</fullName>
                <default>true</default>
                <label>Awaiting Response</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AppLogUtilityTest.cls
/**
 * @description       : 
 * @author            : Mark Alvin Tayag (mtayag@salesforce.com)
 * @group             : 
 * @last modified on  : 10-11-2020
 * @last modified by  : Mark Alvin Tayag (mtayag@salesforce.com)
 * Modifications Log 
 * Ver   Date         Author                                     Modification
 * 1.0   10-11-2020   Mark Alvin Tayag (mtayag@salesforce.com)   Initial Version
**/
@IsTest
public without sharing class AppLogUtilityTest {
    @IsTest
    static void createAppLog(){
        
        Test.startTest();
        insert AppLogUtility.createApplicationLog('stacktrace', 'AppLogUtility', 'xxxxxxx');
        Test.stopTest();

        List<Application_Log__c> appLogs = [SELECT Class__c, RecordId__c, RequestedBy__c, Status__c, Stacktrace__c FROM Application_Log__c];
        System.assertEquals(1, appLogs.size());
        System.assertEquals('stacktrace', appLogs[0].Stacktrace__c);
        System.assertEquals('AppLogUtility', appLogs[0].Class__c);
        System.assertEquals('xxxxxxx', appLogs[0].RecordId__c);
        System.assertEquals(UserInfo.getUserId(), appLogs[0].RequestedBy__c);
        System.assertEquals('Failure', appLogs[0].Status__c);
        
    }
}