force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/GST_Calculated__c.field-meta.xml
<CustomField>
    <fullName>GST_Calculated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>GST Calculated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/GST_Code__c.field-meta.xml
<CustomField>
    <fullName>GST_Code__c</fullName>
    <label>GST Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/GST_Mode__c.field-meta.xml
<CustomField>
    <fullName>GST_Mode__c</fullName>
    <label>GST Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_Mode</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/GST_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>02</fullName>
        <label>0% (Oversea)</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <default>true</default>
        <label>7%</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>0% (Local)</label>
    </customValue>
    <masterLabel>GST Code</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/GST_Mode.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Full</fullName>
        <default>true</default>
        <label>Full</label>
    </customValue>
    <customValue>
        <fullName>Nett</fullName>
    </customValue>
    <masterLabel>GST Mode</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InvoiceLineItemTriggerHandler.cls
public without sharing class InvoiceLineItemTriggerHandler {
    public static void calculateGST(List<Invoice_Line_Item__c> lineItemList, Map<Id, Invoice_Line_Item__c> lineItemMap) {
        Map<String, Decimal> gstCodeMap = Utility.getGSTCodeMap();
        List<Invoice_Line_Item__c> updateLineItem = new List<Invoice_Line_Item__c>();
        for (Invoice_Line_Item__c lineItem : lineItemList) {
            if (lineItemMap.containsKey(lineItem.Id)) {
                Invoice_Line_Item__c oldLineItem = lineItemMap.get(lineItem.Id);
                if (lineItem.GST_Calculated__c == true) {
                    Invoice_Line_Item__c clearFlag = new Invoice_Line_Item__c();
                    clearFlag.Id = lineItem.Id;
                    clearFlag.GST_Calculated__c = false;
                    updateLineItem.add(clearFlag);
                    continue;
                }
                if (oldLineItem.Amount__c == lineItem.Amount__c &&
                    oldLineItem.GST_Code__c == lineItem.GST_Code__c &&
                    oldLineItem.GST_Mode__c == lineItem.GST_Mode__c) {
                    continue;
                }
            }

            Invoice_Line_Item__c lineItemUpdate = new Invoice_Line_Item__c();
            lineItemUpdate.Id = lineItem.Id;
            
            if (lineItem.GST_Mode__c == 'Nett') {
                Decimal gstAmt = Utility.calculateGST(lineItem.Amount__c, lineItem.GST_Code__c, gstCodeMap, lineItem.GST_Mode__c);
                lineItemUpdate.GST_Amount__c = gstAmt;
                lineItemUpdate.Amount__c = lineItem.Amount__c - lineItemUpdate.GST_Amount__c;
            }
            else {
                lineItemUpdate.GST_Amount__c = Utility.calculateGST(lineItem.Amount__c, lineItem.GST_Code__c, gstCodeMap);
            }
            lineItemUpdate.GST_Calculated__c = true;
            updateLineItem.add(lineItemUpdate);
        }

        if (updateLineItem.size() > 0) {
            update updateLineItem;
        }
    }
}