force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <displayFormat>Course-{00000}</displayFormat>
        <label>Course Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Mode_Of_Study__c.field-meta.xml
<CustomField>
    <fullName>Mode_Of_Study__c</fullName>
    <label>Mode Of Study</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On-Campus</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Payment_Option__c.field-meta.xml
<CustomField>
    <fullName>Payment_Option__c</fullName>
    <label>Payment Option</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mode_Of_Study__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MastercardVisa</fullName>
                <label>E-Payment (Mastercard/Visa/PayNow)</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <label>Over-the-Counter (Cash/Cheque/Others)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <description>(MVP 1.0) - Course Provider. If the selected value is &quot;SIM Online&quot; it will be created in SIM Canvas</description>
    <label>Provider</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIM</fullName>
            </value>
            <value>
                <fullName>RMIT</fullName>
            </value>
            <value>
                <fullName>SIM Online</fullName>
                <isActive>false</isActive>
                <label>SIM Online</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/recordTypes/Course.recordType-meta.xml
<RecordType>
    <fullName>Course</fullName>
    <active>true</active>
    <description>Public Courses /Courses without SSG Modules/Courses with Skill future credit</description>
    <label>Course</label>
</RecordType>

force-app/main/default/objects/Course_Registration__c/Course_Registration__c.object-meta.xml
<CustomObject>
    <label>Course Registration</label>
    <nameField>
        <displayFormat>REG-{0000}</displayFormat>
        <label>Course Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Registrations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Registration__c/fields/Course_Run_Id__c.field-meta.xml
<CustomField>
    <fullName>Course_Run_Id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course Run</label>
    <referenceTo>Course_Run__c</referenceTo>
    <relationshipLabel>Course Registrations</relationshipLabel>
    <relationshipName>Course_Registrations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Run__c/Course_Run__c.object-meta.xml
<CustomObject>
    <label>Course Run</label>
    <nameField>
        <displayFormat>COURSERUN-{000000}</displayFormat>
        <label>Course Run Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Run</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Run__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Run</relationshipLabel>
    <relationshipName>Course_Run</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ePayment_Account_No__mdt/ePayment_Account_No__mdt.object-meta.xml
<CustomObject>
    <label>ePayment Account No</label>
    <pluralLabel>ePayment Account Nos</pluralLabel>
</CustomObject>

force-app/main/default/objects/ePayment_Account_No__mdt/fields/Course_Provider__c.field-meta.xml
<CustomField>
    <fullName>Course_Provider__c</fullName>
    <label>Course Provider</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ePayment_Account_No__mdt/fields/ePayment_Account_No__c.field-meta.xml
<CustomField>
    <fullName>ePayment_Account_No__c</fullName>
    <label>ePayment Account No</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Advance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Advance_Amount__c</fullName>
    <label>Advance Amount</label>
    <summarizedField>Invoice_Line_Item__c.Advance_Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Advance_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Advance_GST_Amount__c</fullName>
    <label>Advance GST Amount</label>
    <summarizedField>Invoice_Line_Item__c.Advance_GST_Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <summarizedField>Invoice_Line_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Course_Registration__c.field-meta.xml
<CustomField>
    <fullName>Course_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Registration</label>
    <referenceTo>Course_Registration__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Final_Amount__c.field-meta.xml
<CustomField>
    <fullName>Final_Amount__c</fullName>
    <formula>Nett_Amount__c +  Nett_GST_Amount__c - (Advance_Amount__c +  Advance_GST_Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <label>GST Amount</label>
    <summarizedField>Invoice_Line_Item__c.GST_Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Nett_Amount__c.field-meta.xml
<CustomField>
    <fullName>Nett_Amount__c</fullName>
    <label>Nett Amount</label>
    <summarizedField>Invoice_Line_Item__c.Nett_Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Nett_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Nett_GST_Amount__c</fullName>
    <label>Nett GST Amount</label>
    <summarizedField>Invoice_Line_Item__c.Nett_GST_Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoice_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY-{000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Course_Registration__c.field-meta.xml
<CustomField>
    <fullName>Course_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Registration</label>
    <referenceTo>Course_Registration__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/ePayment_Account_No__c.field-meta.xml
<CustomField>
    <fullName>ePayment_Account_No__c</fullName>
    <label>ePayment Account No</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Receipt_Created__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked once the receipt has been created for a successful payment</description>
    <label>Receipt Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <formula>If(AuthResp__c=&apos;OK&apos;,&apos;Success&apos;,
If(ISBLANK(AuthResp__c),&apos;Pending&apos;,&apos;Failure&apos;))</formula>
    <label>Transaction Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Gateway__mdt/fields/Payment_Gateway_Return_URL__c.field-meta.xml
<CustomField>
    <fullName>Payment_Gateway_Return_URL__c</fullName>
    <label>Payment Gateway Return URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Gateway__mdt/fields/Payment_Gateway_URL__c.field-meta.xml
<CustomField>
    <fullName>Payment_Gateway_URL__c</fullName>
    <label>Payment Gateway URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Gateway__mdt/fields/Self_Signed_Cert_Name__c.field-meta.xml
<CustomField>
    <fullName>Self_Signed_Cert_Name__c</fullName>
    <label>Self Signed Cert Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RECP-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Invoice_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Invoice Generation - In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Unpaid</fullName>
    </customValue>
    <customValue>
        <fullName>Partial</fullName>
    </customValue>
    <customValue>
        <fullName>Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled - Credit Note</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled - Debit Note</fullName>
    </customValue>
    <customValue>
        <fullName>Refunded</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Invoice Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PaymentController.cls
/*************************************************************************************************************
 * @name			PaymentController
 * @author			BLR\rohit.pal <rohit.pal@crmit.com> Salesforce
 * @created			06 / 10 / 2020
 * @description		Description of your code
 *
 * Changes (version)
 * -----------------------------------------------------------------------------------------------------------
 * 				No.		Date			Author					Description
 * 				----	------------	--------------------	----------------------------------------------
 * @version		1.0		2020-10-06		BLR\rohit.pal			Changes desription
 *              1.1     2020-10-21      Alvin Tayag             Changed helper method to private, removed createRecipt 
 *                                                              and replaced with handlePayment, added emptyReturn handling to helper methods
 *              1.2     2020-01-28      Rob/Poon Koon           Added in methods for getting course info and payment options
 *              1.3     2021-03-25      Poon Koon               1. Add in method to generate signature for request signing
 *                                                              2. Add in method to get ePayment Account No
**************************************************************************************************************/
public without sharing class PaymentController {
    /**
   * @description 
   * @author Rohit Pal | 10-06-2020 
   * @param  null 
   * @return Payment_Gateway__mdt 
   **/
    //2021-03-30 Poon Koon: Get self signed cert name
    @AuraEnabled
    public static Payment_Gateway__mdt getPaymentGateway(){
        
        return [SELECT Id,
                       MasterLabel,
                       Payment_Gateway_URL__c,
                       Payment_Gateway_Return_URL__c,
                       Self_Signed_Cert_Name__c 
                FROM Payment_Gateway__mdt];
    }
    
    @AuraEnabled
    public static List<String> handlePayment (String paymentRecordId) {
        List<String> result = new List<String>();
        if(string.isBlank(paymentRecordId)) {
            result.add('Invalid Record');
            result.add('');
            return result;
        }
        try {
            Payment__c paymentRecord = getPaymentRecord(paymentRecordId);
            if (paymentRecord.Transaction_Status__c == 'Success' && !paymentRecord.Receipt_Created__c) {
                //Create Receipt
                Receipt__c receipt = new Receipt__c();
                Invoice__c invoice = getInvoiceRecord(paymentRecord.Invoice__c);
                receipt.Payment__c = paymentRecord.Id;
                receipt.Amount__c = invoice.Nett_Amount__c - invoice.Advance_Amount__c;
                receipt.GST_Amount__c = invoice.Nett_GST_Amount__c - invoice.Advance_GST_Amount__c;
                insert receipt;

                Payment__c payment = new Payment__c();
                payment.Id = paymentRecordId;
                payment.Receipt_Created__c = true;

                update payment;

                result.add('Success');
                result.add(receipt.Id);
            }
            else if (paymentRecord.Transaction_Status__c == 'Success' && paymentRecord.Receipt_Created__c) {
                //Just show success message and get Receipt Record
                Receipt__c receipt = getReceiptRecord(paymentRecordId);
                result.add('Success');
                result.add(receipt.Id != null ? receipt.Id : paymentRecordId);
            }
            else if (paymentRecord.Transaction_Status__c == 'Failure') {
                //Show error message
                result.add('Failure');
                result.add(paymentRecord.Id);
            }
            else {
                //Catch all Failure
                result.add('Failure');
                result.add(paymentRecord.Id);
            }
        }
        catch (Exception e) {
            result.add('Failure');
            result.add('');
        }

        return result;
    }

    /**
    * @description 
    * @author Rohit Pal | 10-08-2020 
    * @param strPaymentId 
    * @return string 
    **/
    @AuraEnabled
    public static formInformationWrapper getInvoiceRecordInformation(string strInvoiceId){
        formInformationWrapper objformInformationWrapper;
        Invoice__c objInvoice = new Invoice__c();
        Payment__c objPayment = new Payment__c();  

        if(string.isNotBlank(strInvoiceId)){
            objInvoice = getInvoiceRecord(strInvoiceId);
            if (objInvoice.Status__c == 'Paid') {
                objformInformationWrapper = new formInformationWrapper(objInvoice, null);
            }
            else {
                String paymentId = createPaymentRecord(strInvoiceId);
                objPayment = [SELECT Id,
                                    Name,
                                    Invoice__c,
                                    ePayment_Account_No__c
                            FROM Payment__c 
                            WHERE Id =: paymentId limit 1];
                objformInformationWrapper = new formInformationWrapper(objInvoice, objPayment);
            }
        }
        return objformInformationWrapper;
    }

    /**
    * @description 
    * @author Rohit Pal | 10-08-2020 
    * @param strInvoiceId 
    * @return Invoice__c 
    **/
    private static Invoice__c getInvoiceRecord(string strInvoiceId){
        try {
            return [SELECT Id,
                            Name,
                            Amount__c,
                            GST_Amount__c,
                            Nett_Amount__c,
                            Nett_GST_Amount__c,
                            Final_Amount__c,
                            Course_Registration__c,
                            Status__c,
                            Advance_Amount__c,
                            Advance_GST_Amount__c,
                            Course_Registration__r.Course_Run_Id__r.Course__r.Provider__c
                    FROM Invoice__c 
                    WHERE Id =: strInvoiceId limit 1];
        }
        catch (Exception e) {
            return new Invoice__c();
        }
    }
    /**
    * @description 
    * @author Rohit Pal | 10-08-2020 
    * @param strPaymentId 
    * @return Invoice__c 
    **/
    private static Payment__c getPaymentRecord(string strPaymentId){
        try {
        return [SELECT Id,
                        Name,
                        Invoice__c,
                        Transaction_Status__c,
                        Receipt_Created__c
                FROM Payment__c 
                WHERE Id =: strPaymentId limit 1];
        }
        catch (Exception e) {
            return new Payment__c();
        }
    }

    
    private static Receipt__c getReceiptRecord(string strPaymentId){
        //Handle Empty returns
        try {
            return [SELECT Id
                    FROM Receipt__c 
                    WHERE Payment__c =: strPaymentId limit 1];
        }
        catch (Exception e) {
            return new Receipt__c();
        }
    }
    
    //2021-04-01 Poon Koon: To get account no based on course provider
    private static string createPaymentRecord(string strInvoiceId){
        Payment__c objPayment = new Payment__c();
        if(string.isNotBlank(strInvoiceId)){
            invoice__c objInvoice = getInvoiceRecord(strInvoiceId);
            objPayment.ePayment_Account_No__c = getEPaymentAccountNo(objInvoice.Course_Registration__r.Course_Run_Id__r.Course__r.Provider__c);
            objPayment.Transaction_Date__c = system.now();
            objPayment.Invoice__c = objInvoice.id;
            objPayment.Course_Registration__c = objInvoice.Course_Registration__c;
            insert objPayment;
            return objPayment.Id;
        }
        return '';
    }

    //2021-04-01 Poon Koon: To get account no based on course provider
    private static string getEPaymentAccountNo(string strCourseProvider){
        ePayment_Account_No__mdt mdtEPaymentAccountNo = new ePayment_Account_No__mdt();
        if(string.isNotBlank(strCourseProvider)){
            mdtEPaymentAccountNo = [SELECT Id, ePayment_Account_No__c FROM ePayment_Account_No__mdt WHERE Course_Provider__c =: strCourseProvider];
            return mdtEPaymentAccountNo.ePayment_Account_No__c;
        }
        return '';
    }

    /*************************************************************************************************************
     * @name			PaymentController
     * @author			BLR\rohit.pal <rohit.pal@crmit.com> Salesforce
     * @created			08 / 10 / 2020
     * @description		Description of your code
     *
     * Changes (version)
     * -----------------------------------------------------------------------------------------------------------
     * 				No.		Date			Author					Description
     * 				----	------------	--------------------	----------------------------------------------
     * @version		1.0		2020-10-08		BLR\rohit.pal			Changes desription
     *
    **************************************************************************************************************/
    public class formInformationWrapper{

        @AuraEnabled
        public Invoice__c objInvoice {get;set;}
        @AuraEnabled
        public Payment__c objPayment {get;set;}

        public formInformationWrapper(Invoice__c objInvoice  , Payment__c objPayment){
            this.objInvoice = objInvoice;
            this.objPayment = objPayment;
        }
    }
    
    /**************************************************/
    /* 28Jan2021 - Rob - Payment Option Configuration */
    /**************************************************/

    @AuraEnabled
    public static formInformationWrapper1 getCourseRecordInformation(string strInvoiceId){
        formInformationWrapper1 objformInformationWrapper1;
        Course__c objCourse = new Course__c();
        
        String strCourseRegId = getCourseRegId (strInvoiceId);
        String strCourseId = getCourseId (strCourseRegId);

        objCourse = [SELECT Mode_Of_Study__c, Payment_Option__c
                    FROM Course__c
                    WHERE Id =: strCourseId limit 1];
        
        List<picklistValuesWrapper> paymentOptions = getPaymentOptions(objCourse.Mode_Of_Study__c);
        
        objformInformationWrapper1 = new formInformationWrapper1(objCourse, paymentOptions);
        return objformInformationWrapper1;
    }

    public class formInformationWrapper1{

        @AuraEnabled
        public Course__c objCourse {get;set;}
        @AuraEnabled
        public List<picklistValuesWrapper> paymentOptions {get; set;}

        public formInformationWrapper1(Course__c objCourse, List<picklistValuesWrapper> paymentOptions){
            this.objCourse = objCourse;
            this.paymentOptions = paymentOptions;
        }
    }

    public class picklistValuesWrapper{
        @AuraEnabled
        public String label {get; set;}
        @AuraEnabled
        public String value {get; set;}

        public picklistValuesWrapper(String label, String value){
            this.label = label;
            this.value = value;
        }
    }

	/** get CourseRegID **/
	private static string getCourseRegID(string strInvoiceId){
        Course_Registration__c objCourseRegId = new Course_Registration__c();
        Invoice__c objInvoice1 = getInvoiceRecord(strInvoiceId);
        objCourseRegId.Id = objInvoice1.Course_Registration__c;
        return objCourseRegId.Id;
    }
    
    /** get CourseID **/
    private static string getCourseID(string strCourseRegId){
        Course__c objCourseId = new Course__c();
        Course_Registration__c objCourseReg = getCourseRegRecord(strCourseRegId);
        objCourseId.Id = objCourseReg.Course_Run_Id__r.Course__c;
        return objCourseId.Id;
    }

    /** get CourseRegRecord **/
    private static Course_Registration__c getCourseRegRecord(string strCourseRegId){
        //Handle Empty returns
        try {
            return [SELECT Course_Run_Id__r.Course__c
                    FROM Course_Registration__c 
                    WHERE Id =: strCourseRegId limit 1];
        }
        catch (Exception e) {
            return new Course_Registration__c();
        }
    }

    /** get PaymentOptions */
    private static List<picklistValuesWrapper> getPaymentOptions(string strModeOfStudy){
        List<picklistValuesWrapper> listPaymentOptions = New List<picklistValuesWrapper>();
        Map<String, List<String>> mapDependentOptions = Utility.getDependentOptionsImpl(Schema.getGlobalDescribe().get('Course__c').getDescribe().fields.getMap().get('Payment_Option__c'), Schema.getGlobalDescribe().get('Course__c').getDescribe().fields.getMap().get('Mode_Of_Study__c'));
        List<String> listOptions= mapDependentOptions.get(strModeOfStudy);
        for(String option: listOptions) {
            picklistValuesWrapper paymentOption = new picklistValuesWrapper(option.Split('\\|\\|')[0], option.Split('\\|\\|')[1]);
            listPaymentOptions.add(paymentOption);
        }
        return listPaymentOptions;
    }
    
    //2021-03-25 Poon Koon: Method to generate signature
    @AuraEnabled
    public static string generateSignature(string strJSONString, string strCertName){
        Blob data = Blob.valueOf(strJSONString);
        String strSignature = EncodingUtil.base64Encode(System.Crypto.signWithCertificate('RSA-SHA512', data, strCertName));
        return strSignature;
    }
}