force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <displayFormat>Course-{00000}</displayFormat>
        <label>Course Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/GST_Code__c.field-meta.xml
<CustomField>
    <fullName>GST_Code__c</fullName>
    <label>GST Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/GST_Mode__c.field-meta.xml
<CustomField>
    <fullName>GST_Mode__c</fullName>
    <label>GST Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_Mode</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Non_Member_Fee__c.field-meta.xml
<CustomField>
    <fullName>Non_Member_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Non-Member Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course__c/recordTypes/Course.recordType-meta.xml
<RecordType>
    <fullName>Course</fullName>
    <active>true</active>
    <description>Public Courses /Courses without SSG Modules/Courses with Skill future credit</description>
    <label>Course</label>
</RecordType>

force-app/main/default/objects/Course_Registration__c/Course_Registration__c.object-meta.xml
<CustomObject>
    <label>Course Registration</label>
    <nameField>
        <displayFormat>REG-{0000}</displayFormat>
        <label>Course Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Registrations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Run__c/Course_Run__c.object-meta.xml
<CustomObject>
    <label>Course Run</label>
    <nameField>
        <displayFormat>COURSERUN-{000000}</displayFormat>
        <label>Course Run Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Run</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Run__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Run</relationshipLabel>
    <relationshipName>Course_Run</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <label>Discount Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <label>GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/GST_Code__c.field-meta.xml
<CustomField>
    <fullName>GST_Code__c</fullName>
    <label>GST Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Percentage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Discount__c/recordTypes/Early_Bird.recordType-meta.xml
<RecordType>
    <fullName>Early_Bird</fullName>
    <active>true</active>
    <label>Early Bird</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <summarizedField>Invoice_Line_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Course_Registration__c.field-meta.xml
<CustomField>
    <fullName>Course_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Registration</label>
    <referenceTo>Course_Registration__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <label>GST Amount</label>
    <summarizedField>Invoice_Line_Item__c.GST_Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice_Discount__c/Invoice_Discount__c.object-meta.xml
<CustomObject>
    <label>Invoice Discount</label>
    <nameField>
        <displayFormat>IVDIS-{0000}</displayFormat>
        <label>Invoice Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Discount__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <inlineHelpText>If left empty, Amount, GST Amount, and GST Code will be taken from the Discount selected</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Discount__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Discount</label>
    <referenceTo>Discount__c</referenceTo>
    <relationshipLabel>Invoice Discounts</relationshipLabel>
    <relationshipName>Invoice_Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Discount__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <inlineHelpText>If left empty, Amount, GST Amount, and GST Code will be taken from the Discount selected</inlineHelpText>
    <label>GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Discount__c/fields/GST_Mode__c.field-meta.xml
<CustomField>
    <fullName>GST_Mode__c</fullName>
    <inlineHelpText>Full - Exclusive of GST
Nett - Inclusive of GST</inlineHelpText>
    <label>GST Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_Mode</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Discount__c/fields/Invoice_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Line_Item__c</fullName>
    <label>Invoice Line Item</label>
    <referenceTo>Invoice_Line_Item__c</referenceTo>
    <relationshipLabel>Invoice Discounts</relationshipLabel>
    <relationshipName>Invoice_Discounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Course_Registration__c.field-meta.xml
<CustomField>
    <fullName>Course_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Registration</label>
    <referenceTo>Course_Registration__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Course_Run__c.field-meta.xml
<CustomField>
    <fullName>Course_Run__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Run</label>
    <referenceTo>Course_Run__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/GST_Code__c.field-meta.xml
<CustomField>
    <fullName>GST_Code__c</fullName>
    <label>GST Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/GST_Mode__c.field-meta.xml
<CustomField>
    <fullName>GST_Mode__c</fullName>
    <label>GST Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_Mode</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/GST_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>02</fullName>
        <label>0% (Oversea)</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <default>true</default>
        <label>7%</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>0% (Local)</label>
    </customValue>
    <masterLabel>GST Code</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/GST_Mode.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Full</fullName>
        <default>true</default>
        <label>Full</label>
    </customValue>
    <customValue>
        <fullName>Nett</fullName>
    </customValue>
    <masterLabel>GST Mode</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InvoiceDiscountTriggerHandlerTest.cls
@IsTest
public without sharing class InvoiceDiscountTriggerHandlerTest {


    //2021-03-31 Poon Koon: Update data preparation class
    static void prepareDataForCourse(){
        Id b2cLearnerRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('B2C_Learner').getRecordTypeId();
        Account acct = new Account();
        acct.RecordTypeId = b2cLearnerRT;
        acct.FirstName = 'Test';
        acct.LastName = 'Account';
        acct.PersonEmail = 'testApexUser@sim.edu.sg';
        acct.Credit_Term_Days__c = 14;
        insert acct;
        acct = [SELECT Id, PersonContactId FROM Account];

        Id courseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Course').getRecordTypeId();
        Course__c course = TestDataFactory.createCourse(null);
        course.RecordTypeId = courseRT;
        course.Non_Member_Fee__c = 100;
        insert course;

        Course_Run__c courseRun = TestDataFactory.createCourseRun();
        courseRun.Course__c = course.Id;
        insert courseRun;

        //Create Course Registration from TestDataFactory
        Course_Registration__c reg = TestDataFactory.createCourseRegistration(courseRun.Id, acct.PersonContactId);
        insert reg;
    }

    @IsTest
    static void calculateGST(){
        prepareDataForCourse();
        
        Id earlyBirdRT = Schema.SObjectType.Discount__c.getRecordTypeInfosByDeveloperName().get('Early_Bird').getRecordTypeId();
        Discount__c disc = TestDataFactory.createDiscount();
        disc.Amount__c = 50;
        disc.GST_Amount__c = 0;
        disc.GST_Code__c = '12';
        disc.Percentage__c = false;
        disc.RecordTypeId = earlyBirdRT;
        insert disc;

        Course_Registration__c reg = [SELECT Id FROM Course_Registration__c];
        InvoiceUtility.generateInvoiceForRegistration(reg.Id);
        List<Invoice__c> invoice = [SELECT Id, Amount__c, GST_Amount__c FROM Invoice__c];
        Test.startTest();
        List<Invoice_Line_Item__c> invoiceLineItems = [SELECT Id, Amount__c, GST_Amount__c FROM Invoice_Line_Item__c WHERE Invoice__c =: invoice[0].Id];
        Invoice_Discount__c invdisc = new Invoice_Discount__c();
        invdisc.Discount__c = disc.Id;
        invdisc.Invoice_Line_Item__c = invoiceLineItems[0].Id;
        invdisc.GST_Code__c = '12';
        invdisc.GST_Mode__c = 'Full';
        insert invdisc;

        Invoice_Discount__c invdiscUpdate = new Invoice_Discount__c();
        invdiscUpdate.Id = invdisc.Id;
        invdiscUpdate.Amount__c = 10;
        update invdiscUpdate;
        Test.stopTest();

        Invoice_Discount__c invDiscAfter = [SELECT Amount__c, GST_Amount__c FROM Invoice_Discount__c];
        System.assertEquals(10, invDiscAfter.Amount__c);
        System.assertEquals(0.7, invDiscAfter.GST_Amount__c);
    }



    @IsTest
    static void calculateGSTNett(){
        prepareDataForCourse();
        
        Id earlyBirdRT = Schema.SObjectType.Discount__c.getRecordTypeInfosByDeveloperName().get('Early_Bird').getRecordTypeId();
        Discount__c disc = TestDataFactory.createDiscount();
        disc.Amount__c = 50;
        disc.GST_Amount__c = 0;
        disc.GST_Code__c = '12';
        disc.Percentage__c = false;
        disc.RecordTypeId = earlyBirdRT;
        insert disc;

        Course_Registration__c reg = [SELECT Id FROM Course_Registration__c];
        InvoiceUtility.generateInvoiceForRegistration(reg.Id);
        List<Invoice__c> invoice = [SELECT Id, Amount__c, GST_Amount__c FROM Invoice__c];
        Test.startTest();
        List<Invoice_Line_Item__c> invoiceLineItems = [SELECT Id, Amount__c, GST_Amount__c FROM Invoice_Line_Item__c WHERE Invoice__c =: invoice[0].Id];
        Invoice_Discount__c invdisc = new Invoice_Discount__c();
        invdisc.Discount__c = disc.Id;
        invdisc.Invoice_Line_Item__c = invoiceLineItems[0].Id;
        invdisc.GST_Code__c = '12';
        invdisc.GST_Mode__c = 'Nett';
        insert invdisc;

        Invoice_Discount__c invdiscUpdate = new Invoice_Discount__c();
        invdiscUpdate.Id = invdisc.Id;
        invdiscUpdate.Amount__c = 10;
        update invdiscUpdate;
        Test.stopTest();

        Invoice_Discount__c invDiscAfter = [SELECT Amount__c, GST_Amount__c FROM Invoice_Discount__c];
        //2001211130 Desmond
        Decimal gstAmt = 10 - (10 / 1.07);
        //Decimal AmountWoGST = (10 / 1.07).setScale(2,RoundingMode.HALF_UP);
        //Decimal gstAmt = 10 - AmountWoGST;

        System.assertEquals(10 - gstAmt.setScale(2, RoundingMode.HALF_UP), invDiscAfter.Amount__c);
        System.assertEquals(gstAmt.setScale(2, RoundingMode.HALF_UP), invDiscAfter.GST_Amount__c);
        System.assertEquals(10, invDiscAfter.Amount__c + invDiscAfter.GST_Amount__c);
    }
}