force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <displayFormat>Course-{00000}</displayFormat>
        <label>Course Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/recordTypes/Course.recordType-meta.xml
<RecordType>
    <fullName>Course</fullName>
    <active>true</active>
    <description>Public Courses /Courses without SSG Modules/Courses with Skill future credit</description>
    <label>Course</label>
</RecordType>

force-app/main/default/objects/Course_Run__c/Course_Run__c.object-meta.xml
<CustomObject>
    <label>Course Run</label>
    <nameField>
        <displayFormat>COURSERUN-{000000}</displayFormat>
        <label>Course Run Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Run</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Run__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Run</relationshipLabel>
    <relationshipName>Course_Run</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Run__c/fields/Course_Run_Code__c.field-meta.xml
<CustomField>
    <fullName>Course_Run_Code__c</fullName>
    <externalId>true</externalId>
    <label>Course Run Code</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CourseRunTriggerHandlerTest.cls
@IsTest
public with sharing class CourseRunTriggerHandlerTest {
    
    @IsTest
    static void generateCourseRunCode(){
        Course__c course = TestDataFactory.createCourse(null);
        insert course;
        Course_Run__c courseRun = TestDataFactory.createCourseRun();
        courseRun.Course_Run_Code__c = '';
        courseRun.Course__c = course.Id;

        Test.startTest();
        insert courseRun;
        Test.stopTest();

        Course_Run__c courseRunAfter = [SELECT Course_Run_Code__c FROM Course_Run__c WHERE Id=: courseRun.Id];
        System.assert(courseRunAfter.Course_Run_Code__c != '');
        
    }

    @IsTest
    static void generateCourseRunCodeMultiInsert(){
        Course__c course = TestDataFactory.createCourse(null);
        insert course;
        Course_Run__c courseRun = TestDataFactory.createCourseRun();
        courseRun.Course_Run_Code__c = '';
        courseRun.Course__c = course.Id;
        Course_Run__c courseRun2 = TestDataFactory.createCourseRun();
        courseRun2.Course_Run_Code__c = '';
        courseRun2.Course__c = course.Id;

        List<Course_Run__c> courseRuns = new List<Course_Run__c>();
        courseRuns.add(courseRun);
        courseRuns.add(courseRun2);
        Test.startTest();
        insert courseRuns;
        Test.stopTest();

        List<Course_Run__c> courseRunAfter = [SELECT Course_Run_Code__c FROM Course_Run__c];
        System.assert(courseRunAfter[0].Course_Run_Code__c != '');
        System.assert(courseRunAfter[1].Course_Run_Code__c != '');
    }

    @IsTest
    static void generateCourseRunCodeExisting(){
        Course__c course = TestDataFactory.createCourse(null);
        insert course;
        Course_Run__c courseRun = TestDataFactory.createCourseRun();
        courseRun.Course_Run_Code__c = '';
        courseRun.Course__c = course.Id;
        insert courseRun;

        Course_Run__c courseRun2 = TestDataFactory.createCourseRun();
        courseRun2.Course_Run_Code__c = '';
        courseRun2.Course__c = course.Id;
        Test.startTest();
        insert courseRun2;
        Test.stopTest();

        List<Course_Run__c> courseRunAfter = [SELECT Course_Run_Code__c FROM Course_Run__c];
        System.assert(courseRunAfter[0].Course_Run_Code__c != '');
        System.assert(courseRunAfter[1].Course_Run_Code__c != '');
    }
}