force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <displayFormat>Course-{00000}</displayFormat>
        <label>Course Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Funding__c.field-meta.xml
<CustomField>
    <fullName>Funding__c</fullName>
    <description>Funding/Subsidies applicable for this Course</description>
    <label>Funding</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Funding</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Public_Course__c.field-meta.xml
<CustomField>
    <fullName>Public_Course__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Public Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/Course_Registration__c.object-meta.xml
<CustomObject>
    <label>Course Registration</label>
    <nameField>
        <displayFormat>REG-{0000}</displayFormat>
        <label>Course Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Registrations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Registration__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <inlineHelpText>Please leave it as &quot;Blank&quot; if you wish to repopulate the company details</inlineHelpText>
    <label>Company Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Run__c/Course_Run__c.object-meta.xml
<CustomObject>
    <label>Course Run</label>
    <nameField>
        <displayFormat>COURSERUN-{000000}</displayFormat>
        <label>Course Run Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Run</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Run__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Run</relationshipLabel>
    <relationshipName>Course_Run</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Run__c/fields/Course_Run_Code__c.field-meta.xml
<CustomField>
    <fullName>Course_Run_Code__c</fullName>
    <externalId>true</externalId>
    <label>Course Run Code</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Funding.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SkillsFuture Credit</fullName>
    </customValue>
    <customValue>
        <fullName>SkillsFuture Funding</fullName>
    </customValue>
    <customValue>
        <fullName>UTAP Funding</fullName>
    </customValue>
    <customValue>
        <fullName>Test Value</fullName>
    </customValue>
    <customValue>
        <fullName>IBF Funding</fullName>
    </customValue>
    <masterLabel>Funding</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ShortenURLInvocableForAnonSurveyTest.cls
/*************************************************************************************************************
 * @name             ShortenURLInvocableForAnonSurveyTest
 * @author           Poon Koon
 * @created          2021-03-10
 * @description      Description of your code
 *
 * Changes (version)
 * -----------------------------------------------------------------------------------------------------------
 *               No.     Date            Author                  Description
 *               ----    ------------    --------------------    ----------------------------------------------
 * @version      1.0     2021-03-10      Poon Koon               Initial Version
 **************************************************************************************************************/
@isTest(seeAllData = false)
private class ShortenURLInvocableForAnonSurveyTest {
    /**
     * @description 
     * @author Poon Koon | 2021-03-10 
     **/

    @testSetup
    static void setupTestData() {
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];  
        
        Profile profile1 = [Select Id from Profile where name = 'System Administrator'];
        User portalAccountOwner1 = new User(
                                            UserRoleId = portalRole.Id,
                                            ProfileId = profile1.Id,
                                            Username = System.now().millisecond() + 'test222@test.com',
                                            Alias = 'batman',
                                            Email='bruce.wayne@wayneenterprises.com',
                                            EmailEncodingKey='UTF-8',
                                            Firstname='Bruce',
                                            Lastname='Wayne',
                                            LanguageLocaleKey='en_US',
                                            LocaleSidKey='en_US',
                                            TimeZoneSidKey='America/Chicago'
                                            );
        Database.insert(portalAccountOwner1);
        user portaluser; 
        Course_Run__c cr;
        Course_Registration__c objCourseRegistration;
        blob file =  Blob.valueOf('sample text');
        attachment att;
        Contact contact1;
        Course__c objCourse;

        System.runAs ( portalAccountOwner1 ) {    
         Account portalAccount1 = new Account(
                                            Name = 'TestAccount'
                                            );
                Database.insert(portalAccount1);
                
                //Create contact
                contact1 = new Contact(
                FirstName = 'Test',
                Lastname = 'McTesty',
                AccountId = portalAccount1.Id,
                Email = 'testCon@test.com',
                Company_Name__c = 'TestAccount'                
                );
                Database.insert(contact1);
                
                objCourse  = TestDataFactory.createCourse(portalAccount1.Id);
                objCourse.Public_Course__c = true;
                objCourse.Funding__c='SkillsFuture Credit';
                //update objCourse;
                insert objCourse;
                       
                cr = TestDataFactory.createCourseRun();
                cr.Course__c = objCourse.id;
                cr.Public_Course__c = true;
                cr.Course_Run_Code__c = 'testCode1234';
                insert cr;
            }
    }

    /**
     * @description 
     * @author Poon Koon | 2021-03-10 
     **/
    static testMethod void shortenAsyncForAnonSurveyTest() {
        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new ShortenURLMock());
        List < List < String >> listCourseRegistrationSurveyURL = new List < List < String >> ();
        List < String > listCrsRegSurveyURL = new List < String > ();

        Course_Run__c courseRun = [SELECT Id FROM Course_Run__c LIMIT 1];

        listCrsRegSurveyURL.add('https://www.InvitationLinkAnonymous.com');
        listCrsRegSurveyURL.add(courseRun.Id);
        listCourseRegistrationSurveyURL.add(listCrsRegSurveyURL);


        ShortenURLInvocableForAnonSurvey.shortenForAnonSurvey(listCourseRegistrationSurveyURL);
        
        Test.stopTest();
    }

}