force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <displayFormat>Course-{00000}</displayFormat>
        <label>Course Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Full_Fee__c.field-meta.xml
<CustomField>
    <fullName>Full_Fee__c</fullName>
    <label>Full Fee</label>
    <summarizedField>Course_Module__c.Full_Fee__c</summarizedField>
    <summaryForeignKey>Course_Module__c.Course__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Non_Member_Fee__c.field-meta.xml
<CustomField>
    <fullName>Non_Member_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Non-Member Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Non_Member_GST_Fee__c.field-meta.xml
<CustomField>
    <fullName>Non_Member_GST_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Non-Member GST Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <description>(MVP 1.0) - Course Provider. If the selected value is &quot;SIM Online&quot; it will be created in SIM Canvas</description>
    <label>Provider</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIM</fullName>
            </value>
            <value>
                <fullName>RMIT</fullName>
            </value>
            <value>
                <fullName>SIM Online</fullName>
                <isActive>false</isActive>
                <label>SIM Online</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/recordTypes/Course.recordType-meta.xml
<RecordType>
    <fullName>Course</fullName>
    <active>true</active>
    <description>Public Courses /Courses without SSG Modules/Courses with Skill future credit</description>
    <label>Course</label>
</RecordType>

force-app/main/default/objects/Course__c/recordTypes/Funded_Course.recordType-meta.xml
<RecordType>
    <fullName>Funded_Course</fullName>
    <active>true</active>
    <description>Courses with SSG Modules</description>
    <label>Funded Course</label>
</RecordType>

force-app/main/default/objects/Course_Discount__c/Course_Discount__c.object-meta.xml
<CustomObject>
    <label>Course Discount</label>
    <nameField>
        <displayFormat>CDISC-{0000}</displayFormat>
        <label>Course Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Discount__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Discounts</relationshipLabel>
    <relationshipName>Course_Discounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Discount__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Discount__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Discount__c</referenceTo>
    <relationshipLabel>Course Discounts</relationshipLabel>
    <relationshipName>Course_Discounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/Course_Module__c.object-meta.xml
<CustomObject>
    <label>Course Module</label>
    <nameField>
        <displayFormat>CMOD-{0000}</displayFormat>
        <label>Course Module Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Module__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Modules</relationshipLabel>
    <relationshipName>Course_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Course Modules</relationshipLabel>
    <relationshipName>Course_Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/Course_Registration__c.object-meta.xml
<CustomObject>
    <label>Course Registration</label>
    <nameField>
        <displayFormat>REG-{0000}</displayFormat>
        <label>Course Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Registrations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Registration__c/fields/Parent_Registration__c.field-meta.xml
<CustomField>
    <fullName>Parent_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Registration</label>
    <referenceTo>Course_Registration__c</referenceTo>
    <relationshipLabel>Course Registrations</relationshipLabel>
    <relationshipName>Course_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/RMIT_Alumni__c.field-meta.xml
<CustomField>
    <fullName>RMIT_Alumni__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RMIT Alumni</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Run__c/Course_Run__c.object-meta.xml
<CustomObject>
    <label>Course Run</label>
    <nameField>
        <displayFormat>COURSERUN-{000000}</displayFormat>
        <label>Course Run Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Run</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Run__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Run</relationshipLabel>
    <relationshipName>Course_Run</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <label>Discount Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <label>GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/No_of_Days__c.field-meta.xml
<CustomField>
    <fullName>No_of_Days__c</fullName>
    <label>No of Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Percentage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Discount__c/recordTypes/Early_Bird.recordType-meta.xml
<RecordType>
    <fullName>Early_Bird</fullName>
    <active>true</active>
    <label>Early Bird</label>
</RecordType>

force-app/main/default/objects/Discount__c/recordTypes/Promotion.recordType-meta.xml
<RecordType>
    <fullName>Promotion</fullName>
    <active>true</active>
    <label>Promotion</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <summarizedField>Invoice_Line_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Course_Registration__c.field-meta.xml
<CustomField>
    <fullName>Course_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Registration</label>
    <referenceTo>Course_Registration__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <label>Discount Amount</label>
    <summarizedField>Invoice_Line_Item__c.Discount_Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Discount_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_GST_Amount__c</fullName>
    <label>Discount GST Amount</label>
    <summarizedField>Invoice_Line_Item__c.Discount_GST_Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <label>GST Amount</label>
    <summarizedField>Invoice_Line_Item__c.GST_Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice_Discount__c/Invoice_Discount__c.object-meta.xml
<CustomObject>
    <label>Invoice Discount</label>
    <nameField>
        <displayFormat>IVDIS-{0000}</displayFormat>
        <label>Invoice Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Discount__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <inlineHelpText>If left empty, Amount, GST Amount, and GST Code will be taken from the Discount selected</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Discount__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Discount</label>
    <referenceTo>Discount__c</referenceTo>
    <relationshipLabel>Invoice Discounts</relationshipLabel>
    <relationshipName>Invoice_Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Discount__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <inlineHelpText>If left empty, Amount, GST Amount, and GST Code will be taken from the Discount selected</inlineHelpText>
    <label>GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Discount__c/fields/Invoice_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Line_Item__c</fullName>
    <label>Invoice Line Item</label>
    <referenceTo>Invoice_Line_Item__c</referenceTo>
    <relationshipLabel>Invoice Discounts</relationshipLabel>
    <relationshipName>Invoice_Discounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Course_Registration__c.field-meta.xml
<CustomField>
    <fullName>Course_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Registration</label>
    <referenceTo>Course_Registration__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Course_Run__c.field-meta.xml
<CustomField>
    <fullName>Course_Run__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Run</label>
    <referenceTo>Course_Run__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <label>Discount Amount</label>
    <summarizedField>Invoice_Discount__c.Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Discount__c.Invoice_Line_Item__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Discount_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_GST_Amount__c</fullName>
    <label>Discount GST Amount</label>
    <summarizedField>Invoice_Discount__c.GST_Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Discount__c.Invoice_Line_Item__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/InvoiceUtilityTest.cls
/**
 * @description       : 
 * @author            : Mark Alvin Tayag (mtayag@salesforce.com)
 * @group             : 
 * @last modified on  : 11-04-2020
 * @last modified by  : Mark Alvin Tayag (mtayag@salesforce.com)
 * Modifications Log 
 * Ver   Date         Author                                     Modification
 * 1.0   10-11-2020   Mark Alvin Tayag (mtayag@salesforce.com)   Initial Version
 * 1.1   2021-03-12   Poon Koon                                  Update test classes to include testing for RMIT Discount
 *                                                               and for early bird calculation to be based on Course Run Start Date
 * 1.2   2021-03-22   Poon Koon                                  Update test preparation methods to include new Credit Term field
**/
@IsTest
public with sharing class InvoiceUtilityTest {
 
    static void prepareDataForCourse(){
        Id b2cLearnerRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('B2C_Learner').getRecordTypeId();
        Account acct = new Account();
        acct.RecordTypeId = b2cLearnerRT;
        acct.FirstName = 'Test';
        acct.LastName = 'Account';
        acct.PersonEmail = 'testApexUser@sim.edu.sg';
        acct.Credit_Term_Days__c = 14;
        insert acct;
        acct = [SELECT Id, PersonContactId FROM Account];

        Id courseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Course').getRecordTypeId();
        Course__c course = TestDataFactory.createCourse(null);
        course.RecordTypeId = courseRT;
        insert course;

        Course_Run__c courseRun = TestDataFactory.createCourseRun();
        courseRun.Course__c = course.Id;
        courseRun.Start_Date__c = System.today()+2;
        courseRun.End_Date__c = System.today()+4;
        insert courseRun;

        //Create Course Registration from TestDataFactory
        Course_Registration__c reg = TestDataFactory.createCourseRegistration(courseRun.Id, acct.PersonContactId);
        insert reg;
    }
 
    static void prepareDataForCourseWithParent(){
        Id b2cLearnerRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('B2C_Learner').getRecordTypeId();
        Account acct = new Account();
        acct.RecordTypeId = b2cLearnerRT;
        acct.FirstName = 'Test';
        acct.LastName = 'Account';
        acct.PersonEmail = 'testApexUser@sim.edu.sg';
        acct.Credit_Term_Days__c = 14;
        insert acct;
        acct = [SELECT Id, PersonContactId FROM Account];

        Id courseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Course').getRecordTypeId();
        Course__c course = TestDataFactory.createCourse(null);
        course.RecordTypeId = courseRT;
        insert course;

        Course_Run__c courseRun = TestDataFactory.createCourseRun();
        courseRun.Course__c = course.Id;
        courseRun.Start_Date__c = System.today()+2;
        courseRun.End_Date__c = System.today()+4;
        insert courseRun;

        //Create Course Registration from TestDataFactory

        Course_Registration__c parentReg = TestDataFactory.createCourseRegistration(courseRun.Id, acct.PersonContactId);
        insert parentReg;

        Course_Registration__c reg = TestDataFactory.createCourseRegistration(courseRun.Id, acct.PersonContactId);
        reg.Parent_Registration__c = parentReg.Id;
        reg.Email_Address__c = 'testApexUser@sim.edu.sg';
        insert reg;

        Course_Registration__c reg2 = TestDataFactory.createCourseRegistration(courseRun.Id, acct.PersonContactId);
        reg2.Parent_Registration__c = parentReg.Id;
        reg2.Email_Address__c = 'testApexUser@sim.edu.sg';
        insert reg2;
    }

    static void prepareDataForFundedCourse(){
        Id b2cLearnerRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('B2C_Learner').getRecordTypeId();
        Account acct = new Account();
        acct.RecordTypeId = b2cLearnerRT;
        acct.FirstName = 'Test';
        acct.LastName = 'Account';
        acct.PersonEmail = 'testApexUser@sim.edu.sg';
        acct.Credit_Term_Days__c = 14;
        insert acct;
        acct = [SELECT Id, PersonContactId FROM Account];

        Id fundedSSGCourseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Funded_Course').getRecordTypeId();
        Course__c course = TestDataFactory.createCourse(null);
        course.RecordTypeId = fundedSSGCourseRT;
        insert course;

        Module__c module = TestDataFactory.createModule();
        insert module;

        Course_Module__c cm = new Course_Module__c();
        cm.Course__c = course.Id;
        cm.Module__c = module.Id;
        insert cm;

        Course_Run__c courseRun = TestDataFactory.createCourseRun();
        courseRun.Course__c = course.Id;
        courseRun.Start_Date__c = System.today()+2;
        courseRun.End_Date__c = System.today()+4;
        insert courseRun;

        //Create Course Registration from TestDataFactory
        Course_Registration__c reg = TestDataFactory.createCourseRegistration(courseRun.Id, acct.PersonContactId);
        insert reg;
    }
 
    static void prepareDataForFundedCourseWithParent(){
        Id b2cLearnerRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('B2C_Learner').getRecordTypeId();
        Account acct = new Account();
        acct.RecordTypeId = b2cLearnerRT;
        acct.FirstName = 'Test';
        acct.LastName = 'Account';
        acct.PersonEmail = 'testApexUser@sim.edu.sg';
        acct.Credit_Term_Days__c = 14;
        insert acct;
        acct = [SELECT Id, PersonContactId FROM Account];

        Id fundedSSGCourseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Funded_Course').getRecordTypeId();
        Course__c course = TestDataFactory.createCourse(null);
        course.RecordTypeId = fundedSSGCourseRT;
        insert course;

        Module__c module = TestDataFactory.createModule();
        insert module;

        Course_Module__c cm = new Course_Module__c();
        cm.Course__c = course.Id;
        cm.Module__c = module.Id;
        insert cm;

        Course_Run__c courseRun = TestDataFactory.createCourseRun();
        courseRun.Course__c = course.Id;
        courseRun.Start_Date__c = System.today()+2;
        courseRun.End_Date__c = System.today()+4;
        insert courseRun;

        //Create Course Registration from TestDataFactory

        Course_Registration__c parentReg = TestDataFactory.createCourseRegistration(courseRun.Id, acct.PersonContactId);
        insert parentReg;

        Course_Registration__c reg = TestDataFactory.createCourseRegistration(courseRun.Id, acct.PersonContactId);
        reg.Parent_Registration__c = parentReg.Id;
        reg.Email_Address__c = 'testApexUser@sim.edu.sg';
        insert reg;

        Course_Registration__c reg2 = TestDataFactory.createCourseRegistration(courseRun.Id, acct.PersonContactId);
        reg2.Parent_Registration__c = parentReg.Id;
        reg2.Email_Address__c = 'testApexUser@sim.edu.sg';
        insert reg2;
    }

    static void prepareDataForRMITCourse(){
        Id b2cLearnerRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('B2C_Learner').getRecordTypeId();
        Account acct = new Account();
        acct.RecordTypeId = b2cLearnerRT;
        acct.FirstName = 'Test';
        acct.LastName = 'Account';
        acct.PersonEmail = 'testApexUser@sim.edu.sg';
        acct.Credit_Term_Days__c = 14;
        insert acct;
        acct = [SELECT Id, PersonContactId FROM Account];

        Id courseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Course').getRecordTypeId();
        Course__c course = TestDataFactory.createCourse(null);
        course.RecordTypeId = courseRT;
        course.Provider__c = 'RMIT';
        insert course;

        Course_Run__c courseRun = TestDataFactory.createCourseRun();
        courseRun.Course__c = course.Id;
        courseRun.Start_Date__c = System.today()+2;
        courseRun.End_Date__c = System.today()+4;
        insert courseRun;

        //Create Course Registration from TestDataFactory
        Course_Registration__c reg = TestDataFactory.createCourseRegistration(courseRun.Id, acct.PersonContactId);
        reg.RMIT_Alumni__c = true;
        insert reg;
    }

    @IsTest
    static void createNonMemberInvoiceWOEarlyBird() {
        Id courseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Course').getRecordTypeId();
        prepareDataForCourse();

        Course__c course = [SELECT Non_Member_Fee__c, Non_Member_GST_Fee__c  FROM Course__c];

        Test.startTest();
        Course_Registration__c reg = [SELECT Id FROM Course_Registration__c];
        InvoiceUtility.generateInvoiceForRegistration(reg.Id);
        Test.stopTest();

        List<Invoice__c> invoice = [SELECT Id, Amount__c, GST_Amount__c FROM Invoice__c];
        System.assertEquals(1, invoice.size());
        List<Invoice_Line_Item__c> invoiceLineItems = [SELECT Id, Amount__c, GST_Amount__c FROM Invoice_Line_Item__c WHERE Invoice__c =: invoice[0].Id];
        System.assertEquals(1, invoiceLineItems.size());
        System.assertEquals(course.Non_Member_Fee__c, invoice[0].Amount__c);
        System.assertEquals(course.Non_Member_GST_Fee__c, invoice[0].GST_Amount__c);
    }

    @IsTest
    static void createNonMemberInvoiceWEarlyBirdPercentage() {        
        Id courseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Course').getRecordTypeId();
        prepareDataForCourse();

        Course__c course = [SELECT Non_Member_Fee__c, Non_Member_GST_Fee__c  FROM Course__c];

        Id earlyBirdRT = Schema.SObjectType.Discount__c.getRecordTypeInfosByDeveloperName().get('Early_Bird').getRecordTypeId();
        Discount__c discount = TestDataFactory.createDiscount();
        discount.Percentage__c = true;
        discount.Amount__c = 10;
        discount.GST_Amount__c = 7;
        discount.RecordTypeId = earlyBirdRT;
        discount.No_of_Days__c = 1;
        insert discount;

        Course_Discount__c cdisc = new Course_Discount__c();
        cdisc.Course__c = course.Id;
        cdisc.Discount__c = discount.Id;
        insert cdisc;
        

        Test.startTest();
        Course_Registration__c reg = [SELECT Id FROM Course_Registration__c];
        InvoiceUtility.generateInvoiceForRegistration(reg.Id);
        Test.stopTest();

        List<Invoice__c> invoice = [SELECT Id, Amount__c, GST_Amount__c, Discount_Amount__c, Discount_GST_Amount__c FROM Invoice__c];
        System.assertEquals(1, invoice.size());
        System.assertEquals(course.Non_Member_Fee__c, invoice[0].Amount__c);
        System.assertEquals(course.Non_Member_GST_Fee__c, invoice[0].GST_Amount__c);
        System.assertEquals(course.Non_Member_Fee__c * (discount.Amount__c / 100), invoice[0].Discount_Amount__c);
        System.assertEquals((course.Non_Member_Fee__c * (discount.Amount__c / 100)) * (discount.GST_Amount__c / 100), invoice[0].Discount_GST_Amount__c);
    }

    @IsTest
    static void createNonMemberInvoiceWEarlyBirdAmount() {        
        Id courseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Course').getRecordTypeId();
        prepareDataForCourse();

        Course__c course = [SELECT Non_Member_Fee__c, Non_Member_GST_Fee__c  FROM Course__c];

        Id earlyBirdRT = Schema.SObjectType.Discount__c.getRecordTypeInfosByDeveloperName().get('Early_Bird').getRecordTypeId();
        Discount__c discount = TestDataFactory.createDiscount();
        discount.Percentage__c = false;
        discount.Amount__c = 100;
        discount.GST_Amount__c = 7;
        discount.RecordTypeId = earlyBirdRT;
        discount.No_of_Days__c = 1;
        insert discount;

        Course_Discount__c cdisc = new Course_Discount__c();
        cdisc.Course__c = course.Id;
        cdisc.Discount__c = discount.Id;
        insert cdisc;
        

        Test.startTest();
        Course_Registration__c reg = [SELECT Id FROM Course_Registration__c];
        InvoiceUtility.generateInvoiceForRegistration(reg.Id);
        Test.stopTest();

        List<Invoice__c> invoice = [SELECT Id, Amount__c, GST_Amount__c, Discount_Amount__c, Discount_GST_Amount__c FROM Invoice__c];
        System.assertEquals(1, invoice.size());
        System.assertEquals(course.Non_Member_Fee__c, invoice[0].Amount__c);
        System.assertEquals(course.Non_Member_GST_Fee__c, invoice[0].GST_Amount__c);
        System.assertEquals(discount.Amount__c, invoice[0].Discount_Amount__c);
        System.assertEquals(discount.GST_Amount__c, invoice[0].Discount_GST_Amount__c);
    }

    @IsTest
    static void createNonMemberInvoiceWExpiredEarlyBirdAmount() {        
        Id courseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Course').getRecordTypeId();
        prepareDataForCourse();

        Course__c course = [SELECT Non_Member_Fee__c, Non_Member_GST_Fee__c  FROM Course__c];
        
        Id earlyBirdRT = Schema.SObjectType.Discount__c.getRecordTypeInfosByDeveloperName().get('Early_Bird').getRecordTypeId();
        Discount__c discount = TestDataFactory.createDiscount();
        discount.Percentage__c = false;
        discount.Amount__c = 100;
        discount.GST_Amount__c = 7;
        discount.RecordTypeId = earlyBirdRT;
        discount.No_of_Days__c = 100;
        insert discount;

        Course_Discount__c cdisc = new Course_Discount__c();
        cdisc.Course__c = course.Id;
        cdisc.Discount__c = discount.Id;
        insert cdisc;
        

        Test.startTest();
        Course_Registration__c reg = [SELECT Id FROM Course_Registration__c];
        InvoiceUtility.generateInvoiceForRegistration(reg.Id);
        Test.stopTest();

        List<Invoice__c> invoice = [SELECT Id, Amount__c, GST_Amount__c, Discount_Amount__c, Discount_GST_Amount__c FROM Invoice__c];
        System.assertEquals(1, invoice.size());
        System.assertEquals(course.Non_Member_Fee__c, invoice[0].Amount__c);
        System.assertEquals(course.Non_Member_GST_Fee__c, invoice[0].GST_Amount__c);
        System.assertEquals(0, invoice[0].Discount_Amount__c);
        System.assertEquals(0, invoice[0].Discount_GST_Amount__c);
    }

    //With Parent
    @IsTest
    static void createChildNonMemberInvoiceWOEarlyBird() {
        Id courseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Course').getRecordTypeId();
        prepareDataForCourseWithParent();

        Course__c course = [SELECT Non_Member_Fee__c, Non_Member_GST_Fee__c  FROM Course__c];
        List<Course_Registration__c> childCourseRegs = [SELECT Id FROM Course_Registration__c WHERE Parent_Registration__c != null];

        Test.startTest();
        Course_Registration__c reg = [SELECT Id FROM Course_Registration__c WHERE Parent_Registration__c = null];
        InvoiceUtility.generateInvoiceForRegistration(reg.Id);
        Test.stopTest();

        List<Invoice__c> invoice = [SELECT Id, Amount__c, GST_Amount__c FROM Invoice__c];
        System.assertEquals(1, invoice.size());
        List<Invoice_Line_Item__c> invoiceLineItems = [SELECT Id, Amount__c, GST_Amount__c FROM Invoice_Line_Item__c WHERE Invoice__c =: invoice[0].Id];
        System.assertEquals(childCourseRegs.size(), invoiceLineItems.size());
        System.assertEquals(course.Non_Member_Fee__c * childCourseRegs.size(), invoice[0].Amount__c);
        System.assertEquals(course.Non_Member_GST_Fee__c * childCourseRegs.size(), invoice[0].GST_Amount__c);
    }

    @IsTest
    static void createChildNonMemberInvoiceWEarlyBirdPercentage() {
        Id courseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Course').getRecordTypeId();
        prepareDataForCourseWithParent();

        Course__c course = [SELECT Non_Member_Fee__c, Non_Member_GST_Fee__c  FROM Course__c];
        List<Course_Registration__c> childCourseRegs = [SELECT Id FROM Course_Registration__c WHERE Parent_Registration__c != null];

        Id earlyBirdRT = Schema.SObjectType.Discount__c.getRecordTypeInfosByDeveloperName().get('Early_Bird').getRecordTypeId();
        Discount__c discount = TestDataFactory.createDiscount();
        discount.Percentage__c = true;
        discount.Amount__c = 10;
        discount.GST_Amount__c = 7;
        discount.RecordTypeId = earlyBirdRT;
        discount.No_of_Days__c = 1;
        insert discount;

        Course_Discount__c cdisc = new Course_Discount__c();
        cdisc.Course__c = course.Id;
        cdisc.Discount__c = discount.Id;
        insert cdisc;

        Test.startTest();
        Course_Registration__c reg = [SELECT Id FROM Course_Registration__c WHERE Parent_Registration__c = null];
        InvoiceUtility.generateInvoiceForRegistration(reg.Id);
        Test.stopTest();

        List<Invoice__c> invoice = [SELECT Id, Amount__c, GST_Amount__c, Discount_Amount__c, Discount_GST_Amount__c FROM Invoice__c];
        System.assertEquals(1, invoice.size());
        List<Invoice_Line_Item__c> invoiceLineItems = [SELECT Id, Amount__c, GST_Amount__c FROM Invoice_Line_Item__c WHERE Invoice__c =: invoice[0].Id];
        System.assertEquals(childCourseRegs.size(), invoiceLineItems.size());
        System.assertEquals(course.Non_Member_Fee__c * childCourseRegs.size(), invoice[0].Amount__c);
        System.assertEquals(course.Non_Member_GST_Fee__c * childCourseRegs.size(), invoice[0].GST_Amount__c);
        List<Invoice_Discount__c> invoiceDiscounts = [SELECT Amount__c, GST_Amount__c, Invoice_Line_Item__c, Id FROM Invoice_Discount__c];
        System.assertEquals(2, invoiceDiscounts.size());
        System.assertEquals(course.Non_Member_Fee__c * (discount.Amount__c / 100) * childCourseRegs.size(), invoice[0].Discount_Amount__c);
        System.assertEquals((course.Non_Member_Fee__c * (discount.Amount__c / 100)) * (discount.GST_Amount__c / 100) * childCourseRegs.size(), invoice[0].Discount_GST_Amount__c);
    }

    @IsTest
    static void createChildNonMemberInvoiceWEarlyBirdAmount() {
        Id courseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Course').getRecordTypeId();
        prepareDataForCourseWithParent();

        Course__c course = [SELECT Non_Member_Fee__c, Non_Member_GST_Fee__c  FROM Course__c];
        List<Course_Registration__c> childCourseRegs = [SELECT Id FROM Course_Registration__c WHERE Parent_Registration__c != null];

        Id earlyBirdRT = Schema.SObjectType.Discount__c.getRecordTypeInfosByDeveloperName().get('Early_Bird').getRecordTypeId();
        Discount__c discount = TestDataFactory.createDiscount();
        discount.Percentage__c = false;
        discount.Amount__c = 100;
        discount.GST_Amount__c = 7;
        discount.RecordTypeId = earlyBirdRT;
        discount.No_of_Days__c = 1;
        insert discount;

        Course_Discount__c cdisc = new Course_Discount__c();
        cdisc.Course__c = course.Id;
        cdisc.Discount__c = discount.Id;
        insert cdisc;

        Test.startTest();
        Course_Registration__c reg = [SELECT Id FROM Course_Registration__c WHERE Parent_Registration__c = null];
        InvoiceUtility.generateInvoiceForRegistration(reg.Id);
        Test.stopTest();

        List<Invoice__c> invoice = [SELECT Id, Amount__c, GST_Amount__c, Discount_Amount__c, Discount_GST_Amount__c FROM Invoice__c];
        System.assertEquals(1, invoice.size());
        List<Invoice_Line_Item__c> invoiceLineItems = [SELECT Id, Amount__c, GST_Amount__c FROM Invoice_Line_Item__c WHERE Invoice__c =: invoice[0].Id];
        System.assertEquals(childCourseRegs.size(), invoiceLineItems.size());
        System.assertEquals(course.Non_Member_Fee__c * childCourseRegs.size(), invoice[0].Amount__c);
        System.assertEquals(course.Non_Member_GST_Fee__c * childCourseRegs.size(), invoice[0].GST_Amount__c);
        List<Invoice_Discount__c> invoiceDiscounts = [SELECT Amount__c, GST_Amount__c, Invoice_Line_Item__c, Id FROM Invoice_Discount__c];
        System.assertEquals(2, invoiceDiscounts.size());
        System.assertEquals(discount.Amount__c * childCourseRegs.size(), invoice[0].Discount_Amount__c);
        System.assertEquals(discount.GST_Amount__c * childCourseRegs.size(), invoice[0].Discount_GST_Amount__c);
    }

    @IsTest
    static void createChildNonMemberInvoiceWExpiredEarlyBirdAmount() {
        Id courseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Course').getRecordTypeId();
        prepareDataForCourseWithParent();

        Course__c course = [SELECT Non_Member_Fee__c, Non_Member_GST_Fee__c  FROM Course__c];
        List<Course_Registration__c> childCourseRegs = [SELECT Id FROM Course_Registration__c WHERE Parent_Registration__c != null];

        Id earlyBirdRT = Schema.SObjectType.Discount__c.getRecordTypeInfosByDeveloperName().get('Early_Bird').getRecordTypeId();
        Discount__c discount = TestDataFactory.createDiscount();
        discount.Percentage__c = false;
        discount.Amount__c = 100;
        discount.GST_Amount__c = 7;
        discount.RecordTypeId = earlyBirdRT;
        discount.No_of_Days__c = 100;
        insert discount;

        Course_Discount__c cdisc = new Course_Discount__c();
        cdisc.Course__c = course.Id;
        cdisc.Discount__c = discount.Id;
        insert cdisc;

        Test.startTest();
        Course_Registration__c reg = [SELECT Id FROM Course_Registration__c WHERE Parent_Registration__c = null];
        InvoiceUtility.generateInvoiceForRegistration(reg.Id);
        Test.stopTest();

        List<Invoice__c> invoice = [SELECT Id, Amount__c, GST_Amount__c, Discount_Amount__c, Discount_GST_Amount__c FROM Invoice__c];
        System.assertEquals(1, invoice.size());
        List<Invoice_Line_Item__c> invoiceLineItems = [SELECT Id, Amount__c, GST_Amount__c FROM Invoice_Line_Item__c WHERE Invoice__c =: invoice[0].Id];
        System.assertEquals(childCourseRegs.size(), invoiceLineItems.size());
        System.assertEquals(course.Non_Member_Fee__c * childCourseRegs.size(), invoice[0].Amount__c);
        System.assertEquals(course.Non_Member_GST_Fee__c * childCourseRegs.size(), invoice[0].GST_Amount__c);
        List<Invoice_Discount__c> invoiceDiscounts = [SELECT Amount__c, GST_Amount__c, Invoice_Line_Item__c, Id FROM Invoice_Discount__c];
        System.assertEquals(0, invoiceDiscounts.size());
        System.assertEquals(0, invoice[0].Discount_Amount__c);
        System.assertEquals(0, invoice[0].Discount_GST_Amount__c);
    }

    //---- FUNDED TEST CASES ----//

    @IsTest
    static void createFundedInvoiceWEarlyBirdPercentage(){
        Id courseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Funded_Course').getRecordTypeId();
        prepareDataForFundedCourse();

        Course__c course = [SELECT Full_Fee__c, Full_Fee_GST_Amount__c  FROM Course__c];

        Id earlyBirdRT = Schema.SObjectType.Discount__c.getRecordTypeInfosByDeveloperName().get('Early_Bird').getRecordTypeId();
        Discount__c discount = TestDataFactory.createDiscount();
        discount.Percentage__c = true;
        discount.Amount__c = 10;
        discount.GST_Amount__c = 7;
        discount.RecordTypeId = earlyBirdRT;
        discount.No_of_Days__c = 1;
        insert discount;

        Course_Discount__c cdisc = new Course_Discount__c();
        cdisc.Course__c = course.Id;
        cdisc.Discount__c = discount.Id;
        insert cdisc;
        

        Test.startTest();
        Course_Registration__c reg = [SELECT Id FROM Course_Registration__c];
        InvoiceUtility.generateInvoiceForRegistration(reg.Id);
        Test.stopTest();

        List<Invoice__c> invoice = [SELECT Id, Amount__c, GST_Amount__c, Discount_Amount__c, Discount_GST_Amount__c FROM Invoice__c];
        System.assertEquals(1, invoice.size());
        System.assertEquals(course.Full_Fee__c, invoice[0].Amount__c);
        System.assertEquals(course.Full_Fee_GST_Amount__c, invoice[0].GST_Amount__c);
        System.assertEquals(course.Full_Fee__c * (discount.Amount__c / 100), invoice[0].Discount_Amount__c);
        System.assertEquals((course.Full_Fee__c * (discount.Amount__c / 100)) * (discount.GST_Amount__c / 100), invoice[0].Discount_GST_Amount__c);
    }

    @IsTest
    static void createFundedInvoiceWEarlyBirdAmount(){
        Id courseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Funded_Course').getRecordTypeId();
        prepareDataForFundedCourse();

        Course__c course = [SELECT Full_Fee__c, Full_Fee_GST_Amount__c  FROM Course__c];

        Id earlyBirdRT = Schema.SObjectType.Discount__c.getRecordTypeInfosByDeveloperName().get('Early_Bird').getRecordTypeId();
        Discount__c discount = TestDataFactory.createDiscount();
        discount.Percentage__c = false;
        discount.Amount__c = 100;
        discount.GST_Amount__c = 7;
        discount.RecordTypeId = earlyBirdRT;
        discount.No_of_Days__c = 1;
        insert discount;

        Course_Discount__c cdisc = new Course_Discount__c();
        cdisc.Course__c = course.Id;
        cdisc.Discount__c = discount.Id;
        insert cdisc;
        

        Test.startTest();
        Course_Registration__c reg = [SELECT Id FROM Course_Registration__c];
        InvoiceUtility.generateInvoiceForRegistration(reg.Id);
        Test.stopTest();

        List<Invoice__c> invoice = [SELECT Id, Amount__c, GST_Amount__c, Discount_Amount__c, Discount_GST_Amount__c FROM Invoice__c];
        System.assertEquals(1, invoice.size());
        System.assertEquals(course.Full_Fee__c, invoice[0].Amount__c);
        System.assertEquals(course.Full_Fee_GST_Amount__c, invoice[0].GST_Amount__c);
        System.assertEquals(discount.Amount__c, invoice[0].Discount_Amount__c);
        System.assertEquals(discount.GST_Amount__c, invoice[0].Discount_GST_Amount__c);
    }

    @IsTest
    static void createFundedInvoiceWExpiredEarlyBirdAmount(){
        Id courseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Funded_Course').getRecordTypeId();
        prepareDataForFundedCourse();

        Course__c course = [SELECT Full_Fee__c, Full_Fee_GST_Amount__c  FROM Course__c];

        Id earlyBirdRT = Schema.SObjectType.Discount__c.getRecordTypeInfosByDeveloperName().get('Early_Bird').getRecordTypeId();
        Discount__c discount = TestDataFactory.createDiscount();
        discount.Percentage__c = false;
        discount.Amount__c = 100;
        discount.GST_Amount__c = 7;
        discount.RecordTypeId = earlyBirdRT;
        discount.No_of_Days__c = 100;
        insert discount;

        Course_Discount__c cdisc = new Course_Discount__c();
        cdisc.Course__c = course.Id;
        cdisc.Discount__c = discount.Id;
        insert cdisc;
        

        Test.startTest();
        Course_Registration__c reg = [SELECT Id FROM Course_Registration__c];
        InvoiceUtility.generateInvoiceForRegistration(reg.Id);
        Test.stopTest();

        List<Invoice__c> invoice = [SELECT Id, Amount__c, GST_Amount__c, Discount_Amount__c, Discount_GST_Amount__c FROM Invoice__c];
        System.assertEquals(1, invoice.size());
        System.assertEquals(course.Full_Fee__c, invoice[0].Amount__c);
        System.assertEquals(course.Full_Fee_GST_Amount__c, invoice[0].GST_Amount__c);
        System.assertEquals(0, invoice[0].Discount_Amount__c);
        System.assertEquals(0, invoice[0].Discount_GST_Amount__c);
    }

    @IsTest
    static void createFundedInvoiceWOEarlyBird(){
        Id courseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Funded_Course').getRecordTypeId();
        prepareDataForFundedCourse();

        Course__c course = [SELECT Full_Fee__c, Full_Fee_GST_Amount__c  FROM Course__c];

        Test.startTest();
        Course_Registration__c reg = [SELECT Id FROM Course_Registration__c];
        InvoiceUtility.generateInvoiceForRegistration(reg.Id);
        Test.stopTest();

        List<Invoice__c> invoice = [SELECT Id, Amount__c, GST_Amount__c FROM Invoice__c];
        System.assertEquals(1, invoice.size());
        List<Invoice_Line_Item__c> invoiceLineItems = [SELECT Id, Amount__c, GST_Amount__c FROM Invoice_Line_Item__c WHERE Invoice__c =: invoice[0].Id];
        System.assertEquals(1, invoiceLineItems.size());
        System.assertEquals(course.Full_Fee__c, invoice[0].Amount__c);
        System.assertEquals(course.Full_Fee_GST_Amount__c, invoice[0].GST_Amount__c);
    }


    //With Parent

    @IsTest
    static void createChildFundedInvoiceWEarlyBirdPercentage(){
        Id courseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Funded_Course').getRecordTypeId();
        prepareDataForFundedCourseWithParent();

        Course__c course = [SELECT Full_Fee__c, Full_Fee_GST_Amount__c  FROM Course__c];
        List<Course_Registration__c> childCourseRegs = [SELECT Id FROM Course_Registration__c WHERE Parent_Registration__c != null];

        Id earlyBirdRT = Schema.SObjectType.Discount__c.getRecordTypeInfosByDeveloperName().get('Early_Bird').getRecordTypeId();
        Discount__c discount = TestDataFactory.createDiscount();
        discount.Percentage__c = true;
        discount.Amount__c = 10;
        discount.GST_Amount__c = 7;
        discount.RecordTypeId = earlyBirdRT;
        discount.No_of_Days__c = 1;
        insert discount;

        Course_Discount__c cdisc = new Course_Discount__c();
        cdisc.Course__c = course.Id;
        cdisc.Discount__c = discount.Id;
        insert cdisc;

        Test.startTest();
        Course_Registration__c reg = [SELECT Id FROM Course_Registration__c WHERE Parent_Registration__c = null];
        InvoiceUtility.generateInvoiceForRegistration(reg.Id);
        Test.stopTest();

        List<Invoice__c> invoice = [SELECT Id, Amount__c, GST_Amount__c, Discount_Amount__c, Discount_GST_Amount__c FROM Invoice__c];
        System.assertEquals(1, invoice.size());
        List<Invoice_Line_Item__c> invoiceLineItems = [SELECT Id, Amount__c, GST_Amount__c FROM Invoice_Line_Item__c WHERE Invoice__c =: invoice[0].Id];
        System.assertEquals(childCourseRegs.size(), invoiceLineItems.size());
        System.assertEquals(course.Full_Fee__c * childCourseRegs.size(), invoice[0].Amount__c);
        System.assertEquals(course.Full_Fee_GST_Amount__c * childCourseRegs.size(), invoice[0].GST_Amount__c);
        List<Invoice_Discount__c> invoiceDiscounts = [SELECT Amount__c, GST_Amount__c, Invoice_Line_Item__c, Id FROM Invoice_Discount__c];
        System.assertEquals(2, invoiceDiscounts.size());
        System.assertEquals(course.Full_Fee__c * (discount.Amount__c / 100) * childCourseRegs.size(), invoice[0].Discount_Amount__c);
        System.assertEquals((course.Full_Fee__c * (discount.Amount__c / 100)) * (discount.GST_Amount__c / 100) * childCourseRegs.size(), invoice[0].Discount_GST_Amount__c);
    }

    @IsTest
    static void createChildFundedInvoiceWEarlyBirdAmount(){
        Id courseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Funded_Course').getRecordTypeId();
        prepareDataForFundedCourseWithParent();

        Course__c course = [SELECT Full_Fee__c, Full_Fee_GST_Amount__c  FROM Course__c];
        List<Course_Registration__c> childCourseRegs = [SELECT Id FROM Course_Registration__c WHERE Parent_Registration__c != null];

        Id earlyBirdRT = Schema.SObjectType.Discount__c.getRecordTypeInfosByDeveloperName().get('Early_Bird').getRecordTypeId();
        Discount__c discount = TestDataFactory.createDiscount();
        discount.Percentage__c = false;
        discount.Amount__c = 100;
        discount.GST_Amount__c = 7;
        discount.RecordTypeId = earlyBirdRT;
        discount.No_of_Days__c = 1;
        insert discount;

        Course_Discount__c cdisc = new Course_Discount__c();
        cdisc.Course__c = course.Id;
        cdisc.Discount__c = discount.Id;
        insert cdisc;

        Test.startTest();
        Course_Registration__c reg = [SELECT Id FROM Course_Registration__c WHERE Parent_Registration__c = null];
        InvoiceUtility.generateInvoiceForRegistration(reg.Id);
        Test.stopTest();

        List<Invoice__c> invoice = [SELECT Id, Amount__c, GST_Amount__c, Discount_Amount__c, Discount_GST_Amount__c FROM Invoice__c];
        System.assertEquals(1, invoice.size());
        List<Invoice_Line_Item__c> invoiceLineItems = [SELECT Id, Amount__c, GST_Amount__c FROM Invoice_Line_Item__c WHERE Invoice__c =: invoice[0].Id];
        System.assertEquals(childCourseRegs.size(), invoiceLineItems.size());
        System.assertEquals(course.Full_Fee__c * childCourseRegs.size(), invoice[0].Amount__c);
        System.assertEquals(course.Full_Fee_GST_Amount__c * childCourseRegs.size(), invoice[0].GST_Amount__c);
        List<Invoice_Discount__c> invoiceDiscounts = [SELECT Amount__c, GST_Amount__c, Invoice_Line_Item__c, Id FROM Invoice_Discount__c];
        System.assertEquals(2, invoiceDiscounts.size());
        System.assertEquals(discount.Amount__c * childCourseRegs.size(), invoice[0].Discount_Amount__c);
        System.assertEquals(discount.GST_Amount__c * childCourseRegs.size(), invoice[0].Discount_GST_Amount__c);
    }

    @IsTest
    static void createChildFundedInvoiceWExpiredEarlyBirdAmount(){
        Id courseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Funded_Course').getRecordTypeId();
        prepareDataForFundedCourseWithParent();

        Course__c course = [SELECT Full_Fee__c, Full_Fee_GST_Amount__c  FROM Course__c];
        List<Course_Registration__c> childCourseRegs = [SELECT Id FROM Course_Registration__c WHERE Parent_Registration__c != null];

        Id earlyBirdRT = Schema.SObjectType.Discount__c.getRecordTypeInfosByDeveloperName().get('Early_Bird').getRecordTypeId();
        Discount__c discount = TestDataFactory.createDiscount();
        discount.Percentage__c = false;
        discount.Amount__c = 100;
        discount.GST_Amount__c = 7;
        discount.RecordTypeId = earlyBirdRT;
        discount.No_of_Days__c = 100;
        insert discount;

        Course_Discount__c cdisc = new Course_Discount__c();
        cdisc.Course__c = course.Id;
        cdisc.Discount__c = discount.Id;
        insert cdisc;

        Test.startTest();
        Course_Registration__c reg = [SELECT Id FROM Course_Registration__c WHERE Parent_Registration__c = null];
        InvoiceUtility.generateInvoiceForRegistration(reg.Id);
        Test.stopTest();

        List<Invoice__c> invoice = [SELECT Id, Amount__c, GST_Amount__c, Discount_Amount__c, Discount_GST_Amount__c FROM Invoice__c];
        System.assertEquals(1, invoice.size());
        List<Invoice_Line_Item__c> invoiceLineItems = [SELECT Id, Amount__c, GST_Amount__c FROM Invoice_Line_Item__c WHERE Invoice__c =: invoice[0].Id];
        System.assertEquals(childCourseRegs.size(), invoiceLineItems.size());
        System.assertEquals(course.Full_Fee__c * childCourseRegs.size(), invoice[0].Amount__c);
        System.assertEquals(course.Full_Fee_GST_Amount__c * childCourseRegs.size(), invoice[0].GST_Amount__c);
        List<Invoice_Discount__c> invoiceDiscounts = [SELECT Amount__c, GST_Amount__c, Invoice_Line_Item__c, Id FROM Invoice_Discount__c];
        System.assertEquals(0, invoiceDiscounts.size());
        System.assertEquals(0, invoice[0].Discount_Amount__c);
        System.assertEquals(0, invoice[0].Discount_GST_Amount__c);
    }

    @IsTest
    static void createChildFundedInvoiceWOEarlyBird(){
        Id courseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Funded_Course').getRecordTypeId();
        prepareDataForFundedCourseWithParent();

        Course__c course = [SELECT Full_Fee__c, Full_Fee_GST_Amount__c  FROM Course__c];
        List<Course_Registration__c> childCourseRegs = [SELECT Id FROM Course_Registration__c WHERE Parent_Registration__c != null];

        Test.startTest();
        Course_Registration__c reg = [SELECT Id FROM Course_Registration__c WHERE Parent_Registration__c = null];
        InvoiceUtility.generateInvoiceForRegistration(reg.Id);
        Test.stopTest();

        List<Invoice__c> invoice = [SELECT Id, Amount__c, GST_Amount__c, Discount_Amount__c, Discount_GST_Amount__c FROM Invoice__c];
        System.assertEquals(1, invoice.size());
        List<Invoice_Line_Item__c> invoiceLineItems = [SELECT Id, Amount__c, GST_Amount__c FROM Invoice_Line_Item__c WHERE Invoice__c =: invoice[0].Id];
        System.assertEquals(childCourseRegs.size(), invoiceLineItems.size());
        System.assertEquals(course.Full_Fee__c * childCourseRegs.size(), invoice[0].Amount__c);
        System.assertEquals(course.Full_Fee_GST_Amount__c * childCourseRegs.size(), invoice[0].GST_Amount__c);
        List<Invoice_Discount__c> invoiceDiscounts = [SELECT Amount__c, GST_Amount__c, Invoice_Line_Item__c, Id FROM Invoice_Discount__c];
        System.assertEquals(0, invoiceDiscounts.size());
        System.assertEquals(0, invoice[0].Discount_Amount__c);
        System.assertEquals(0, invoice[0].Discount_GST_Amount__c);
    }

    @IsTest
    static void createRMITInvoiceWRMITPercentage() {        
        Id courseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Course').getRecordTypeId();
        prepareDataForRMITCourse();

        Course__c course = [SELECT Non_Member_Fee__c, Non_Member_GST_Fee__c  FROM Course__c];

        Id promotionRT = Schema.SObjectType.Discount__c.getRecordTypeInfosByDeveloperName().get('Promotion').getRecordTypeId();
        Discount__c discount = TestDataFactory.createDiscount();
        discount.Percentage__c = true;
        discount.Amount__c = 15;
        discount.GST_Amount__c = 7;
        discount.RecordTypeId = promotionRT;
        discount.No_of_Days__c = 0;
        discount.Name = 'RMIT Alumni/Student Discount';
        discount.Description__c = 'RMIT Alumni/Student Discount';
        insert discount;

        Course_Discount__c cdisc = new Course_Discount__c();
        cdisc.Course__c = course.Id;
        cdisc.Discount__c = discount.Id;
        insert cdisc;
        

        Test.startTest();
        Course_Registration__c reg = [SELECT Id FROM Course_Registration__c];
        InvoiceUtility.generateInvoiceForRegistration(reg.Id);
        Test.stopTest();

        List<Invoice__c> invoice = [SELECT Id, Amount__c, GST_Amount__c, Discount_Amount__c, Discount_GST_Amount__c FROM Invoice__c];
        System.assertEquals(1, invoice.size());
        System.assertEquals(course.Non_Member_Fee__c, invoice[0].Amount__c);
        System.assertEquals(course.Non_Member_GST_Fee__c, invoice[0].GST_Amount__c);
        System.assertEquals(course.Non_Member_Fee__c * (discount.Amount__c / 100), invoice[0].Discount_Amount__c);
        System.assertEquals((course.Non_Member_Fee__c * (discount.Amount__c / 100)) * (discount.GST_Amount__c / 100), invoice[0].Discount_GST_Amount__c);
    }
}