force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <displayFormat>Course-{00000}</displayFormat>
        <label>Course Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Baseline_Grant_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Grant_GST_Amount__c</fullName>
    <label>Baseline Grant GST Amount</label>
    <summarizedField>Course_Module__c.Baseline_Grant_GST_Amount__c</summarizedField>
    <summaryForeignKey>Course_Module__c.Course__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Full_Fee__c.field-meta.xml
<CustomField>
    <fullName>Full_Fee__c</fullName>
    <label>Full Fee</label>
    <summarizedField>Course_Module__c.Full_Fee__c</summarizedField>
    <summaryForeignKey>Course_Module__c.Course__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Full_Fee_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Full_Fee_GST_Amount__c</fullName>
    <label>Full Fee GST Amount</label>
    <summarizedField>Course_Module__c.Full_Fee_GST_Amount__c</summarizedField>
    <summaryForeignKey>Course_Module__c.Course__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Mid_Career_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Mid_Career_GST_Amount__c</fullName>
    <label>Mid-Career GST Amount</label>
    <summarizedField>Course_Module__c.Mid_Career_GST_Amount__c</summarizedField>
    <summaryForeignKey>Course_Module__c.Course__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Non_SME_Grant_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Non_SME_Grant_GST_Amount__c</fullName>
    <label>Non-SME Grant GST Amount</label>
    <summarizedField>Course_Module__c.Non_SME_Grant_GST_Amount__c</summarizedField>
    <summaryForeignKey>Course_Module__c.Course__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/SME_Grant_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>SME_Grant_GST_Amount__c</fullName>
    <label>SME Grant GST Amount</label>
    <summarizedField>Course_Module__c.SME_Grant_GST_Amount__c</summarizedField>
    <summaryForeignKey>Course_Module__c.Course__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Workfare_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Workfare_GST_Amount__c</fullName>
    <label>Workfare GST Amount</label>
    <summarizedField>Course_Module__c.Workfare_GST_Amount__c</summarizedField>
    <summaryForeignKey>Course_Module__c.Course__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course__c/recordTypes/Course.recordType-meta.xml
<RecordType>
    <fullName>Course</fullName>
    <active>true</active>
    <description>Public Courses /Courses without SSG Modules/Courses with Skill future credit</description>
    <label>Course</label>
</RecordType>

force-app/main/default/objects/Course_Module__c/Course_Module__c.object-meta.xml
<CustomObject>
    <label>Course Module</label>
    <nameField>
        <displayFormat>CMOD-{0000}</displayFormat>
        <label>Course Module Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Module__c/fields/Baseline_Grant_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Grant_GST_Amount__c</fullName>
    <label>Baseline Grant GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Modules</relationshipLabel>
    <relationshipName>Course_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/Full_Fee__c.field-meta.xml
<CustomField>
    <fullName>Full_Fee__c</fullName>
    <label>Full Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/Full_Fee_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Full_Fee_GST_Amount__c</fullName>
    <label>Full Fee GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/Mid_Career_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Mid_Career_GST_Amount__c</fullName>
    <label>Mid-Career GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Course Modules</relationshipLabel>
    <relationshipName>Course_Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/Non_SME_Grant_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Non_SME_Grant_GST_Amount__c</fullName>
    <label>Non-SME Grant GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/SME_Grant_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>SME_Grant_GST_Amount__c</fullName>
    <label>SME Grant GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/Workfare_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Workfare_GST_Amount__c</fullName>
    <label>IBF GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/fields/Baseline_Grant_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Grant_GST_Amount__c</fullName>
    <label>Baseline Grant GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Full_Fee__c.field-meta.xml
<CustomField>
    <fullName>Full_Fee__c</fullName>
    <label>Full Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Full_Fee_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Full_Fee_GST_Amount__c</fullName>
    <label>Full Fee GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Mid_Career_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Mid_Career_GST_Amount__c</fullName>
    <label>Mid-Career GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Non_SME_Grant_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Non_SME_Grant_GST_Amount__c</fullName>
    <label>Non-SME Grant GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/SME_Grant_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>SME_Grant_GST_Amount__c</fullName>
    <label>SME Grant GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Workfare_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Workfare_GST_Amount__c</fullName>
    <label>Workfare GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ModuleTriggerHandlerTest.cls
@IsTest
public without sharing class ModuleTriggerHandlerTest {
    @IsTest
    static void calculateGST(){
        
        Module__c module = TestDataFactory.createModule();

        module.Full_Fee_GST_Amount__c = 0;
        module.SME_Grant_GST_Amount__c = 0;
        module.Non_SME_Grant_GST_Amount__c = 0;
        module.Baseline_Grant_GST_Amount__c = 0;
        module.Workfare_GST_Amount__c = 0;
        module.Mid_Career_GST_Amount__c = 0;
        Test.startTest();
        insert module;
        Test.stopTest();
        
        Module__c moduleAfter = [SELECT Full_Fee_GST_Amount__c,
                                SME_Grant_GST_Amount__c,
                                Non_SME_Grant_GST_Amount__c,
                                Baseline_Grant_GST_Amount__c,
                                Workfare_GST_Amount__c,
                                Mid_Career_GST_Amount__c
                                FROM Module__c
                                WHERE Id =: module.Id];

        Decimal fullFeeGSTAmount = 70;
        Decimal smeGrantGSTAmount = 35;
        Decimal nonSMEGrantGSTAmount = 49;
        Decimal baselineGrantGSTAmount = 56;
        Decimal workfareGSTAmount = 56;
        Decimal midCareerGSTAmount = 49;

        System.assertEquals(fullFeeGSTAmount, moduleAfter.Full_Fee_GST_Amount__c);
        /*System.assertEquals(smeGrantGSTAmount, moduleAfter.SME_Grant_GST_Amount__c);
        System.assertEquals(nonSMEGrantGSTAmount, moduleAfter.Non_SME_Grant_GST_Amount__c);
        System.assertEquals(baselineGrantGSTAmount, moduleAfter.Baseline_Grant_GST_Amount__c);
        System.assertEquals(workfareGSTAmount, moduleAfter.Workfare_GST_Amount__c);
        System.assertEquals(midCareerGSTAmount, moduleAfter.Mid_Career_GST_Amount__c);*/
    }

    @IsTest
    static void updateCourseModules(){
        Course__c course = TestDataFactory.createCourse(null);
        insert course;
        Module__c module = TestDataFactory.createModule();
        insert module;
        Course_Module__c cm = new Course_Module__c();
        cm.Module__c = module.Id;
        cm.Course__c = course.Id;
        insert cm;
        
        Test.startTest();
        Module__c moduleUpdate = new Module__c();
        moduleUpdate.Id = module.Id;
        moduleUpdate.Full_Fee__c = 100;
        update moduleUpdate;
        Test.stopTest();

        Course_Module__c cmAfter = [SELECT Full_Fee__c, Full_Fee_GST_Amount__c FROM Course_Module__c];
        System.assertEquals(7, cmAfter.Full_Fee_GST_Amount__c);
        System.assertEquals(100, cmAfter.Full_Fee__c);
        
    }
}