force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <displayFormat>Course-{00000}</displayFormat>
        <label>Course Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Funding__c.field-meta.xml
<CustomField>
    <fullName>Funding__c</fullName>
    <description>Funding/Subsidies applicable for this Course</description>
    <label>Funding</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Funding</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Public_Course__c.field-meta.xml
<CustomField>
    <fullName>Public_Course__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Public Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/Course_Registration__c.object-meta.xml
<CustomObject>
    <label>Course Registration</label>
    <nameField>
        <displayFormat>REG-{0000}</displayFormat>
        <label>Course Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Registrations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Registration__c/fields/Attention__c.field-meta.xml
<CustomField>
    <fullName>Attention__c</fullName>
    <label>Attention</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Billing_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address_Line_1__c</fullName>
    <label>Billing Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <label>Billing City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_State__c</fullName>
    <label>Billing State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <inlineHelpText>Please leave it as &quot;Blank&quot; if you wish to repopulate the company details</inlineHelpText>
    <label>Company Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <label>Designation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural and Fishery Workers</fullName>
            </value>
            <value>
                <fullName>Associate Professionals and Technicians</fullName>
            </value>
            <value>
                <fullName>Cleaners, Labourers and Related Workers</fullName>
            </value>
            <value>
                <fullName>Clerical Workers</fullName>
            </value>
            <value>
                <fullName>Legislators, Senior Officials and Managers</fullName>
            </value>
            <value>
                <fullName>Plan and Machine Operators and Assemblers</fullName>
            </value>
            <value>
                <fullName>Production Craftsmen &amp; Related Workers</fullName>
            </value>
            <value>
                <fullName>Professionals</fullName>
            </value>
            <value>
                <fullName>Service Workers and Shop and Market Sales Workers</fullName>
            </value>
            <value>
                <fullName>Workers not classifed by Occupation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Designation_Level__c.field-meta.xml
<CustomField>
    <fullName>Designation_Level__c</fullName>
    <label>Designation Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Top Management</fullName>
            </value>
            <value>
                <fullName>Senior Management</fullName>
            </value>
            <value>
                <fullName>Middle Management</fullName>
            </value>
            <value>
                <fullName>Junior Management</fullName>
            </value>
            <value>
                <fullName>Non-Managerial Professional/ Technical Executive</fullName>
            </value>
            <value>
                <fullName>Non-Executive Staff</fullName>
            </value>
            <value>
                <fullName>Sole Proprietor</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Education_Level__c.field-meta.xml
<CustomField>
    <fullName>Education_Level__c</fullName>
    <label>Education Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Education_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Employment_Status__c.field-meta.xml
<CustomField>
    <fullName>Employment_Status__c</fullName>
    <label>Employment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Employed</fullName>
            </value>
            <value>
                <fullName>Unemployed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Home_No__c.field-meta.xml
<CustomField>
    <fullName>Home_No__c</fullName>
    <label>Home No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Mobile_No__c</fullName>
    <label>Mobile No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Monthly_Basic_Salary__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Basic_Salary__c</fullName>
    <label>Monthly Basic Salary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Below $1000</fullName>
            </value>
            <value>
                <fullName>$1,000 - $1,499</fullName>
            </value>
            <value>
                <fullName>$1,500 - $1,900</fullName>
            </value>
            <value>
                <fullName>$1,901 - $2,000</fullName>
            </value>
            <value>
                <fullName>$2,001 - $2,499</fullName>
            </value>
            <value>
                <fullName>$2,500 - $2,999</fullName>
            </value>
            <value>
                <fullName>$3,000 - $3,499</fullName>
            </value>
            <value>
                <fullName>$3,500 and Above</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/NRIC__c.field-meta.xml
<CustomField>
    <fullName>NRIC__c</fullName>
    <label>Identification Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/NRIC_Type__c.field-meta.xml
<CustomField>
    <fullName>NRIC_Type__c</fullName>
    <label>Identification Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Singapore Citizen/PR</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Office_No__c.field-meta.xml
<CustomField>
    <fullName>Office_No__c</fullName>
    <label>Office No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Persons_with_Disabilities__c.field-meta.xml
<CustomField>
    <fullName>Persons_with_Disabilities__c</fullName>
    <label>Persons with Disabilities</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Preferred_Certificate_Name__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Certificate_Name__c</fullName>
    <label>Preferred Certificate Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Primary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_Address__c</fullName>
    <label>Primary Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Race</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>Remarks</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Residency_Status__c.field-meta.xml
<CustomField>
    <fullName>Residency_Status__c</fullName>
    <inlineHelpText>Refers to type of residency in Singapore</inlineHelpText>
    <label>Residency Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Citizen</fullName>
            </value>
            <value>
                <fullName>Dependent Pass</fullName>
            </value>
            <value>
                <fullName>Employment Pass/Work Permit</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Permanent Resident</fullName>
            </value>
            <value>
                <fullName>Professional Pass</fullName>
            </value>
            <value>
                <fullName>Student Pass</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr</fullName>
            </value>
            <value>
                <fullName>Ms</fullName>
            </value>
            <value>
                <fullName>Mrs</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Prof.</fullName>
            </value>
            <value>
                <fullName>Mdm</fullName>
            </value>
            <value>
                <fullName>Rev.</fullName>
            </value>
            <value>
                <fullName>Sir Dr.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Secondary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Email_Address__c</fullName>
    <label>Alternate Contact Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Secondary_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Mobile__c</fullName>
    <label>Alternate Contact Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Secondary_Name__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Secondary_Salutation__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Salutation__c</fullName>
    <label>Alternate Contact Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Mdm</fullName>
            </value>
            <value>
                <fullName>Mr</fullName>
            </value>
            <value>
                <fullName>Mrs</fullName>
            </value>
            <value>
                <fullName>Ms</fullName>
            </value>
            <value>
                <fullName>Prof.</fullName>
            </value>
            <value>
                <fullName>Rev.</fullName>
            </value>
            <value>
                <fullName>Sir Dr.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/recordTypes/Course_Registration.recordType-meta.xml
<RecordType>
    <fullName>Course_Registration</fullName>
    <active>true</active>
    <description>Course Registeration</description>
    <label>Course Registration</label>
</RecordType>

force-app/main/default/objects/Course_Run__c/Course_Run__c.object-meta.xml
<CustomObject>
    <label>Course Run</label>
    <nameField>
        <displayFormat>COURSERUN-{000000}</displayFormat>
        <label>Course Run Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Run</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Run__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Run</relationshipLabel>
    <relationshipName>Course_Run</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Education_Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>No Formal Qualification &amp; Lower Primary</fullName>
    </customValue>
    <customValue>
        <fullName>Primary PSLE</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Lower Secondary</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;N&quot; Level or equivalent</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;O&quot; Level or equivalent</fullName>
    </customValue>
    <customValue>
        <fullName>ITE Skills Certification (ISC)</fullName>
    </customValue>
    <customValue>
        <fullName>A Level or equivalent</fullName>
    </customValue>
    <customValue>
        <fullName>NITEC/Post Nitec</fullName>
    </customValue>
    <customValue>
        <fullName>Higher NITEC</fullName>
    </customValue>
    <customValue>
        <fullName>Master NITEC</fullName>
    </customValue>
    <customValue>
        <fullName>WSQ Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>WSQ Higher Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>Polytechnic Diploma</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Qualification &amp; Other Diploma</fullName>
    </customValue>
    <customValue>
        <fullName>WSQ Advance Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>WSQ Diploma</fullName>
    </customValue>
    <customValue>
        <fullName>WSQ Special Diploma</fullName>
    </customValue>
    <customValue>
        <fullName>University First Degree</fullName>
    </customValue>
    <customValue>
        <fullName>University Post-graduate Diploma &amp; Degree/Master/Doctorate</fullName>
    </customValue>
    <customValue>
        <fullName>WSQ Graduate Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>WSQ Graduate Diploma</fullName>
    </customValue>
    <customValue>
        <fullName>Not Reported</fullName>
    </customValue>
    <masterLabel>Education Level</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Funding.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SkillsFuture Credit</fullName>
    </customValue>
    <customValue>
        <fullName>SkillsFuture Funding</fullName>
    </customValue>
    <customValue>
        <fullName>UTAP Funding</fullName>
    </customValue>
    <customValue>
        <fullName>Test Value</fullName>
    </customValue>
    <customValue>
        <fullName>IBF Funding</fullName>
    </customValue>
    <masterLabel>Funding</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Nationality.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Singapore_CITIZEN</fullName>
        <default>true</default>
        <label>Singapore CITIZEN</label>
    </customValue>
    <customValue>
        <fullName>Singapore PR</fullName>
    </customValue>
    <customValue>
        <fullName>Afghan</fullName>
    </customValue>
    <customValue>
        <fullName>Albanian</fullName>
    </customValue>
    <customValue>
        <fullName>Algerian</fullName>
    </customValue>
    <customValue>
        <fullName>American</fullName>
    </customValue>
    <customValue>
        <fullName>Andorran</fullName>
    </customValue>
    <customValue>
        <fullName>Angolan</fullName>
    </customValue>
    <customValue>
        <fullName>Anguillan</fullName>
    </customValue>
    <customValue>
        <fullName>Argentine</fullName>
    </customValue>
    <customValue>
        <fullName>Armenian</fullName>
    </customValue>
    <customValue>
        <fullName>Australian</fullName>
    </customValue>
    <customValue>
        <fullName>Austrian</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijani</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamian</fullName>
    </customValue>
    <customValue>
        <fullName>Bahraini</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladeshi</fullName>
    </customValue>
    <customValue>
        <fullName>Barbadian</fullName>
    </customValue>
    <customValue>
        <fullName>Belarusian</fullName>
    </customValue>
    <customValue>
        <fullName>Belgian</fullName>
    </customValue>
    <customValue>
        <fullName>Belizean</fullName>
    </customValue>
    <customValue>
        <fullName>Beninese</fullName>
    </customValue>
    <customValue>
        <fullName>Bermudian</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutanese</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivian</fullName>
    </customValue>
    <customValue>
        <fullName>Botswanan</fullName>
    </customValue>
    <customValue>
        <fullName>Brazilian</fullName>
    </customValue>
    <customValue>
        <fullName>British</fullName>
    </customValue>
    <customValue>
        <fullName>British Virgin Islander</fullName>
    </customValue>
    <customValue>
        <fullName>Bruneian</fullName>
    </customValue>
    <masterLabel>Nationality</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ShortenURLInvocableTest.cls
/*************************************************************************************************************
 * @name             ShortenURLInvocableTest
 * @author           BLR\rohit.pal <rohit.pal@crmit.com>
 * @created          28 / 10 / 2020
 * @description      Description of your code
 *
 * Changes (version)
 * -----------------------------------------------------------------------------------------------------------
 *               No.     Date            Author                  Description
 *               ----    ------------    --------------------    ----------------------------------------------
 * @version      1.0     2020-10-28      BLR\rohit.pal           Changes desription
 *
 **************************************************************************************************************/
@isTest(seeAllData = false)
private class ShortenURLInvocableTest {
    /**
     * @description 
     * @author Rohit Pal | 28-13-2020 
     **/

    @testSetup
    static void setupTestData() {
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];  
        
        Profile profile1 = [Select Id from Profile where name = 'System Administrator'];
        User portalAccountOwner1 = new User(
                                            UserRoleId = portalRole.Id,
                                            ProfileId = profile1.Id,
                                            Username = System.now().millisecond() + 'test222@test.com',
                                            Alias = 'batman',
                                            Email='bruce.wayne@wayneenterprises.com',
                                            EmailEncodingKey='UTF-8',
                                            Firstname='Bruce',
                                            Lastname='Wayne',
                                            LanguageLocaleKey='en_US',
                                            LocaleSidKey='en_US',
                                            TimeZoneSidKey='America/Chicago'
                                            );
        Database.insert(portalAccountOwner1);
        user portaluser; 
        Course_Run__c cr;
        Course_Registration__c objCourseRegistration;
        blob file =  Blob.valueOf('sample text');
        attachment att;
        Contact contact1;
        Course__c objCourse;

        System.runAs ( portalAccountOwner1 ) {    
         Account portalAccount1 = new Account(
                                            Name = 'TestAccount'
                                            );
                Database.insert(portalAccount1);
                
                //Create contact
                contact1 = new Contact(
                FirstName = 'Test',
                Lastname = 'McTesty',
                AccountId = portalAccount1.Id,
                Email = 'testCon@test.com',
                Company_Name__c = 'TestAccount'                
                );
                Database.insert(contact1);
                
                objCourse  = TestDataFactory.createCourse(portalAccount1.Id);
                objCourse.Public_Course__c = true;
                objCourse.Funding__c='SkillsFuture Credit';
                //update objCourse;
                insert objCourse;
                       
                cr = TestDataFactory.createCourseRun();
                cr.Course__c = objCourse.id;
                cr.Public_Course__c = true;
                insert cr;
                
                objCourseRegistration = TestDataFactory.createCourseRegistration(cr.id , contact1.id);
                objCourseRegistration.Salutation__c = 'Mr';
                objCourseRegistration.First_Name__c = 'test';
                objCourseRegistration.Last_Name__c = 'Lname';
                objCourseRegistration.Date_of_Birth__c = system.today().addyears(-10);
                objCourseRegistration.Preferred_Certificate_Name__c= 'test certificate name';
                objCourseRegistration.Gender__c = 'Male';
                objCourseRegistration.NRIC_Type__c = 'Passport';
                objCourseRegistration.NRIC__c = 'SA0001';
                objCourseRegistration.Email_Address__c = 'testCon@test.com';
                objCourseRegistration.Primary_Email_Address__c = 'test1@test.com';
                objCourseRegistration.Nationality__c = 'Singapore PR';
                objCourseRegistration.Mobile_No__c = '1234567890';
                objCourseRegistration.Race__c = 'CHINESE';
                objCourseRegistration.Home_No__c = '1234567891';
                objCourseRegistration.Residency_Status__c = 'Citizen';
                objCourseRegistration.Office_No__c = '3232325555';
                objCourseRegistration.Education_Level__c = 'Others';
                objCourseRegistration.Persons_with_Disabilities__c = 'No';
                objCourseRegistration.Employment_Status__c = 'Employed';
                objCourseRegistration.Job_Title__c = 'developer';
                objCourseRegistration.Company_Name__c = 'TestAccount';
                objCourseRegistration.Designation__c = 'Clerical Workers';
                objCourseRegistration.Monthly_Basic_Salary__c= 'Below $1000';
                objCourseRegistration.Designation_Level__c = 'Student';
                objCourseRegistration.Secondary_Salutation__c = 'Ms';
                objCourseRegistration.Secondary_Name__c = 'test name';
                objCourseRegistration.Secondary_Email_Address__c = 'second@test.com';
                objCourseRegistration.Secondary_Mobile__c = '1234567890';
                objCourseRegistration.Remarks__c = 'test remarks';
                objCourseRegistration.Attention__c = 'test attentions';
                objCourseRegistration.Billing_State__c = 'AP';
                objCourseRegistration.Billing_Address_Line_1__c = 'test line1';
                objCourseRegistration.Billing_City__c= 'test city';
                objCourseRegistration.Billing_Address_Line_2__c = 'test line2';
                objCourseRegistration.Billing_Country__c = 'Singapore';
                objCourseRegistration.Billing_Address_Line_3__c = 'test line3';
                objCourseRegistration.Billing_Postal_Code__c = '500050';
                objCourseRegistration.Address_Type__c = 'Home';
                objCourseRegistration.Preferred_Contact_Method__c = 'Email';
                objCourseRegistration.Alternative_Attention__c = 'test attention';
                objCourseRegistration.Alternative_State__c = 'test state';
                objCourseRegistration.Alternative_Billing_Line_1__c = 'test alternative line1';
                objCourseRegistration.Alternative_City__c  = 'test alter city';
                objCourseRegistration.Alternative_Billing_Line_2__c = 'test alter line2';
                objCourseRegistration.Alternative_Country__c = 'Singapore';
                objCourseRegistration.Alternative_Billing_Line_3__c = 'test alter line3';
                objCourseRegistration.Alternative_Postal_Code__c = '500070';
                objCourseRegistration.Alternative_Email__c = 'testAlter@test.com';
                objCourseRegistration.Alternative_Phone__c = '4544545454';   
                objCourseRegistration.Company_UEN_No__c = '123';
                insert objCourseRegistration;
                 system.debug('objCourseRegistration ==>' + objCourseRegistration.Email_Address__c);
              
          }
    }

    /**
     * @description : 
     * @author Rohit Pal | 2020-10-28 
     * @return void 
     **/
    static testMethod void shortenAsyncTest() {
        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new ShortenURLMock());
        List < List < String >> listCourseRegistrationSurveyURL = new List < List < String >> ();
        List < String > listCrsRegSurveyURL = new List < String > ();
        Account acc = [SELECT Id FROM Account];
        Contact con = [SELECT Id, Email FROM Contact WHERE AccountId =: acc.Id];
        Course_Registration__c course_Registration = [SELECT Id, 
                                                                Course_Run_Id__c,
                                                                Email_Address__c, 
                                                                Contact__c, 
                                                                Contact__r.Email, 
                                                                Contact__r.Primary_Email_Address__c, 
                                                                Contact__r.Alternative_Email__c 
                                                        FROM Course_Registration__c 
                                                        WHERE Email_Address__c = 'testCon@test.com'];

        system.debug('inside test class' + course_Registration.Email_Address__c + ' @@@ >> ' + course_Registration.Contact__c + ' << Email >>' + course_Registration.Contact__r.Email);
        listCrsRegSurveyURL.add('https://www.InvitationLinkAnonymous.com');
        listCrsRegSurveyURL.add('https://www.wstrInvitationLink.com');
        listCrsRegSurveyURL.add(course_Registration.Id);
        listCrsRegSurveyURL.add(course_Registration.Course_Run_Id__c);
        listCourseRegistrationSurveyURL.add(listCrsRegSurveyURL);


        ShortenURLInvocable.shorten(listCourseRegistrationSurveyURL);
        
        Test.stopTest();
    }

}