force-app/main/default/objects/Invoice_Discount__c/Invoice_Discount__c.object-meta.xml
<CustomObject>
    <label>Invoice Discount</label>
    <nameField>
        <displayFormat>IVDIS-{0000}</displayFormat>
        <label>Invoice Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Discount__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <inlineHelpText>If left empty, Amount, GST Amount, and GST Code will be taken from the Discount selected</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Discount__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <inlineHelpText>If left empty, Amount, GST Amount, and GST Code will be taken from the Discount selected</inlineHelpText>
    <label>GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Discount__c/fields/GST_Mode__c.field-meta.xml
<CustomField>
    <fullName>GST_Mode__c</fullName>
    <inlineHelpText>Full - Exclusive of GST
Nett - Inclusive of GST</inlineHelpText>
    <label>GST Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_Mode</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/GST_Mode.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Full</fullName>
        <default>true</default>
        <label>Full</label>
    </customValue>
    <customValue>
        <fullName>Nett</fullName>
    </customValue>
    <masterLabel>GST Mode</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InvoiceDiscountTriggerHandler.cls
public without sharing class InvoiceDiscountTriggerHandler {
    public static void calculateGST(List<Invoice_Discount__c> itemDiscList, Map<Id, Invoice_Discount__c> itemDiscMap) {
        Map<String, Decimal> gstCodeMap = Utility.getGSTCodeMap();
        List<Invoice_Discount__c> updateItemDisc = new List<Invoice_Discount__c>();
        for (Invoice_Discount__c lineDisc : itemDiscList) {
            if (itemDiscMap.containsKey(lineDisc.Id)) {
                Invoice_Discount__c oldItemDisc = itemDiscMap.get(lineDisc.Id);
                if (lineDisc.GST_Calculated__c == true) {
                    Invoice_Discount__c clearFlag = new Invoice_Discount__c();
                    clearFlag.Id = lineDisc.Id;
                    clearFlag.GST_Calculated__c = false;
                    updateItemDisc.add(clearFlag);
                    continue;
                }
                if (oldItemDisc.Amount__c == lineDisc.Amount__c &&
                    oldItemDisc.GST_Code__c == lineDisc.GST_Code__c &&
                    oldItemDisc.GST_Mode__c == lineDisc.GST_Mode__c) {
                    continue;
                }
            }

            if (lineDisc.Amount__c == null) {
                continue;
            }

            Invoice_Discount__c lineDiscUpdate = new Invoice_Discount__c();
            lineDiscUpdate.Id = lineDisc.Id;
            if (lineDisc.GST_Mode__c == 'Nett') {
                Decimal gstAmt = Utility.calculateGST(lineDisc.Amount__c, lineDisc.GST_Code__c, gstCodeMap, lineDisc.GST_Mode__c);
                lineDiscUpdate.GST_Amount__c = gstAmt;
                lineDiscUpdate.Amount__c = lineDisc.Amount__c - lineDiscUpdate.GST_Amount__c;
            }
            else {
                lineDiscUpdate.GST_Amount__c = Utility.calculateGST(lineDisc.Amount__c, lineDisc.GST_Code__c, gstCodeMap);
            }
            lineDiscUpdate.GST_Calculated__c = true;
            updateItemDisc.add(lineDiscUpdate);
        }

        if (updateItemDisc.size() > 0) {
            update updateItemDisc;
        }
    }
}