force-app/main/default/objects/Deduction__c/Deduction__c.object-meta.xml
<CustomObject>
    <label>Note Detail</label>
    <nameField>
        <displayFormat>NOTEDTL-{0000}</displayFormat>
        <label>Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Note Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deduction__c/fields/Deduction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deduction_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Deduction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deduction__c/fields/Deduction_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deduction_GST_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Deduction GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deduction__c/fields/Deduction_GST_Code__c.field-meta.xml
<CustomField>
    <fullName>Deduction_GST_Code__c</fullName>
    <label>Deduction GST Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/GST_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>02</fullName>
        <label>0% (Oversea)</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <default>true</default>
        <label>7%</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>0% (Local)</label>
    </customValue>
    <masterLabel>GST Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DeductionTriggerHandler.cls
public with sharing class DeductionTriggerHandler {
    public static void calculateGST(List<Deduction__c> deductionList, Map<Id, Deduction__c> deductionMap) {
        Map<String, Decimal> gstCodeMap = Utility.getGSTCodeMap();
        List<Deduction__c> updateDeduction = new List<Deduction__c>();
        for (Deduction__c deduction : deductionList) {
            if (deductionMap.containsKey(deduction.Id)) {
                Deduction__c oldDeduction = deductionMap.get(deduction.Id);
                if (oldDeduction.Deduction_Amount__c == deduction.Deduction_Amount__c &&
                    oldDeduction.Deduction_GST_Code__c == deduction.Deduction_GST_Code__c) {
                    continue;
                }
            }

            Deduction__c deductionUpdate = new Deduction__c();
            deductionUpdate.Id = deduction.Id;
            if (deduction.Deduction_Amount__c > 0) {
                deductionUpdate.Deduction_GST_Amount__c = Utility.calculateGST(deduction.Deduction_Amount__c, deduction.Deduction_GST_Code__c, gstCodeMap);
            }
            else {
                deductionUpdate.Deduction_GST_Amount__c = 0;
            }
            updateDeduction.add(deductionUpdate);
        }

        if (updateDeduction.size() > 0) {
            update updateDeduction;
        }
    }
}