force-app/main/default/objects/Course_Module__c/Course_Module__c.object-meta.xml
<CustomObject>
    <label>Course Module</label>
    <nameField>
        <displayFormat>CMOD-{0000}</displayFormat>
        <label>Course Module Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Module__c/fields/Baseline_Grant__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Grant__c</fullName>
    <label>Baseline Grant</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/Baseline_Grant_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Grant_GST_Amount__c</fullName>
    <label>Baseline Grant GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/Full_Fee__c.field-meta.xml
<CustomField>
    <fullName>Full_Fee__c</fullName>
    <label>Full Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/Full_Fee_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Full_Fee_GST_Amount__c</fullName>
    <label>Full Fee GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/Mid_Career__c.field-meta.xml
<CustomField>
    <fullName>Mid_Career__c</fullName>
    <label>Mid-Career</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/Mid_Career_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Mid_Career_GST_Amount__c</fullName>
    <label>Mid-Career GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Course Modules</relationshipLabel>
    <relationshipName>Course_Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/Non_SME_Grant__c.field-meta.xml
<CustomField>
    <fullName>Non_SME_Grant__c</fullName>
    <label>Non-SME Grant</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/Non_SME_Grant_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Non_SME_Grant_GST_Amount__c</fullName>
    <label>Non-SME Grant GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/SME_Grant__c.field-meta.xml
<CustomField>
    <fullName>SME_Grant__c</fullName>
    <label>SME Grant</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/SME_Grant_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>SME_Grant_GST_Amount__c</fullName>
    <label>SME Grant GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/Workfare__c.field-meta.xml
<CustomField>
    <fullName>Workfare__c</fullName>
    <label>IBF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/Workfare_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Workfare_GST_Amount__c</fullName>
    <label>IBF GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/fields/Baseline_Grant__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Grant__c</fullName>
    <label>Baseline Grant</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Baseline_Grant_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Grant_GST_Amount__c</fullName>
    <label>Baseline Grant GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Full_Fee__c.field-meta.xml
<CustomField>
    <fullName>Full_Fee__c</fullName>
    <label>Full Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Full_Fee_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Full_Fee_GST_Amount__c</fullName>
    <label>Full Fee GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/GST_Code__c.field-meta.xml
<CustomField>
    <fullName>GST_Code__c</fullName>
    <label>GST Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module__c/fields/Mid_Career__c.field-meta.xml
<CustomField>
    <fullName>Mid_Career__c</fullName>
    <label>Mid-Career</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Mid_Career_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Mid_Career_GST_Amount__c</fullName>
    <label>Mid-Career GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Non_SME_Grant__c.field-meta.xml
<CustomField>
    <fullName>Non_SME_Grant__c</fullName>
    <label>Non-SME Grant</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Non_SME_Grant_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Non_SME_Grant_GST_Amount__c</fullName>
    <label>Non-SME Grant GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/SME_Grant__c.field-meta.xml
<CustomField>
    <fullName>SME_Grant__c</fullName>
    <label>SME Grant</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/SME_Grant_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>SME_Grant_GST_Amount__c</fullName>
    <label>SME Grant GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Workfare__c.field-meta.xml
<CustomField>
    <fullName>Workfare__c</fullName>
    <label>Workfare</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Workfare_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Workfare_GST_Amount__c</fullName>
    <label>Workfare GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/GST_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>02</fullName>
        <label>0% (Oversea)</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <default>true</default>
        <label>7%</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>0% (Local)</label>
    </customValue>
    <masterLabel>GST Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ModuleTriggerHandler.cls
public without sharing class ModuleTriggerHandler {
    public static void calculateGST(List<Module__c> moduleList, Map<Id, Module__c> moduleMap) {
        Map<String, Decimal> gstCodeMap = Utility.getGSTCodeMap();
        List<Module__c> updateModule = new List<Module__c>();
        for (Module__c module : moduleList) {
            if (moduleMap.containsKey(module.Id)) {
                Module__c oldModule = moduleMap.get(module.Id);
                if (oldModule.Full_Fee__c == module.Full_Fee__c &&
                    oldModule.GST_Code__c == module.GST_Code__c) {
                    continue;
                }
            }
            Module__c moduleUpdate = new Module__c();
            moduleUpdate.Id = module.Id;
            moduleUpdate.Full_Fee_GST_Amount__c = Utility.calculateGST(module.Full_Fee__c, module.GST_Code__c, gstCodeMap);
            updateModule.add(moduleUpdate);
            
        }

        if (updateModule.size() > 0) {
            update updateModule;
        }
    }

    public static void updateCourseModules(Map<Id, Module__c> moduleMap) {
        //Replacement to Flow Trigger
        List<Course_Module__c> courseModules = new List<Course_Module__c>();

        for (Course_Module__c cm : [SELECT Id, Module__c FROM Course_Module__c WHERE Module__c =: moduleMap.keySet()]) {
            Module__c module = moduleMap.get(cm.Module__c);
            Course_Module__c cmUpdate = new Course_Module__c();
            cmUpdate.Id = cm.Id;
            cmUpdate.Full_Fee__c = module.Full_Fee__c;
            cmUpdate.SME_Grant__c = module.SME_Grant__c;
            cmUpdate.Non_SME_Grant__c = module.Non_SME_Grant__c;
            cmUpdate.Baseline_Grant__c = module.Baseline_Grant__c;
            cmUpdate.Workfare__c = module.Workfare__c;
            cmUpdate.Mid_Career__c = module.Mid_Career__c;

            cmUpdate.Full_Fee_GST_Amount__c = module.Full_Fee_GST_Amount__c;
            cmUpdate.SME_Grant_GST_Amount__c = module.SME_Grant_GST_Amount__c;
            cmUpdate.Non_SME_Grant_GST_Amount__c = module.Non_SME_Grant_GST_Amount__c;
            cmUpdate.Baseline_Grant_GST_Amount__c = module.Baseline_Grant_GST_Amount__c;
            cmUpdate.Workfare_GST_Amount__c = module.Workfare_GST_Amount__c;
            cmUpdate.Mid_Career_GST_Amount__c = module.Mid_Career_GST_Amount__c;

            courseModules.add(cmUpdate);
        }

        if (courseModules.size() > 0) {
            update courseModules;
        }
    }
}