force-app/main/default/objects/Accounting_Notes__c/Accounting_Notes__c.object-meta.xml
<CustomObject>
    <label>Accounting Notes</label>
    <nameField>
        <displayFormat>NOTE-{0000}</displayFormat>
        <label>Accounting Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Accounting_Notes__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <summarizedField>Deduction__c.Amount__c</summarizedField>
    <summaryForeignKey>Deduction__c.Accounting_Notes__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Accounting_Notes__c/fields/Attention_To__c.field-meta.xml
<CustomField>
    <fullName>Attention_To__c</fullName>
    <label>Attention To</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accounting_Notes__c/fields/Course_Registration__c.field-meta.xml
<CustomField>
    <fullName>Course_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Registration</label>
    <referenceTo>Course_Registration__c</referenceTo>
    <relationshipLabel>Accounting Notes</relationshipLabel>
    <relationshipName>Accounting_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Accounting_Notes__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <label>GST Amount</label>
    <summarizedField>Deduction__c.GST_Amount__c</summarizedField>
    <summaryForeignKey>Deduction__c.Accounting_Notes__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Accounting_Notes__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Accounting Notes</relationshipLabel>
    <relationshipName>Accounting_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <displayFormat>Course-{00000}</displayFormat>
        <label>Course Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>Cost_Center__c</fullName>
    <label>Cost Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cost_Center</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Center__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Fee_Code__c.field-meta.xml
<CustomField>
    <fullName>Fee_Code__c</fullName>
    <label>Fee Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Center__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Fee_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/GST_Code__c.field-meta.xml
<CustomField>
    <fullName>GST_Code__c</fullName>
    <label>GST Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Non_Member_Fee__c.field-meta.xml
<CustomField>
    <fullName>Non_Member_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Non-Member Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course__c/recordTypes/Course.recordType-meta.xml
<RecordType>
    <fullName>Course</fullName>
    <active>true</active>
    <description>Public Courses /Courses without SSG Modules/Courses with Skill future credit</description>
    <label>Course</label>
</RecordType>

force-app/main/default/objects/Course_Registration__c/Course_Registration__c.object-meta.xml
<CustomObject>
    <label>Course Registration</label>
    <nameField>
        <displayFormat>REG-{0000}</displayFormat>
        <label>Course Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Registrations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Run__c/Course_Run__c.object-meta.xml
<CustomObject>
    <label>Course Run</label>
    <nameField>
        <displayFormat>COURSERUN-{000000}</displayFormat>
        <label>Course Run Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Run</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Run__c/fields/Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>Cost_Center__c</fullName>
    <label>Cost Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cost_Center</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Run__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Run</relationshipLabel>
    <relationshipName>Course_Run</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Run__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Center__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Run__c/fields/Fee_Code__c.field-meta.xml
<CustomField>
    <fullName>Fee_Code__c</fullName>
    <label>Fee Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Center__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Fee_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deduction__c/Deduction__c.object-meta.xml
<CustomObject>
    <label>Note Detail</label>
    <nameField>
        <displayFormat>NOTEDTL-{0000}</displayFormat>
        <label>Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Note Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deduction__c/fields/Accounting_Notes__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Notes__c</fullName>
    <label>Accounting Note</label>
    <referenceTo>Accounting_Notes__c</referenceTo>
    <relationshipLabel>Note Details</relationshipLabel>
    <relationshipName>Deductions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deduction__c/fields/Deduction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deduction_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Deduction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deduction__c/fields/Deduction_Fee_Code__c.field-meta.xml
<CustomField>
    <fullName>Deduction_Fee_Code__c</fullName>
    <label>Deduction Fee Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fee_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deduction__c/fields/Deduction_GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deduction_GST_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Deduction GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deduction__c/fields/Deduction_GST_Code__c.field-meta.xml
<CustomField>
    <fullName>Deduction_GST_Code__c</fullName>
    <label>Deduction GST Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deduction__c/fields/Fee_Code__c.field-meta.xml
<CustomField>
    <fullName>Fee_Code__c</fullName>
    <label>Fee Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fee_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deduction__c/fields/Invoice_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Line Item</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Accounting Note is not selected</errorMessage>
        <filterItems>
            <field>$Source.Accounting_Notes__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Invoice_Line_Item__c</referenceTo>
    <relationshipLabel>Note Details</relationshipLabel>
    <relationshipName>Deductions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <summarizedField>Invoice_Line_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Course_Registration__c.field-meta.xml
<CustomField>
    <fullName>Course_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Registration</label>
    <referenceTo>Course_Registration__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <label>GST Amount</label>
    <summarizedField>Invoice_Line_Item__c.GST_Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>Cost_Center__c</fullName>
    <label>Cost Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cost_Center</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Course_Registration__c.field-meta.xml
<CustomField>
    <fullName>Course_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Registration</label>
    <referenceTo>Course_Registration__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Course_Run__c.field-meta.xml
<CustomField>
    <fullName>Course_Run__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Run</label>
    <referenceTo>Course_Run__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Center__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Fee_Code__c.field-meta.xml
<CustomField>
    <fullName>Fee_Code__c</fullName>
    <label>Fee Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Center__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Fee_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/GST_Code__c.field-meta.xml
<CustomField>
    <fullName>GST_Code__c</fullName>
    <label>GST Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Cost_Center.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SM1040</fullName>
    </customValue>
    <customValue>
        <fullName>AE1000</fullName>
    </customValue>
    <customValue>
        <fullName>RAMA</fullName>
    </customValue>
    <customValue>
        <fullName>SM1033</fullName>
    </customValue>
    <customValue>
        <fullName>CAM</fullName>
    </customValue>
    <customValue>
        <fullName>CAP</fullName>
    </customValue>
    <customValue>
        <fullName>REPD</fullName>
    </customValue>
    <customValue>
        <fullName>SM1043</fullName>
    </customValue>
    <customValue>
        <fullName>SM1034</fullName>
    </customValue>
    <customValue>
        <fullName>RENC</fullName>
    </customValue>
    <masterLabel>Cost Center</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Department.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PM</fullName>
    </customValue>
    <customValue>
        <fullName>ACD</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>CAM</fullName>
    </customValue>
    <customValue>
        <fullName>CAP</fullName>
    </customValue>
    <customValue>
        <fullName>EPD</fullName>
    </customValue>
    <customValue>
        <fullName>FP</fullName>
    </customValue>
    <customValue>
        <fullName>PM-FP</fullName>
    </customValue>
    <customValue>
        <fullName>E&amp;C</fullName>
    </customValue>
    <masterLabel>Department</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/GST_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>02</fullName>
        <label>0% (Oversea)</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <default>true</default>
        <label>7%</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>0% (Local)</label>
    </customValue>
    <masterLabel>GST Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DeductionTriggerHandlerTest.cls
@IsTest
public with sharing class DeductionTriggerHandlerTest {
    //2021-03-31 Poon Koon: Update data preparation class
    @TestSetup
    static void makeData(){
        Id b2cLearnerRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('B2C_Learner').getRecordTypeId();
        Account acct = new Account();
        acct.RecordTypeId = b2cLearnerRT;
        acct.FirstName = 'Test';
        acct.LastName = 'Account';
        acct.PersonEmail = 'testApexUser@sim.edu.sg';
        acct.Credit_Term_Days__c = 14;
        insert acct;
        acct = [SELECT Id, PersonContactId FROM Account];

        Id courseRT = Schema.SObjectType.Course__c.getRecordTypeInfosByDeveloperName().get('Course').getRecordTypeId();
        Course__c course = TestDataFactory.createCourse(null);
        course.RecordTypeId = courseRT;
        course.Non_Member_Fee__c = 100;
        course.Fee_Code__c = 'PROGRM';
        course.Cost_Center__c = 'SM1040';
        insert course;

        Course_Run__c courseRun = TestDataFactory.createCourseRun();
        courseRun.Course__c = course.Id;
        courseRun.Fee_Code__c = 'PROGRM';
        courseRun.Cost_Center__c = 'SM1040';
        insert courseRun;

        //Create Course Registration from TestDataFactory
        Course_Registration__c reg = TestDataFactory.createCourseRegistration(courseRun.Id, acct.PersonContactId);
        insert reg;

        InvoiceUtility.generateInvoiceForRegistration(reg.Id);
    }

    @IsTest
    static void calculateGSTWithDeduction() {

        Id invoiceId = [SELECT Id FROM Invoice__c LIMIT 1].Id;
        Accounting_Notes__c acct = new Accounting_Notes__c();
        acct.Invoice__c = invoiceId;
        acct.Attention_To__c = 'Test';
        
        insert acct;
        Invoice_Line_Item__c lineItem = [SELECT Fee_Code__c, Department__c, Cost_Center__c FROM Invoice_Line_Item__c LIMIT 1];
        Deduction__c deduction = new Deduction__c();
        deduction.GST_Code__c = '12';
        deduction.Amount__c = 100;
        deduction.GST_Amount__c = 10;
        deduction.Accounting_Notes__c = acct.Id;
        deduction.Fee_Code__c = lineItem.Fee_Code__c;
        deduction.Deduction_Amount__c = 200;
        deduction.Deduction_GST_Code__c = '12';
        deduction.Deduction_Fee_Code__c = lineItem.Fee_Code__c;
        Test.startTest();
        insert deduction;
        Test.stopTest();
        
        Deduction__c deductionAfter = [SELECT GST_Amount__c, Deduction_GST_Amount__c FROM Deduction__c WHERE Id=: deduction.Id];
        System.assertEquals(10, deductionAfter.GST_Amount__c);
        System.assertEquals(14, deductionAfter.Deduction_GST_Amount__c);
    }

    @IsTest
    static void calculateGST() {

        Id invoiceId = [SELECT Id FROM Invoice__c LIMIT 1].Id;
        Accounting_Notes__c acct = new Accounting_Notes__c();
        acct.Invoice__c = invoiceId;
        acct.Attention_To__c = 'Test';
        
        insert acct;
        Invoice_Line_Item__c lineItem = [SELECT Fee_Code__c, Department__c, Cost_Center__c FROM Invoice_Line_Item__c LIMIT 1];
        Deduction__c deduction = new Deduction__c();
        deduction.GST_Code__c = '12';
        deduction.Amount__c = 100;
        deduction.GST_Amount__c = 0;
        deduction.Accounting_Notes__c = acct.Id;
        deduction.Fee_Code__c = lineItem.Fee_Code__c;
        deduction.Deduction_Amount__c = 0;
        deduction.Deduction_GST_Code__c = '12';
        deduction.Deduction_Fee_Code__c = lineItem.Fee_Code__c;
        Test.startTest();
        insert deduction;
        Test.stopTest();
        
        Deduction__c deductionAfter = [SELECT GST_Amount__c, Deduction_GST_Amount__c FROM Deduction__c WHERE Id=: deduction.Id];
        System.assertEquals(0, deductionAfter.GST_Amount__c);
        System.assertEquals(0, deductionAfter.Deduction_GST_Amount__c);
    }
}