force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <label>Discount Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <label>GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/GST_Code__c.field-meta.xml
<CustomField>
    <fullName>GST_Code__c</fullName>
    <label>GST Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Percentage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/GST_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>02</fullName>
        <label>0% (Oversea)</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <default>true</default>
        <label>7%</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>0% (Local)</label>
    </customValue>
    <masterLabel>GST Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DiscountTriggerHandler.cls
public without sharing class DiscountTriggerHandler {
    public static void calculateGST(List<Discount__c> discountList, Map<Id, Discount__c> discountMap) {
        Map<String, Decimal> gstCodeMap = Utility.getGSTCodeMap();
        List<Discount__c> updateDiscount = new List<Discount__c>();
        for (Discount__c discount : discountList) {
            if (discountMap.containsKey(discount.Id)) {
                Discount__c oldDiscount = discountMap.get(discount.Id);
                if (oldDiscount.Amount__c == discount.Amount__c &&
                    oldDiscount.GST_Code__c == discount.GST_Code__c) {
                    continue;
                }
            }
            if (discount.Percentage__c == false) {            
                Discount__c discountUpdate = new Discount__c();
                discountUpdate.Id = discount.Id;
                discountUpdate.GST_Amount__c = Utility.calculateGST(discount.Amount__c, discount.GST_Code__c, gstCodeMap);
                updateDiscount.add(discountUpdate);
            }
        }

        if (updateDiscount.size() > 0) {
            update updateDiscount;
        }
    }
}