force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <label>Discount Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <label>GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/GST_Code__c.field-meta.xml
<CustomField>
    <fullName>GST_Code__c</fullName>
    <label>GST Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Percentage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/GST_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>02</fullName>
        <label>0% (Oversea)</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <default>true</default>
        <label>7%</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>0% (Local)</label>
    </customValue>
    <masterLabel>GST Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DiscountTriggerHandlerTest.cls
@IsTest
public without sharing class DiscountTriggerHandlerTest {
    @IsTest
    static void calculateGST(){
        Discount__c disc = TestDataFactory.createDiscount();
        disc.Amount__c = 100;
        disc.GST_Amount__c = 0;
        disc.GST_Code__c = '12';
        disc.Percentage__c = false;
        
        Test.startTest();
        insert disc;
        Test.stopTest();
        
        Discount__c discAfter = [SELECT GST_Amount__c FROM Discount__c WHERE Id=: disc.Id];
        System.assertEquals(7, discAfter.GST_Amount__c);
    }

    @IsTest
    static void calculateGSTPercentage(){
        Discount__c disc = TestDataFactory.createDiscount();
        disc.Amount__c = 100;
        disc.GST_Amount__c = 0;
        disc.Percentage__c = true;
        disc.GST_Code__c = '12';
        Test.startTest();
        insert disc;
        Test.stopTest();
        
        Discount__c discAfter = [SELECT GST_Amount__c FROM Discount__c WHERE Id=: disc.Id];
        System.assertEquals(0, discAfter.GST_Amount__c);
    }
}