force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Ensure that the new category is added to the Global Value Set (&quot;Categories&quot;)</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <displayFormat>Course-{00000}</displayFormat>
        <label>Course Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Course_Code__c.field-meta.xml
<CustomField>
    <fullName>Course_Code__c</fullName>
    <externalId>true</externalId>
    <label>Course Code</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Course__c/fields/GST_Code__c.field-meta.xml
<CustomField>
    <fullName>GST_Code__c</fullName>
    <label>GST Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/GST_Mode__c.field-meta.xml
<CustomField>
    <fullName>GST_Mode__c</fullName>
    <label>GST Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_Mode</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Member_Fee__c.field-meta.xml
<CustomField>
    <fullName>Member_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Member Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Member_GST_Fee__c.field-meta.xml
<CustomField>
    <fullName>Member_GST_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Member GST Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Non_Member_Fee__c.field-meta.xml
<CustomField>
    <fullName>Non_Member_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Non-Member Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Non_Member_GST_Fee__c.field-meta.xml
<CustomField>
    <fullName>Non_Member_GST_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Non-Member GST Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/RMIT_Alumni_Fee__c.field-meta.xml
<CustomField>
    <fullName>RMIT_Alumni_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RMIT Alumni Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/RMIT_Alumni_GST_Fee__c.field-meta.xml
<CustomField>
    <fullName>RMIT_Alumni_GST_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RMIT Alumni GST Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course__c/recordTypes/Course.recordType-meta.xml
<RecordType>
    <fullName>Course</fullName>
    <active>true</active>
    <description>Public Courses /Courses without SSG Modules/Courses with Skill future credit</description>
    <label>Course</label>
</RecordType>

force-app/main/default/objects/Course_Category__c/Course_Category__c.object-meta.xml
<CustomObject>
    <label>Course Category</label>
    <nameField>
        <displayFormat>CCAT-{0000}</displayFormat>
        <label>Course Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Categories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Course Categories</relationshipLabel>
    <relationshipName>Course_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Category__c/fields/Category_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Category_Picklist__c</fullName>
    <label>Category Picklist</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Category__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Categories</relationshipLabel>
    <relationshipName>Course_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agile At Scale</fullName>
    </customValue>
    <customValue>
        <fullName>Agility</fullName>
    </customValue>
    <customValue>
        <fullName>AI SmokeTest</fullName>
    </customValue>
    <customValue>
        <fullName>Artificial Intelligence</fullName>
    </customValue>
    <customValue>
        <fullName>Business &amp; Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Business Insight</fullName>
    </customValue>
    <customValue>
        <fullName>Category 1</fullName>
    </customValue>
    <customValue>
        <fullName>Change Management</fullName>
    </customValue>
    <customValue>
        <fullName>Communication</fullName>
    </customValue>
    <customValue>
        <fullName>Communication - General</fullName>
    </customValue>
    <customValue>
        <fullName>Communication - Spoken</fullName>
    </customValue>
    <customValue>
        <fullName>Communication - Written</fullName>
    </customValue>
    <customValue>
        <fullName>Complex Adaptive Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Creativity &amp; Innovation</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Service</fullName>
    </customValue>
    <customValue>
        <fullName>CX &amp; UX</fullName>
        <label>CX,UX &amp; UI</label>
    </customValue>
    <customValue>
        <fullName>Data Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Design Thinking</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Practices</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Transformation</fullName>
    </customValue>
    <customValue>
        <fullName>Disruptive Innovation</fullName>
    </customValue>
    <customValue>
        <fullName>Diversity Management</fullName>
    </customValue>
    <customValue>
        <fullName>Employability Skills System</fullName>
    </customValue>
    <customValue>
        <fullName>Events &amp; Conferences</fullName>
    </customValue>
    <customValue>
        <fullName>Evergreen Leadership</fullName>
    </customValue>
    <customValue>
        <fullName>Finance &amp; Legal</fullName>
    </customValue>
    <customValue>
        <fullName>General Management</fullName>
    </customValue>
    <customValue>
        <fullName>HR Development</fullName>
    </customValue>
    <customValue>
        <fullName>HR Management</fullName>
    </customValue>
    <customValue>
        <fullName>HR Management &amp; Development</fullName>
    </customValue>
    <customValue>
        <fullName>Innovation</fullName>
    </customValue>
    <description>Category for Courses</description>
    <masterLabel>Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/GST_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>02</fullName>
        <label>0% (Oversea)</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <default>true</default>
        <label>7%</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>0% (Local)</label>
    </customValue>
    <masterLabel>GST Code</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/GST_Mode.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Full</fullName>
        <default>true</default>
        <label>Full</label>
    </customValue>
    <customValue>
        <fullName>Nett</fullName>
    </customValue>
    <masterLabel>GST Mode</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CourseTriggerHandlerTest.cls
/**
 * @description       : 
 * @author            : Mark Alvin Tayag (mtayag@salesforce.com)
 * @group             : 
 * @last modified on  : 10-31-2020
 * @last modified by  : Mark Alvin Tayag (mtayag@salesforce.com)
 * Modifications Log 
 * Ver   Date         Author                                     Modification
 * 1.0   10-31-2020   Mark Alvin Tayag (mtayag@salesforce.com)   Initial Version
 * 1.1   2021-03-15   Poon Koon                                  Updated Assertion Values for Nett GST calculation
**/
@istest
public class CourseTriggerHandlerTest {
    @TestSetup
    static void makeData() {
        category__c cat = TestDataFactory.createCategory();
        cat.Category__c = 'Agility';
        insert cat;
        
        category__c cat2 = TestDataFactory.createCategory();
        cat2.Category__c = 'Innovation';
        insert cat2;        
        
        Id personAccountRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        account acc = TestDataFactory.createAccount(personAccountRT);
        acc.LastName = 'test';
        insert acc;
    }

    public static testmethod void singleInsertCategory() {
        Account acc = [SELECT Id FROM Account];
        Test.startTest();
        course__c course = TestDataFactory.createCourse(acc.id);
        course.category__c = 'Agility';
        insert course;
        Test.stopTest();
        
        List<Course_Category__c> cc = [SELECT id,
                                              Category_Picklist__c 
                                        FROM Course_Category__c 
                                        WHERE Course__c =: course.id];
        System.assertEquals(1, cc.size());
        System.assertEquals(cc[0].Category_Picklist__c, 'Agility');
    }

    public static testmethod void multipleInsertCategories() {
        Account acc = [SELECT Id FROM Account];

        Test.startTest();
        course__c course = TestDataFactory.createCourse(acc.id);
        course.category__c = 'Agility;Innovation';
        insert course;
        Test.stopTest();
        
        List<Course_Category__c> cc = [SELECT id,
                                              Category_Picklist__c 
                                        FROM Course_Category__c 
                                        WHERE Course__c =: course.id];
        System.assertEquals(2, cc.size());
        for (Course_Category__c ccat : cc) {
            System.assert(ccat.Category_Picklist__c == 'Agility' || 
                            ccat.Category_Picklist__c == 'Innovation');
        }
    }

    public static testmethod void updateCategory() {
        Account acc = [SELECT Id FROM Account];

        course__c course = TestDataFactory.createCourse(acc.id);
        course.category__c = 'Agility;Innovation';
        insert course;

        Test.startTest();
        course.category__c = 'Agility';
        update course;
        Test.stopTest();
        
        List<Course_Category__c> cc = [SELECT id,
                                              Category_Picklist__c 
                                        FROM Course_Category__c 
                                        WHERE Course__c =: course.id];

        System.assertEquals(1, cc.size());
        System.assertEquals(cc[0].Category_Picklist__c, 'Agility');
    }

    public static testmethod void multipleUpdateCategories() {
        Account acc = [SELECT Id FROM Account];

        course__c course = TestDataFactory.createCourse(acc.id);
        course.category__c = 'Agility';
        insert course;

        Test.startTest();
        course.category__c = 'Agility;Innovation';
        update course;
        Test.stopTest();
        
        List<Course_Category__c> cc = [SELECT id,
                                              Category_Picklist__c 
                                                 FROM Course_Category__c 
                                        WHERE Course__c =: course.id];

        System.assertEquals(2, cc.size());
        for (Course_Category__c ccat : cc) {
            System.assert(ccat.Category_Picklist__c == 'Agility' || 
                            ccat.Category_Picklist__c == 'Innovation');
        }
    }

    public static testmethod void testGSTCalculationOnInsert(){
        Account acc = [SELECT Id FROM Account];
        Course__c courseFull = TestDataFactory.createCourse(acc.id);
        courseFull.GST_Code__c = '12';
        courseFull.GST_Mode__c = 'Full';
        courseFull.Non_Member_Fee__c = 1000;
        courseFull.Non_Member_GST_Fee__c = 0;
        courseFull.Member_Fee__c = 2000;
        courseFull.Member_GST_Fee__c = 0;
        courseFull.RMIT_Alumni_Fee__c = 3000;
        courseFull.RMIT_Alumni_GST_Fee__c = 0;

        Course__c courseNett = TestDataFactory.createCourse(acc.id);
        courseNett.Course_Code__c = 'Nett GST';
        courseNett.GST_Code__c = '12';
        courseNett.GST_Mode__c = 'Nett';
        courseNett.Non_Member_Fee__c = 1000;
        courseNett.Non_Member_GST_Fee__c = 0;
        courseNett.Member_Fee__c = 2000;
        courseNett.Member_GST_Fee__c = 0;
        courseNett.RMIT_Alumni_Fee__c = 3000;
        courseNett.RMIT_Alumni_GST_Fee__c = 0;

        Test.startTest();
        insert courseFull;
        insert courseNett;
        Test.stopTest();
        
        Course__c courseFullAfter = [SELECT Non_Member_Fee__c, 
                                            Non_Member_GST_Fee__c, 
                                            Member_Fee__c, 
                                            Member_GST_Fee__c,
                                            RMIT_Alumni_Fee__c,
                                            RMIT_Alumni_GST_Fee__c
                                    FROM Course__c
                                    WHERE Id=:courseFull.Id];
        System.assertEquals(1000, courseFullAfter.Non_Member_Fee__c);
        System.assertEquals(2000, courseFullAfter.Member_Fee__c);
        System.assertEquals(3000, courseFullAfter.RMIT_Alumni_Fee__c);
        System.assertEquals(70, courseFullAfter.Non_Member_GST_Fee__c);
        System.assertEquals(140, courseFullAfter.Member_GST_Fee__c);
        System.assertEquals(210, courseFullAfter.RMIT_Alumni_GST_Fee__c);
        
        Course__c courseNettAfter = [SELECT Non_Member_Fee__c, 
                                            Non_Member_GST_Fee__c, 
                                            Member_Fee__c, 
                                            Member_GST_Fee__c,
                                            RMIT_Alumni_Fee__c,
                                            RMIT_Alumni_GST_Fee__c
                                    FROM Course__c
                                    WHERE Id=:courseNett.Id];
        System.assertEquals(1000, courseFullAfter.Non_Member_Fee__c);
        System.assertEquals(2000, courseFullAfter.Member_Fee__c);
        System.assertEquals(3000, courseFullAfter.RMIT_Alumni_Fee__c);
        //2021-03-15 Poon Koon: Updated Assertion Values for Nett GST calculation
        System.assertEquals(65.42, courseNettAfter.Non_Member_GST_Fee__c);
        System.assertEquals(130.84, courseNettAfter.Member_GST_Fee__c);
        System.assertEquals(196.26, courseNettAfter.RMIT_Alumni_GST_Fee__c);
    }

    public static testmethod void testGSTCalculationOnUpdate(){
        Account acc = [SELECT Id FROM Account];
        Course__c courseFull = TestDataFactory.createCourse(acc.id);
        courseFull.GST_Code__c = '12';
        courseFull.GST_Mode__c = 'Full';
        courseFull.Non_Member_Fee__c = 100;
        courseFull.Non_Member_GST_Fee__c = 0;
        courseFull.Member_Fee__c = 200;
        courseFull.Member_GST_Fee__c = 0;
        courseFull.RMIT_Alumni_Fee__c = 300;
        courseFull.RMIT_Alumni_GST_Fee__c = 0;
        Course__c courseNett = TestDataFactory.createCourse(acc.id);
        courseNett.Course_Code__c = 'Nett GST';
        courseNett.GST_Code__c = '12';
        courseNett.GST_Mode__c = 'Nett';
        courseNett.Non_Member_Fee__c = 100;
        courseNett.Non_Member_GST_Fee__c = 0;
        courseNett.Member_Fee__c = 200;
        courseNett.Member_GST_Fee__c = 0;
        courseNett.RMIT_Alumni_Fee__c = 300;
        courseNett.RMIT_Alumni_GST_Fee__c = 0;
        insert courseFull;
        insert courseNett;

        Test.startTest();
        courseFull.Non_Member_Fee__c = 1000;
        courseFull.Member_Fee__c = 2000;
        courseFull.RMIT_Alumni_Fee__c = 3000;
        courseNett.Non_Member_Fee__c = 1000;
        courseNett.Member_Fee__c = 2000;
        courseNett.RMIT_Alumni_Fee__c = 3000;
        update courseFull;
        update courseNett;
        Test.stopTest();
        
        Course__c courseFullAfter = [SELECT Non_Member_Fee__c, 
                                            Non_Member_GST_Fee__c, 
                                            Member_Fee__c, 
                                            Member_GST_Fee__c,
                                            RMIT_Alumni_Fee__c,
                                            RMIT_Alumni_GST_Fee__c
                                    FROM Course__c
                                    WHERE Id=:courseFull.Id];
        System.assertEquals(1000, courseFullAfter.Non_Member_Fee__c);
        System.assertEquals(2000, courseFullAfter.Member_Fee__c);
        System.assertEquals(3000, courseFullAfter.RMIT_Alumni_Fee__c);
        System.assertEquals(70, courseFullAfter.Non_Member_GST_Fee__c);
        System.assertEquals(140, courseFullAfter.Member_GST_Fee__c);
        System.assertEquals(210, courseFullAfter.RMIT_Alumni_GST_Fee__c);
        
        Course__c courseNettAfter = [SELECT Non_Member_Fee__c, 
                                            Non_Member_GST_Fee__c, 
                                            Member_Fee__c, 
                                            Member_GST_Fee__c,
                                            RMIT_Alumni_Fee__c,
                                            RMIT_Alumni_GST_Fee__c
                                    FROM Course__c
                                    WHERE Id=:courseNett.Id];
        System.assertEquals(1000, courseFullAfter.Non_Member_Fee__c);
        System.assertEquals(2000, courseFullAfter.Member_Fee__c);
        System.assertEquals(3000, courseFullAfter.RMIT_Alumni_Fee__c);
        //2021-03-15 Poon Koon: Updated Assertion Values for Nett GST calculation
        System.assertEquals(65.42, courseNettAfter.Non_Member_GST_Fee__c);
        System.assertEquals(130.84, courseNettAfter.Member_GST_Fee__c);
        System.assertEquals(196.26, courseNettAfter.RMIT_Alumni_GST_Fee__c);
    }


    public static testmethod void generateCourseCode() {
        Test.startTest();
        Course__c course = TestDataFactory.createCourse(null);
        course.category__c = 'Agility';
        course.Course_Code__c = '';
        insert course;
        Test.stopTest();

        Course__c courseAfter = [SELECT Id, Course_Code__c FROM Course__c WHERE Id =: course.Id];

        System.assert(courseAfter.Course_Code__c != '');
    }
}