force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Ensure that the new category is added to the Global Value Set (&quot;Categories&quot;)</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Category__c/fields/Thumbnail_URL__c.field-meta.xml
<CustomField>
    <fullName>Thumbnail_URL__c</fullName>
    <label>Thumbnail URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/ThumbnailURL_ext__c.field-meta.xml
<CustomField>
    <fullName>ThumbnailURL_ext__c</fullName>
    <label>ThumbnailURL Ext</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <displayFormat>Course-{00000}</displayFormat>
        <label>Course Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/AttachmentURL__c.field-meta.xml
<CustomField>
    <fullName>AttachmentURL__c</fullName>
    <label>AttachmentURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/AttachmentURL_Ext__c.field-meta.xml
<CustomField>
    <fullName>AttachmentURL_Ext__c</fullName>
    <label>AttachmentURL Ext</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/ThumbnailURL__c.field-meta.xml
<CustomField>
    <fullName>ThumbnailURL__c</fullName>
    <label>ThumbnailURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/ThumbnailURL_Ext__c.field-meta.xml
<CustomField>
    <fullName>ThumbnailURL_Ext__c</fullName>
    <label>ThumbnailURL Ext</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/recordTypes/Course.recordType-meta.xml
<RecordType>
    <fullName>Course</fullName>
    <active>true</active>
    <description>Public Courses /Courses without SSG Modules/Courses with Skill future credit</description>
    <label>Course</label>
</RecordType>

force-app/main/default/globalValueSets/Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agile At Scale</fullName>
    </customValue>
    <customValue>
        <fullName>Agility</fullName>
    </customValue>
    <customValue>
        <fullName>AI SmokeTest</fullName>
    </customValue>
    <customValue>
        <fullName>Artificial Intelligence</fullName>
    </customValue>
    <customValue>
        <fullName>Business &amp; Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Business Insight</fullName>
    </customValue>
    <customValue>
        <fullName>Category 1</fullName>
    </customValue>
    <customValue>
        <fullName>Change Management</fullName>
    </customValue>
    <customValue>
        <fullName>Communication</fullName>
    </customValue>
    <customValue>
        <fullName>Communication - General</fullName>
    </customValue>
    <customValue>
        <fullName>Communication - Spoken</fullName>
    </customValue>
    <customValue>
        <fullName>Communication - Written</fullName>
    </customValue>
    <customValue>
        <fullName>Complex Adaptive Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Creativity &amp; Innovation</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Service</fullName>
    </customValue>
    <customValue>
        <fullName>CX &amp; UX</fullName>
        <label>CX,UX &amp; UI</label>
    </customValue>
    <customValue>
        <fullName>Data Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Design Thinking</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Practices</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Transformation</fullName>
    </customValue>
    <customValue>
        <fullName>Disruptive Innovation</fullName>
    </customValue>
    <customValue>
        <fullName>Diversity Management</fullName>
    </customValue>
    <customValue>
        <fullName>Employability Skills System</fullName>
    </customValue>
    <customValue>
        <fullName>Events &amp; Conferences</fullName>
    </customValue>
    <customValue>
        <fullName>Evergreen Leadership</fullName>
    </customValue>
    <customValue>
        <fullName>Finance &amp; Legal</fullName>
    </customValue>
    <customValue>
        <fullName>General Management</fullName>
    </customValue>
    <customValue>
        <fullName>HR Development</fullName>
    </customValue>
    <customValue>
        <fullName>HR Management</fullName>
    </customValue>
    <customValue>
        <fullName>HR Management &amp; Development</fullName>
    </customValue>
    <description>Category for Courses</description>
    <masterLabel>Category</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContentVersionTriggerHandler.cls
/**
 * @description       : 
 * @author            : Mark Alvin Tayag (mtayag@salesforce.com)
 * @group             : 
 * @last modified on  : 10-20-2020
 * @last modified by  : Mark Alvin Tayag (mtayag@salesforce.com)
 * Modifications Log 
 * Ver   Date         Author                                     Modification
 * 1.0   10-20-2020   Mark Alvin Tayag (mtayag@salesforce.com)   Initial Version
**/
public without sharing class ContentVersionTriggerHandler {
    public static void afterInsert(list<ContentVersion> contentVersionList) {
        updateThumbnailURL(contentVersionList);
    }

    public static void afterUpdate(list<ContentVersion> contentVersionList) {
        updateThumbnailURL(contentVersionList);
    }
    
    //Add afterUpdate
     public static void updateThumbnailURL(list<ContentVersion> contentVersionList) {
        
        Set<Id> contentDocumentIdSet = new Set<Id>(); 
        Map<Id, Id> cdlMapwithLinkedEntityId = new Map<Id, Id>();
        Set<Id> attachmentDocIds = new Set<Id>();
        Set<Id> thumbnailDocIds = new Set<Id>();
        Map<Id, String> cvExtMap = new Map<Id, String>();
        List<ContentDistribution> cdList = new List<ContentDistribution>();
        List<Category__c> catList = new List<Category__c>();
        List<Course__c> courseList = new List<Course__c>();
        List<Id> cvIds = new List<Id>();

        for(ContentVersion cv : contentVersionList) {
            if(cv.File_Type__c == 'Attachment' &&
                cv.ContentDocumentId != null && 
                cv.IsLatest == true) {
                contentDocumentIdSet.add(cv.ContentDocumentId);
                attachmentDocIds.add(cv.ContentDocumentId);
                cvIds.add(cv.Id);
            }
            else if(cv.File_Type__c == 'Thumbnail' &&
                cv.ContentDocumentId != null && 
                cv.IsLatest == true) {
                contentDocumentIdSet.add(cv.ContentDocumentId);
                thumbnailDocIds.add(cv.ContentDocumentId);
                cvIds.add(cv.Id);
            }
        }
        if(contentDocumentIdSet.size() > 0) {
            List<ContentDocumentLink> cdlList = [SELECT ContentDocumentId,LinkedEntityId FROM ContentDocumentLink 
                                                 WHERE ContentDocumentId IN : contentDocumentIdSet];
            
            for(ContentDocumentLink cdl : cdlList) {
                Id linkedEntityId = cdl.LinkedEntityId;
                //This logic is only applicable for Course and Category 
                if (linkedEntityId.getSobjectType() == Course__c.sObjectType || 
                    linkedEntityId.getSobjectType() == Category__c.sObjectType) {
                    cdlMapwithLinkedEntityId.put(cdl.ContentDocumentId, linkedEntityId);
                }
                
            }          
            
            //Check if there is an existing Content Delivery Record for the Content Version
            Set<Id> contentVersionWithDelivery = new Set<Id>();
            for (ContentDistribution cd : [SELECT ContentVersionId FROM ContentDistribution WHERE ContentVersionId =: cvIds]) {
                contentVersionWithDelivery.add(cd.ContentVersionId);
            }

            for (ContentVersion cv : contentVersionList) {
                if (cdlMapwithLinkedEntityId.containsKey(cv.ContentDocumentId) &&
                    !contentVersionWithDelivery.contains(cv.Id)) {
                    ContentDistribution cd = new ContentDistribution();
                    cd.Name = cv.Id + '-Url';
                    cd.ContentVersionId = cv.id;
                    cd.PreferencesAllowViewInBrowser= true;
                    cd.PreferencesLinkLatestVersion=true;
                    cd.PreferencesNotifyOnVisit=false;
                    cd.PreferencesPasswordRequired=false;
                    cd.PreferencesAllowOriginalDownload= true;
                    cdList.add(cd);
                }
            }
            
            if (cdList.size() > 0) {
                insert cdList;
            }         
            
            //Get the ContentVersion Extension
            for (ContentVersion cv : [SELECT ContentDocumentId, FileExtension FROM ContentVersion WHERE Id =: cvIds]) {
                cvExtMap.put(cv.ContentDocumentId, cv.FileExtension);
                
            }
            
            for (ContentDistribution cd : [select DistributionPublicUrl,ContentDownloadUrl, ContentVersionID, contentDocumentId from ContentDistribution 
                                           where contentDocumentId =: cdlMapwithLinkedEntityId.keySet()]) {
                Id linkedEntityId = cdlMapwithLinkedEntityId.get(cd.contentDocumentId);
                if (linkedEntityId.getSobjectType() == Course__c.sObjectType) {
                    Course__c course = new Course__c();
                    course.Id = linkedEntityId;
                    if (thumbnailDocIds.contains(cd.contentDocumentId)) {
                        //course.ThumbnailURL__c = cd.DistributionPublicUrl;
                        course.ThumbnailURL__c = cd.ContentDownloadUrl;
                        course.ThumbnailURL_Ext__c = cvExtMap.get(cd.contentDocumentId);
                    }
                    else if (attachmentDocIds.contains(cd.contentDocumentId)) {
                        course.AttachmentURL__c = cd.ContentDownloadUrl;
                        //course.AttachmentURL__c = cd.DistributionPublicUrl;
                        course.AttachmentURL_Ext__c = cvExtMap.get(cd.contentDocumentId);
                    }
                    courseList.add(course);
                }
                if (linkedEntityId.getSobjectType() == Category__c.sObjectType && 
                    thumbnailDocIds.contains(cd.contentDocumentId)) {
                    Category__c category = new Category__c();
                    category.Id = linkedEntityId;
                    category.Thumbnail_URL__c = cd.ContentDownloadUrl;
                    //category.Thumbnail_URL__c = cd.DistributionPublicUrl;
                    category.ThumbnailURL_Ext__c = cvExtMap.get(cd.contentDocumentId);
                    catList.add(category);
                }
            }
        }
        if (catList.size() > 0) {
            update catList;
        }
         
        if (courseList.size() > 0) {
            update courseList;
        }
         
     }
}