force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Ensure that the new category is added to the Global Value Set (&quot;Categories&quot;)</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Category__c/fields/Thumbnail_URL__c.field-meta.xml
<CustomField>
    <fullName>Thumbnail_URL__c</fullName>
    <label>Thumbnail URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/ThumbnailURL_ext__c.field-meta.xml
<CustomField>
    <fullName>ThumbnailURL_ext__c</fullName>
    <label>ThumbnailURL Ext</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <displayFormat>Course-{00000}</displayFormat>
        <label>Course Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/AttachmentURL__c.field-meta.xml
<CustomField>
    <fullName>AttachmentURL__c</fullName>
    <label>AttachmentURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/AttachmentURL_Ext__c.field-meta.xml
<CustomField>
    <fullName>AttachmentURL_Ext__c</fullName>
    <label>AttachmentURL Ext</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/ThumbnailURL__c.field-meta.xml
<CustomField>
    <fullName>ThumbnailURL__c</fullName>
    <label>ThumbnailURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/ThumbnailURL_Ext__c.field-meta.xml
<CustomField>
    <fullName>ThumbnailURL_Ext__c</fullName>
    <label>ThumbnailURL Ext</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/recordTypes/Course.recordType-meta.xml
<RecordType>
    <fullName>Course</fullName>
    <active>true</active>
    <description>Public Courses /Courses without SSG Modules/Courses with Skill future credit</description>
    <label>Course</label>
</RecordType>

force-app/main/default/globalValueSets/Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agile At Scale</fullName>
    </customValue>
    <customValue>
        <fullName>Agility</fullName>
    </customValue>
    <customValue>
        <fullName>AI SmokeTest</fullName>
    </customValue>
    <customValue>
        <fullName>Artificial Intelligence</fullName>
    </customValue>
    <customValue>
        <fullName>Business &amp; Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Business Insight</fullName>
    </customValue>
    <customValue>
        <fullName>Category 1</fullName>
    </customValue>
    <customValue>
        <fullName>Change Management</fullName>
    </customValue>
    <customValue>
        <fullName>Communication</fullName>
    </customValue>
    <customValue>
        <fullName>Communication - General</fullName>
    </customValue>
    <customValue>
        <fullName>Communication - Spoken</fullName>
    </customValue>
    <customValue>
        <fullName>Communication - Written</fullName>
    </customValue>
    <customValue>
        <fullName>Complex Adaptive Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Creativity &amp; Innovation</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Service</fullName>
    </customValue>
    <customValue>
        <fullName>CX &amp; UX</fullName>
        <label>CX,UX &amp; UI</label>
    </customValue>
    <customValue>
        <fullName>Data Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Design Thinking</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Practices</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Transformation</fullName>
    </customValue>
    <customValue>
        <fullName>Disruptive Innovation</fullName>
    </customValue>
    <customValue>
        <fullName>Diversity Management</fullName>
    </customValue>
    <customValue>
        <fullName>Employability Skills System</fullName>
    </customValue>
    <customValue>
        <fullName>Events &amp; Conferences</fullName>
    </customValue>
    <customValue>
        <fullName>Evergreen Leadership</fullName>
    </customValue>
    <customValue>
        <fullName>Finance &amp; Legal</fullName>
    </customValue>
    <customValue>
        <fullName>General Management</fullName>
    </customValue>
    <customValue>
        <fullName>HR Development</fullName>
    </customValue>
    <customValue>
        <fullName>HR Management</fullName>
    </customValue>
    <customValue>
        <fullName>HR Management &amp; Development</fullName>
    </customValue>
    <customValue>
        <fullName>Management</fullName>
    </customValue>
    <description>Category for Courses</description>
    <masterLabel>Category</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContentVersionTriggerHandlerTest.cls
@istest
public class ContentVersionTriggerHandlerTest {
    public static testmethod void testThumbnailUpdateonCategory() {     
        List<ContentVersion> cvList = new List<ContentVersion>();
        category__c category = TestDataFactory.createCategory();
        //2021-03-31 Poon Koon: Update Category with valid picklist value
        category.Category__c = 'Management';
        insert category;
        
        contentVersion contentVersionVar = TestDataFactory.createContentVersion();
        insert contentVersionVar; 
        System.assertEquals( contentVersionVar.Title , 'Thumbnail' );               
       
        cvList  = [SELECT Id, Title,PathOnClient,VersionData,File_Type__c,IsMajorVersion,ContentDocumentId,isLatest 
                   FROM ContentVersion WHERE Id = :contentVersionVar.Id];               

        ContentDocumentLink contentDocLink = TestDataFactory.createContentDocumentLink(category.Id,cvList[0].ContentDocumentId);
        insert contentDocLink;
        
        Test.startTest();
        ContentVersionTriggerHandler.updateThumbnailURL(cvList);
        category__c updateCategory = [select id,Thumbnail_URL__c,ThumbnailURL_Ext__c from category__c where id=: category.id];
        System.assertEquals( updateCategory.ThumbnailURL_Ext__c , 'jpg' );               
        Test.stopTest();
    }
    
    public static testmethod void testThumnailUpdateonCourse() {
        List<ContentVersion> cvList = new List<ContentVersion>();
        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('B2B Account').getRecordTypeId();
        Account acc = TestDataFactory.createAccount(devRecordTypeId);
        insert acc;
        
        Course__c course = TestDataFactory.createCourse(acc.Id);
        insert course;       
        
        contentVersion contentVerThumbNail = TestDataFactory.createContentVersion();
        insert contentVerThumbNail;
        System.assertEquals( contentVerThumbNail.Title , 'Thumbnail' );
        
        cvList  = [SELECT Id, Title,PathOnClient,VersionData,IsMajorVersion,File_Type__c,ContentDocumentId,isLatest FROM 
                   ContentVersion WHERE Id =: contentVerThumbNail.id];               
        
        ContentDocumentLink contentDocLinkThumnail = TestDataFactory.createContentDocumentLink(course.Id,cvList[0].ContentDocumentId);
        insert contentDocLinkThumnail;        
       
        Test.startTest();
        ContentVersionTriggerHandler.updateThumbnailURL(cvList);
        Course__c updateCourse = [select id,ThumbnailURL__c,ThumbnailURL_Ext__c from course__c where id=: course.id];
        System.assertEquals( updateCourse.ThumbnailURL_Ext__c , 'jpg' );               
        Test.stopTest();
    }
    
    public static testmethod void testAttachmentUpdateonCourse() {
        List<ContentVersion> cvList = new List<ContentVersion>();
        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('B2B Account').getRecordTypeId();
        Account acc = TestDataFactory.createAccount(devRecordTypeId);
        insert acc;
        
        Course__c course = TestDataFactory.createCourse(acc.Id);
        insert course;        
      
       
        contentVersion contentVerAttachment = TestDataFactory.createContentVersionAttachment();
       // contentVerAttachment.Title = 'Attachment';
       // contentVerAttachment.PathOnClient = 'Attachment.jpg';
        insert contentVerAttachment; 
        System.assertEquals( contentVerAttachment.Title , 'Attachment' );
        
        cvList  = [SELECT Id, Title,PathOnClient,VersionData,IsMajorVersion,ContentDocumentId,isLatest,File_Type__c 
                   FROM ContentVersion WHERE Id =: contentVerAttachment.id];                       
      
        ContentDocumentLink contentDocLinkAttachment = TestDataFactory.createContentDocumentLink(course.Id,cvList[0].ContentDocumentId);
        insert contentDocLinkAttachment;
        
        Test.startTest();
        ContentVersionTriggerHandler.updateThumbnailURL(cvList);
        Course__c updateCourse = [select id,AttachmentURL__c,AttachmentURL_Ext__c from course__c where id=: course.id];
        System.assertEquals( updateCourse.AttachmentURL_Ext__c , 'jpg' );
        Test.stopTest();
    }
    
    
       public static testmethod void testFileUploadCategoryTest() {     
        List<ContentVersion> cvList = new List<ContentVersion>();
        category__c category = TestDataFactory.createCategory();
        //2021-03-31 Poon Koon: Update Category with valid picklist value
        category.Category__c = 'Management';
        insert category;
        
        contentVersion contentVersionVar = TestDataFactory.createContentVersionTest();
        insert contentVersionVar; 
        System.assertEquals( contentVersionVar.Title , 'Test' );               
       
        cvList  = [SELECT Id, Title,PathOnClient,VersionData,IsMajorVersion,ContentDocumentId,isLatest,File_Type__c 
                   FROM ContentVersion WHERE Id = :contentVersionVar.Id];               

        ContentDocumentLink contentDocLink = TestDataFactory.createContentDocumentLink(category.Id,cvList[0].ContentDocumentId);
        insert contentDocLink;
        
        Test.startTest();
        ContentVersionTriggerHandler.updateThumbnailURL(cvList);
        Test.stopTest();
    }
    
      public static testmethod void testFileUploadonCourseTest() {
        List<ContentVersion> cvList = new List<ContentVersion>();
        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('B2B Account').getRecordTypeId();
        Account acc = TestDataFactory.createAccount(devRecordTypeId);
        insert acc;
        
        Course__c course = TestDataFactory.createCourse(acc.Id);
        insert course;        
      
        
        contentVersion contentVerThumbNail = TestDataFactory.createContentVersionTest();
        insert contentVerThumbNail;
        System.assertEquals( contentVerThumbNail.Title , 'Test' );
        
        cvList  = [SELECT Id, Title,PathOnClient,VersionData,IsMajorVersion,ContentDocumentId,isLatest,File_Type__c 
                   FROM ContentVersion WHERE Id =: contentVerThumbNail.id];               
        
        ContentDocumentLink contentDocLinkThumnail = TestDataFactory.createContentDocumentLink(course.Id,cvList[0].ContentDocumentId);
        insert contentDocLinkThumnail;        
       
        Test.startTest();
        ContentVersionTriggerHandler.updateThumbnailURL(cvList);
        Test.stopTest();
    }

   
}