force-app/main/default/objects/Course_Registration__c/Course_Registration__c.object-meta.xml
<CustomObject>
    <label>Course Registration</label>
    <nameField>
        <displayFormat>REG-{0000}</displayFormat>
        <label>Course Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Registrations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Registration__c/fields/Address_Type__c.field-meta.xml
<CustomField>
    <fullName>Address_Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Address_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Attention__c.field-meta.xml
<CustomField>
    <fullName>Attention__c</fullName>
    <label>Attention</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Billing_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address_Line_1__c</fullName>
    <label>Billing Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <label>Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Billing_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Postal_Code__c</fullName>
    <label>Billing Postal Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Registrations</relationshipLabel>
    <relationshipName>Course_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Course_Run_Id__c.field-meta.xml
<CustomField>
    <fullName>Course_Run_Id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course Run</label>
    <referenceTo>Course_Run__c</referenceTo>
    <relationshipLabel>Course Registrations</relationshipLabel>
    <relationshipName>Course_Registrations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Course_Run_Owner_Email__c.field-meta.xml
<CustomField>
    <fullName>Course_Run_Owner_Email__c</fullName>
    <description>MVP1.0 This field stores the Email Address of the Course Run Owner</description>
    <inlineHelpText>This field stores the Email Address of the Course Run Owner</inlineHelpText>
    <label>Course Run Owner (Email)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/IsMember__c.field-meta.xml
<CustomField>
    <fullName>IsMember__c</fullName>
    <defaultValue>false</defaultValue>
    <description>MVP1.0 Please consider this option to avail Membership Prices on the Course Fees</description>
    <inlineHelpText>Please consider this option to avail Membership Prices on the Course Fees</inlineHelpText>
    <label>SIM Society Member?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Marketing_Consent_Clause__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Consent_Clause__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Marketing Consent Clause</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Mobile_No__c</fullName>
    <label>Mobile No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Office_No__c.field-meta.xml
<CustomField>
    <fullName>Office_No__c</fullName>
    <label>Office No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <defaultValue>&quot;Unpaid&quot;</defaultValue>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Invoice Issued</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/PDPA_Consent_Clause__c.field-meta.xml
<CustomField>
    <fullName>PDPA_Consent_Clause__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PDPA Consent Clause</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Preferred_Certificate_Name__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Certificate_Name__c</fullName>
    <label>Preferred Certificate Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Preferred_Contact_Method__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Contact_Method__c</fullName>
    <label>Preferred Contact Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EMAIL</fullName>
                <default>true</default>
                <label>Email</label>
            </value>
            <value>
                <fullName>PHONE</fullName>
                <label>Phone</label>
            </value>
            <value>
                <fullName>FAX</fullName>
                <isActive>false</isActive>
                <label>FAX</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Race</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Registration_Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Residency_Status__c.field-meta.xml
<CustomField>
    <fullName>Residency_Status__c</fullName>
    <inlineHelpText>Refers to type of residency in Singapore</inlineHelpText>
    <label>Residency Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Citizen</fullName>
            </value>
            <value>
                <fullName>Dependent Pass</fullName>
            </value>
            <value>
                <fullName>Employment Pass/Work Permit</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Permanent Resident</fullName>
            </value>
            <value>
                <fullName>Professional Pass</fullName>
            </value>
            <value>
                <fullName>Student Pass</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/RMIT_Alumni__c.field-meta.xml
<CustomField>
    <fullName>RMIT_Alumni__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RMIT Alumni</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr</fullName>
            </value>
            <value>
                <fullName>Ms</fullName>
            </value>
            <value>
                <fullName>Mrs</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Prof.</fullName>
            </value>
            <value>
                <fullName>Mdm</fullName>
            </value>
            <value>
                <fullName>Rev.</fullName>
            </value>
            <value>
                <fullName>Sir Dr.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Send_Survey__c.field-meta.xml
<CustomField>
    <fullName>Send_Survey__c</fullName>
    <defaultValue>false</defaultValue>
    <description>MVP1.0 Please check this Box to initiate a Survey Invitation</description>
    <inlineHelpText>Please check this Box to initiate a Survey Invitation</inlineHelpText>
    <label>Send Survey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Stop_Survey__c.field-meta.xml
<CustomField>
    <fullName>Stop_Survey__c</fullName>
    <defaultValue>false</defaultValue>
    <description>MVP1.0 Check this Box when you want to STOP sending a Survey</description>
    <inlineHelpText>Check this Box when you want to STOP sending a Survey</inlineHelpText>
    <label>Stop Survey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Address_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>HOME</fullName>
        <label>Home</label>
    </customValue>
    <customValue>
        <fullName>OFFICE</fullName>
        <default>true</default>
        <label>Office</label>
    </customValue>
    <masterLabel>Address Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Singapore</fullName>
        <default>true</default>
        <label>Singapore</label>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei Darussalam</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Burkina Faso</fullName>
    </customValue>
    <customValue>
        <fullName>Burundi</fullName>
    </customValue>
    <customValue>
        <fullName>Cambodia</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Nationality.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Singapore_CITIZEN</fullName>
        <default>true</default>
        <label>Singapore CITIZEN</label>
    </customValue>
    <customValue>
        <fullName>Singapore PR</fullName>
    </customValue>
    <customValue>
        <fullName>Afghan</fullName>
    </customValue>
    <customValue>
        <fullName>Albanian</fullName>
    </customValue>
    <customValue>
        <fullName>Algerian</fullName>
    </customValue>
    <customValue>
        <fullName>American</fullName>
    </customValue>
    <customValue>
        <fullName>Andorran</fullName>
    </customValue>
    <customValue>
        <fullName>Angolan</fullName>
    </customValue>
    <customValue>
        <fullName>Anguillan</fullName>
    </customValue>
    <customValue>
        <fullName>Argentine</fullName>
    </customValue>
    <customValue>
        <fullName>Armenian</fullName>
    </customValue>
    <customValue>
        <fullName>Australian</fullName>
    </customValue>
    <customValue>
        <fullName>Austrian</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijani</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamian</fullName>
    </customValue>
    <customValue>
        <fullName>Bahraini</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladeshi</fullName>
    </customValue>
    <customValue>
        <fullName>Barbadian</fullName>
    </customValue>
    <customValue>
        <fullName>Belarusian</fullName>
    </customValue>
    <customValue>
        <fullName>Belgian</fullName>
    </customValue>
    <customValue>
        <fullName>Belizean</fullName>
    </customValue>
    <customValue>
        <fullName>Beninese</fullName>
    </customValue>
    <customValue>
        <fullName>Bermudian</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutanese</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivian</fullName>
    </customValue>
    <customValue>
        <fullName>Botswanan</fullName>
    </customValue>
    <customValue>
        <fullName>Brazilian</fullName>
    </customValue>
    <customValue>
        <fullName>British</fullName>
    </customValue>
    <customValue>
        <fullName>British Virgin Islander</fullName>
    </customValue>
    <customValue>
        <fullName>Bruneian</fullName>
    </customValue>
    <masterLabel>Nationality</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PassSelectedIdsToFlowVFControllerTest.cls
@isTest
public class PassSelectedIdsToFlowVFControllerTest {
	@isTest static void PassSelectedIds() {
        List<Course_Registration__c> accList1 = new List<Course_Registration__c>();
        List<Course_Registration__c> accList  =[Select 
                                                Course_Run_Id__c,
                                                Course_Run_Owner_Email__c,
                                                Registration_Status__c,
                                                Payment_Status__c,
                                                Marketing_Consent_Clause__c,
                                                PDPA_Consent_Clause__c,
                                                Contact__c,
                                                IsMember__c,
                                                RMIT_Alumni__c,
                                                Salutation__c,
                                                First_Name__c,
                                                Email_Address__c,
                                                Last_Name__c,
                                                Job_Title__c,
                                                Preferred_Certificate_Name__c,
                                                Mobile_No__c,
                                                Office_No__c,
                                                Nationality__c,
                                                Race__c,
                                                Residency_Status__c,
                                                Stop_Survey__c,
                                                Send_Survey__c,
                                                Country__c,
                                                Attention__c,
                                                Billing_Address_Line_1__c,
                                                Billing_Country__c,
                                                Billing_Postal_Code__c,
                                                Address_Type__c,
                                                Preferred_Contact_Method__c,
                                                Provider_Status__c,
                                                RecordTypeId
                                               from Course_Registration__c limit 1];
        
        Course_Registration__c cr1 = accList[0].clone();
        List<string> crList = new List<string>();
        crList.add(cr1.Id);
        acclist1.add(cr1);
        insert acclist1;
        
        Test.startTest();
        //Test.setCurrentPage(Page.PassSelectedIdsToFlowVFController);
        ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(acclist1);
        stdSetController.setSelected(acclist1);
        PassSelectedIdsToFlowVFController ext = new PassSelectedIdsToFlowVFController(stdSetController);
        Test.stopTest();
        
        
         
    }
}