force-app/main/default/objects/Course_Registration__c/Course_Registration__c.object-meta.xml
<CustomObject>
    <label>Course Registration</label>
    <nameField>
        <displayFormat>REG-{0000}</displayFormat>
        <label>Course Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Registrations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Course_Registration__c.field-meta.xml
<CustomField>
    <fullName>Course_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Registration</label>
    <referenceTo>Course_Registration__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RECP-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContentDocumentTriggerHandler.cls
public without sharing class ContentDocumentTriggerHandler {
    public static void AllowSharingToCommunity(List<ContentDocumentLink> cdlList) {
        //Allow Sharing for Invoice, Receipt, and Registration
        for (ContentDocumentLink cdl : cdlList) {
            Id linkedEntityId = cdl.LinkedEntityId;
            if (linkedEntityId.getSobjectType() == Invoice__c.getSObjectType() ||
                linkedEntityId.getSobjectType() == Course_Registration__c.getSObjectType() ||
                linkedEntityId.getSobjectType() == Receipt__c.getSObjectType()) {
                cdl.Visibility = 'AllUsers';
                cdl.ShareType = 'V';
            }
        }
    }
}