force-app/main/default/objects/Course_Registration__c/Course_Registration__c.object-meta.xml
<CustomObject>
    <label>Course Registration</label>
    <nameField>
        <displayFormat>REG-{0000}</displayFormat>
        <label>Course Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Registrations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Registration__c/fields/Alternative_Attention__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Attention__c</fullName>
    <label>Attention</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Alternative_Billing_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Billing_Line_1__c</fullName>
    <label>Billing Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Alternative_Billing_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Billing_Line_2__c</fullName>
    <label>Billing Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Alternative_Billing_Line_3__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Billing_Line_3__c</fullName>
    <label>Billing Address Line 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Alternative_City__c.field-meta.xml
<CustomField>
    <fullName>Alternative_City__c</fullName>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Alternative_Country__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Alternative_Email__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Alternative_Phone__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Phone__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Alternative_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Alternative_State__c.field-meta.xml
<CustomField>
    <fullName>Alternative_State__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Attention__c.field-meta.xml
<CustomField>
    <fullName>Attention__c</fullName>
    <label>Attention</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Billing_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address_Line_1__c</fullName>
    <label>Billing Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Billing_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address_Line_2__c</fullName>
    <label>Billing Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Billing_Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address_Line_3__c</fullName>
    <label>Billing Address Line 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <label>Billing City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <label>Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Billing_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Postal_Code__c</fullName>
    <label>Billing Postal Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_State__c</fullName>
    <label>Billing State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Registrations</relationshipLabel>
    <relationshipName>Course_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <label>Designation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural and Fishery Workers</fullName>
            </value>
            <value>
                <fullName>Associate Professionals and Technicians</fullName>
            </value>
            <value>
                <fullName>Cleaners, Labourers and Related Workers</fullName>
            </value>
            <value>
                <fullName>Clerical Workers</fullName>
            </value>
            <value>
                <fullName>Legislators, Senior Officials and Managers</fullName>
            </value>
            <value>
                <fullName>Plan and Machine Operators and Assemblers</fullName>
            </value>
            <value>
                <fullName>Production Craftsmen &amp; Related Workers</fullName>
            </value>
            <value>
                <fullName>Professionals</fullName>
            </value>
            <value>
                <fullName>Service Workers and Shop and Market Sales Workers</fullName>
            </value>
            <value>
                <fullName>Workers not classifed by Occupation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Designation_Level__c.field-meta.xml
<CustomField>
    <fullName>Designation_Level__c</fullName>
    <label>Designation Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Top Management</fullName>
            </value>
            <value>
                <fullName>Senior Management</fullName>
            </value>
            <value>
                <fullName>Middle Management</fullName>
            </value>
            <value>
                <fullName>Junior Management</fullName>
            </value>
            <value>
                <fullName>Non-Managerial Professional/ Technical Executive</fullName>
            </value>
            <value>
                <fullName>Non-Executive Staff</fullName>
            </value>
            <value>
                <fullName>Sole Proprietor</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Education_Level__c.field-meta.xml
<CustomField>
    <fullName>Education_Level__c</fullName>
    <label>Education Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Education_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Employment_Status__c.field-meta.xml
<CustomField>
    <fullName>Employment_Status__c</fullName>
    <label>Employment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Employed</fullName>
            </value>
            <value>
                <fullName>Unemployed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Home_No__c.field-meta.xml
<CustomField>
    <fullName>Home_No__c</fullName>
    <label>Home No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Mobile_No__c</fullName>
    <label>Mobile No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Monthly_Basic_Salary__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Basic_Salary__c</fullName>
    <label>Monthly Basic Salary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Below $1000</fullName>
            </value>
            <value>
                <fullName>$1,000 - $1,499</fullName>
            </value>
            <value>
                <fullName>$1,500 - $1,900</fullName>
            </value>
            <value>
                <fullName>$1,901 - $2,000</fullName>
            </value>
            <value>
                <fullName>$2,001 - $2,499</fullName>
            </value>
            <value>
                <fullName>$2,500 - $2,999</fullName>
            </value>
            <value>
                <fullName>$3,000 - $3,499</fullName>
            </value>
            <value>
                <fullName>$3,500 and Above</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/NRIC__c.field-meta.xml
<CustomField>
    <fullName>NRIC__c</fullName>
    <label>Identification Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/NRIC_Type__c.field-meta.xml
<CustomField>
    <fullName>NRIC_Type__c</fullName>
    <label>Identification Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Singapore Citizen/PR</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Office_No__c.field-meta.xml
<CustomField>
    <fullName>Office_No__c</fullName>
    <label>Office No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/P_O_Number__c.field-meta.xml
<CustomField>
    <fullName>P_O_Number__c</fullName>
    <label>P.O Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Parent_Registration__c.field-meta.xml
<CustomField>
    <fullName>Parent_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Registration</label>
    <referenceTo>Course_Registration__c</referenceTo>
    <relationshipLabel>Course Registrations</relationshipLabel>
    <relationshipName>Course_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Persons_with_Disabilities__c.field-meta.xml
<CustomField>
    <fullName>Persons_with_Disabilities__c</fullName>
    <label>Persons with Disabilities</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Registration__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr</fullName>
            </value>
            <value>
                <fullName>Ms</fullName>
            </value>
            <value>
                <fullName>Mrs</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Prof.</fullName>
            </value>
            <value>
                <fullName>Mdm</fullName>
            </value>
            <value>
                <fullName>Rev.</fullName>
            </value>
            <value>
                <fullName>Sir Dr.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NRIC_Details__mdt/NRIC_Details__mdt.object-meta.xml
<CustomObject>
    <label>NRIC Detail</label>
    <pluralLabel>NRIC Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/NRIC_Details__mdt/fields/Alphabet__c.field-meta.xml
<CustomField>
    <fullName>Alphabet__c</fullName>
    <label>Alphabet</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NRIC_Details__mdt/fields/Check_Digit__c.field-meta.xml
<CustomField>
    <fullName>Check_Digit__c</fullName>
    <label>Check Digit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NRIC_Details__mdt/fields/Initial_Letter__c.field-meta.xml
<CustomField>
    <fullName>Initial_Letter__c</fullName>
    <label>Initial Letter</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Singapore</fullName>
        <default>true</default>
        <label>Singapore</label>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei Darussalam</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Burkina Faso</fullName>
    </customValue>
    <customValue>
        <fullName>Burundi</fullName>
    </customValue>
    <customValue>
        <fullName>Cambodia</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Education_Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>No Formal Qualification &amp; Lower Primary</fullName>
    </customValue>
    <customValue>
        <fullName>Primary PSLE</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Lower Secondary</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;N&quot; Level or equivalent</fullName>
    </customValue>
    <customValue>
        <fullName>&quot;O&quot; Level or equivalent</fullName>
    </customValue>
    <customValue>
        <fullName>ITE Skills Certification (ISC)</fullName>
    </customValue>
    <customValue>
        <fullName>A Level or equivalent</fullName>
    </customValue>
    <customValue>
        <fullName>NITEC/Post Nitec</fullName>
    </customValue>
    <customValue>
        <fullName>Higher NITEC</fullName>
    </customValue>
    <customValue>
        <fullName>Master NITEC</fullName>
    </customValue>
    <customValue>
        <fullName>WSQ Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>WSQ Higher Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>Polytechnic Diploma</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Qualification &amp; Other Diploma</fullName>
    </customValue>
    <customValue>
        <fullName>WSQ Advance Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>WSQ Diploma</fullName>
    </customValue>
    <customValue>
        <fullName>WSQ Special Diploma</fullName>
    </customValue>
    <customValue>
        <fullName>University First Degree</fullName>
    </customValue>
    <customValue>
        <fullName>University Post-graduate Diploma &amp; Degree/Master/Doctorate</fullName>
    </customValue>
    <customValue>
        <fullName>WSQ Graduate Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>WSQ Graduate Diploma</fullName>
    </customValue>
    <customValue>
        <fullName>Not Reported</fullName>
    </customValue>
    <masterLabel>Education Level</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Nationality.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Singapore_CITIZEN</fullName>
        <default>true</default>
        <label>Singapore CITIZEN</label>
    </customValue>
    <customValue>
        <fullName>Singapore PR</fullName>
    </customValue>
    <customValue>
        <fullName>Afghan</fullName>
    </customValue>
    <customValue>
        <fullName>Albanian</fullName>
    </customValue>
    <customValue>
        <fullName>Algerian</fullName>
    </customValue>
    <customValue>
        <fullName>American</fullName>
    </customValue>
    <customValue>
        <fullName>Andorran</fullName>
    </customValue>
    <customValue>
        <fullName>Angolan</fullName>
    </customValue>
    <customValue>
        <fullName>Anguillan</fullName>
    </customValue>
    <customValue>
        <fullName>Argentine</fullName>
    </customValue>
    <customValue>
        <fullName>Armenian</fullName>
    </customValue>
    <customValue>
        <fullName>Australian</fullName>
    </customValue>
    <customValue>
        <fullName>Austrian</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijani</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamian</fullName>
    </customValue>
    <customValue>
        <fullName>Bahraini</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladeshi</fullName>
    </customValue>
    <customValue>
        <fullName>Barbadian</fullName>
    </customValue>
    <customValue>
        <fullName>Belarusian</fullName>
    </customValue>
    <customValue>
        <fullName>Belgian</fullName>
    </customValue>
    <customValue>
        <fullName>Belizean</fullName>
    </customValue>
    <customValue>
        <fullName>Beninese</fullName>
    </customValue>
    <customValue>
        <fullName>Bermudian</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutanese</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivian</fullName>
    </customValue>
    <customValue>
        <fullName>Botswanan</fullName>
    </customValue>
    <customValue>
        <fullName>Brazilian</fullName>
    </customValue>
    <customValue>
        <fullName>British</fullName>
    </customValue>
    <customValue>
        <fullName>British Virgin Islander</fullName>
    </customValue>
    <customValue>
        <fullName>Bruneian</fullName>
    </customValue>
    <masterLabel>Nationality</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CourseRegistrationTriggerHandler.cls
public class CourseRegistrationTriggerHandler {
    
    public static void CourseRegistrationMethod(list<Course_Registration__c> newCourse){
        Map<Decimal,string> nricMap = returnNRICGrid();
        Map<Decimal,string> nricMapone = returnNRICGrid_F();
        
        for(Course_Registration__c cr:newCourse)
        {
            if(cr.NRIC_Type__c == 'Singapore Citizen/PR' || cr.NRIC_Type__c == 'FIN') {
                string nric = cr.NRIC__c;
                if(String.isNotBlank(nric)) {
                    if(nric.length() != 9) {
                        cr.NRIC__c.addError('Invalid NRIC');
                    }
                    else if(validateNRIC(nric) == true && 
                            (nric.substring(0,1)=='S'||nric.substring(0,1)=='T'||nric.substring(0,1)=='F'||nric.substring(0,1)=='G')){
                                Integer nricsum = 2*Integer.valueOf(nric.substring(1,2)) +
                                    7*Integer.valueOf(nric.substring(2, 3)) +
                                    6*Integer.valueOf(nric.substring(3, 4)) +
                                    5*Integer.valueOf(nric.substring(4, 5)) +
                                    4*Integer.valueOf(nric.substring(5,6)) +
                                    3*Integer.valueOf(nric.substring(6, 7)) +
                                    2*Integer.valueOf(nric.substring(7, 8));       
                                if(nric.substring(0,1) == 'S') {
                                    Integer nricremainder = Math.mod(nricsum , 11);   
                                    if(nricMap.containskey(nricremainder) &&  nricMap.get(nricremainder)!= null &&
                                       nricMap.get(nricremainder) != nric.substring(8, 9)) {
                                           cr.NRIC__c.addError('NRIC/FIN is not valid ');
                                       }
                                }
                                if(nric.substring(0,1) == 'T') {
                                    Integer nricremainder = Math.mod(nricsum+4, 11);               
                                    if(nricMap.containskey(nricremainder) &&  nricMap.get(nricremainder)!= null &&
                                       nricMap.get(nricremainder) != nric.substring(8, 9)) {
                                           cr.NRIC__c.addError('NRIC/FIN is not valid ');
                                       }
                                }
                                if(nric.substring(0,1) == 'F') {
                                    Integer nricremainder=Math.mod(nricsum , 11);               
                                    if(nricMapone.containskey(nricremainder) &&  nricMapone.get(nricremainder)!= null &&
                                       nricMapone.get(nricremainder) != nric.substring(8, 9)) {
                                           cr.NRIC__c.addError('NRIC/FIN is not valid ');
                                       }
                                }
                                if(nric.substring(0,1)=='G'){
                                    Integer nricremainder=Math.mod(nricsum+4, 11);               
                                    if(nricMapone.containskey(nricremainder) &&  nricMapone.get(nricremainder)!= null &&
                                       nricMapone.get(nricremainder) != nric.substring(8, 9)) {
                                           cr.NRIC__c.addError('NRIC/FIN is not valid ');
                                       }
                                }       
                            }
                }
            }}}
    
    public static Map<Decimal,string> returnNRICGrid() {
        Map<Decimal,string> nricMap = new map<Decimal,string>();
        for(NRIC_Details__mdt nr : [select Check_Digit__c,Alphabet__c from NRIC_Details__mdt where Initial_Letter__c=:'S']) {
            nricMap.put(nr.Check_Digit__c,nr.Alphabet__c);
        }
        return nricMap;
    }
    public static Map<Decimal,string> returnNRICGrid_F() {   
        Map<Decimal,string> nricMap = new map<Decimal,string>();   
        for(NRIC_Details__mdt nr : [select Check_Digit__c,Alphabet__c from NRIC_Details__mdt where Initial_Letter__c=:'F']) {
            nricMap.put(nr.Check_Digit__c,nr.Alphabet__c);
        }
        return nricMap;
    }
    
    public static boolean validateNRIC(string nricVal) {
        Boolean result = false;
        String nricRegex = '[S F T G][0-9]{7}[A-Z]';
        Pattern nricPattern = Pattern.compile(nricRegex);
        Matcher nricMatcher = nricPattern.matcher(nricVal);
        if(nricMatcher.matches()) {
            result = true;
        }
        return result;
        
    }
    
    public static void createB2BUser(list<Course_Registration__c> courseList) { 
        Map<id,course_registration__c> contactWithRegIdMap = new Map<id,course_registration__c>();
        set<String> regWithEmailSet = new set<String>();
        Map<string,id> contactEmailMap = new Map<String,id>();
        Map<id,contact> contactMapToUpdate = new Map<id,contact>();
        set<id> parentContactSet = new set<id>();
        Map<String,contact> contactMapToInsert = new Map<string,contact>();     
        List<course_registration__c> courseRegListToUpdate = new list<course_registration__c>();
        Map<id,course_registration__c> accountIdMap = new Map<id,course_registration__c>();
        List<account> accountListToUpdate = new List<account>();
        set<id> parentIds = new set<id>();
        Map<id,id> parentRegistrationMap = new Map<id,id>();
        Map<id,id> userMap = new Map<id,id>();
        
        for(Course_Registration__c cr : courseList) {
            if(cr.contact__c != null) {
                contactWithRegIdMap.put(cr.contact__c, cr);
                accountIdMap.put(cr.contact__r.accountid,cr);
            } else if(cr.Email_Address__c != null && cr.contact__c == null) {
                regWithEmailSet.add(cr.Email_Address__c);
            } 
            
            if(cr.Parent_Registration__c != null && cr.contact__c == null ) {
                parentIds.add(cr.Parent_Registration__c);
                
            }
        }      
        
        for(contact con : [select id,email from contact where email in : regWithEmailSet]) {
            contactEmailMap.put(con.email, con.id);
        }
        
        if(parentIds.size() > 0) {
            for(course_registration__c crParent : [select id,contact__c,parent_registration__c from course_registration__c 
                                                   where id in : parentIds]) {
                                                       parentContactSet.add(crParent.contact__c);
                                                       parentRegistrationMap.put(crParent.id,crParent.contact__c);
                                                   }
            
            Map<id,contact> parentContactMap = new Map<id,Contact>([select id,accountid,email from contact where id in : parentContactSet]);                   
            
            
            for(Course_Registration__c cReg : courseList) {
                set<string> emailSet = new set<string>();
                if(cReg.Parent_Registration__c != null && cReg.contact__c == null && 
                   !contactEmailMap.containskey(cReg.Email_Address__c) && 
                   !emailSet.contains(cReg.Email_Address__c)) {
                       contact con = new contact();
                       con.firstname = cReg.first_name__c;
                       con.lastname = cReg.last_name__c;
                       con.email = cReg.email_address__c;
                       con.Salutation = cReg.Salutation__c;
                       
                       if(parentRegistrationMap.containskey(cReg.parent_registration__c) && 
                          parentRegistrationMap.get(cReg.parent_registration__c) != null &&
                          parentContactMap.containskey(parentRegistrationMap.get(cReg.parent_registration__c)) && 
                          parentContactMap.get(parentRegistrationMap.get(cReg.parent_registration__c)).accountid != null) {
                              con.accountid = parentContactMap.get(parentRegistrationMap.get(cReg.parent_registration__c)).accountid;
                          } 
                       emailSet.add(cReg.email_address__c);
                       contactMapToInsert.put(con.email,con);  
                   }
            }
            
            if(contactMapToInsert.size() > 0 ) {
                insert contactMapToInsert.values();  
                for(contact c :contactMapToInsert.values()) {
                    contactEmailMap.put(c.email,c.id);
                }
            }
            
        }
        
        for(user u :[select id,contactid from user where contactid in : parentContactSet OR contactid in : contactEmailMap.values()]) {
            userMap.put(u.contactid,u.id);
        }
        // Poon Koon 3/2/2021: Added in consent fields during query
        // Poon Koon 2021-04-22: Added in marketing channel field during query
        for(Course_Registration__c crReg : [select id,contact__c,contact__r.accountid,email_address__c,attention__c,Alternative_Attention__c,
                                            Alternative_Billing_Line_1__c,Alternative_Billing_Line_2__c,Alternative_Billing_Line_3__c,
                                            Alternative_City__c,Alternative_Country__c,Alternative_Email__c,Alternative_Phone__c,
                                            Alternative_Postal_Code__c,Alternative_State__c,Billing_Address_Line_1__c,
                                            Billing_Address_Line_3__c, Billing_Address_Line_2__c,Billing_City__c,Billing_Country__c,
                                            Billing_Postal_Code__c,Billing_State__c,Date_of_Birth__c,Designation_Level__c,Designation__c,
                                            Education_Level__c,Employment_Status__c,First_Name__c,Gender__c,Last_Name__c,
                                            Mobile_No__c,Monthly_Basic_Salary__c,NRIC_Type__c,NRIC__c,Nationality__c,Office_No__c,P_O_Number__c,
                                            Persons_with_Disabilities__c,Home_No__c,Preferred_Certificate_Name__c,Primary_Email_Address__c,
                                            RMIT_Alumni__c,Race__c,Remarks__c,Residency_Status__c,Salutation__c,Secondary_Email_Address__c,
                                            Secondary_Mobile__c,Secondary_Salutation__c,job_title__c,Address_Type__c,ownerid,How_did_you_get_to_know_us__c,
                                            Sync_Learner_s_Record__c, Preferred_Contact_Method__c, Marketing_Consent_Clause__c, PDPA_Consent_Clause__c,
                                            Marketing_Channel_Email__c, Marketing_Channel_Post__c, Marketing_Channel_Telephone_call__c, Marketing_Channel_Text_Messages__c
                                            from Course_Registration__c
                                            where id in : courseList]) {
                                                if(contactEmailMap.containskey(crReg.email_address__c)) {
                                                    crReg.contact__c = contactEmailMap.get(crReg.email_address__c);                    
                                                } 
                                                if(userMap.containskey(crReg.contact__c) && userMap.get(crReg.contact__c) != null) {  
                                                    crReg.ownerid = userMap.get(crReg.contact__c);
                                                }
                                                courseRegListToUpdate.add(crReg);
                                                contactWithRegIdMap.put(crReg.contact__c, crReg);
                                                accountIdMap.put(crReg.contact__r.accountid,crReg);     
                                            }
        
        if(courseRegListToUpdate.size() > 0 ) {
            update courseRegListToUpdate;
        }         
        
        for(contact conRec : [select id,Alternative_Attention__c,Alternative_Billing_Address1__c,Alternative_Billing_Address2__c,
                              Alternative_Billing_Address3__c,Alternative_City__c,Alternative_Country__c,Alternative_Email__c,
                              Alternative_Phone__c,Alternative_PostalCode__c,Alternative_State__c,Attention__c,Billing_Address_Line_1__c,
                              Billing_Address_Line_2__c,Billing_Address_Line_3__c,Billing_City__c,Billing_Country__c,Billing_Postal_Code__c,
                              Billing_State__c,Date_of_Birth__c,Designation_Level__c,Designation__c,Education_Level__c,Email,Employment_Status__c,
                              FirstName,Gender__c,LastName,MobilePhone,Monthly_Basic_Salary__c,NRIC_Type__c,NRIC__c,Nationality__c,Office_No__c,
                              P_O_Number__c,Persons_with_Disabilities__c,Phone,Preferred_Certificate_Name__c,Primary_Email_Address__c,RMIT_Alumni__c,
                              Race__c,Remarks__c,Residency_Status__c,Salutation,Secondary_Email_Address__c,Secondary_Mobile_Number__c,
                              Secondary_Salutation__c,Title, How_did_you_get_to_know_us__c from contact where id in : contactWithRegIdMap.keyset()]) {
                                  if(contactWithRegIdMap.get(conRec.id).Sync_Learner_s_Record__c == true) {               
                                      conRec = updateContactFields(conRec,contactWithRegIdMap.get(conRec.id));
                                      contactMapToUpdate.put(conRec.id,conRec);
                                  }
                                  
                              } 
        
        if(contactMapToUpdate.size() > 0) {
            update contactMapToUpdate.values();
        }
        
        for(Account acc :[select id,Address_Type__c,Billing_Address_Line_1__c,Billing_Address_Line_2__c,Billing_Address_Line_3__c,
                          Billing_City__c,Billing_Contact_Person__c,Billing_Country__c,Billing_Postal_Code__c,Billing_State__c,
                          Preferred_Contact_Method__c,ispersonAccount from account where id in : accountIdMap.keyset()]) {
                              if(accountIdMap.get(acc.id).Sync_Learner_s_Record__c == true) {
                                  if(acc.ispersonAccount == true) {
                                      acc.Billing_Contact_Person__c = accountIdMap.get(acc.id).attention__c;
                                      acc.Address_Type__c = accountIdMap.get(acc.id).Address_Type__c;
                                      acc.Billing_Address_Line_1__c = accountIdMap.get(acc.id).Billing_Address_Line_1__c;
                                      acc.Billing_Address_Line_2__c = accountIdMap.get(acc.id).Billing_Address_Line_2__c;
                                      acc.Billing_Address_Line_3__c = accountIdMap.get(acc.id).Billing_Address_Line_3__c;
                                      acc.Billing_City__c = accountIdMap.get(acc.id).Billing_City__c;
                                      acc.Billing_Country__c = accountIdMap.get(acc.id).Billing_Country__c;
                                      acc.Billing_Postal_Code__c = accountIdMap.get(acc.id).Billing_Postal_Code__c;
                                      acc.Billing_State__c = accountIdMap.get(acc.id).Billing_State__c;
                                      acc.Preferred_Contact_Method__c = accountIdMap.get(acc.id).Preferred_Contact_Method__c;
                                  } else {
                                      acc.Billing_Contact_Person__c = accountIdMap.get(acc.id).attention__c;
                                  }
                                  accountListToUpdate.add(acc);  
                              }           
                          }
        
        if(accountListToUpdate.size() > 0) {
            update accountListToUpdate;
        }
    }
    
    public static contact updateContactFields(contact contactRec,course_registration__c courseReg) {
        contact con = contactRec;
        con.Alternative_Attention__c =  courseReg.Alternative_Attention__c;
        con.Alternative_Billing_Address1__c = courseReg.Alternative_Billing_Line_1__c;
        con.Alternative_Billing_Address2__c = courseReg.Alternative_Billing_Line_2__c;
        con.Alternative_Billing_Address3__c = courseReg.Alternative_Billing_Line_3__c;
        con.Alternative_City__c = courseReg.Alternative_City__c;
        con.Alternative_Country__c = courseReg.Alternative_Country__c;
        con.Alternative_Email__c = courseReg.Alternative_Email__c;
        con.Alternative_Phone__c = courseReg.Alternative_Phone__c;
        con.Alternative_PostalCode__c = courseReg.Alternative_Postal_Code__c;
        con.Alternative_State__c = courseReg.Alternative_State__c;
        con.Attention__c = courseReg.Attention__c;      
        con.Billing_Address_Line_1__c = courseReg.Billing_Address_Line_1__c;
        con.Billing_Address_Line_2__c = courseReg.Billing_Address_Line_2__c;
        con.Billing_Address_Line_3__c = courseReg.Billing_Address_Line_3__c;
        con.Billing_City__c = courseReg.Billing_City__c;
        con.Billing_Country__c = courseReg.Billing_Country__c;
        con.Billing_Postal_Code__c = courseReg.Billing_Postal_Code__c;
        con.Billing_State__c = courseReg.Billing_State__c;
        con.Date_of_Birth__c = courseReg.Date_of_Birth__c;
        con.Designation_Level__c = courseReg.Designation_Level__c;
        con.Designation__c = courseReg.Designation__c;
        con.Education_Level__c = courseReg.Education_Level__c;
        con.Email = courseReg.Email_address__c;
        con.Employment_Status__c = courseReg.Employment_Status__c;
        con.FirstName = courseReg.First_Name__c;
        con.Gender__c = courseReg.Gender__c;
        con.LastName = courseReg.Last_Name__c;
        con.MobilePhone = courseReg.Mobile_No__c;
        con.Monthly_Basic_Salary__c = courseReg.Monthly_Basic_Salary__c;
        con.NRIC_Type__c = courseReg.NRIC_Type__c;
        con.NRIC__c = courseReg.NRIC__c;
        con.Nationality__c = courseReg.Nationality__c;
        con.Office_No__c = courseReg.Office_No__c;
        con.P_O_Number__c = courseReg.P_O_Number__c;
        con.Persons_with_Disabilities__c = courseReg.Persons_with_Disabilities__c;
        con.Phone = courseReg.Home_No__c;
        con.Preferred_Certificate_Name__c = courseReg.Preferred_Certificate_Name__c;
        con.Primary_Email_Address__c = courseReg.Primary_Email_Address__c;
        con.RMIT_Alumni__c = courseReg.RMIT_Alumni__c;
        con.Race__c = courseReg.Race__c;
        con.Remarks__c = courseReg.Remarks__c;
        con.Residency_Status__c = courseReg.Residency_Status__c;
        con.Salutation = courseReg.Salutation__c;
        con.Secondary_Email_Address__c = courseReg.Secondary_Email_Address__c;
        con.Secondary_Mobile_Number__c = courseReg.Secondary_Mobile__c;
        con.Secondary_Salutation__c = courseReg.Secondary_Salutation__c;
        con.Title = courseReg.job_title__c;
        con.How_did_you_get_to_know_us__c = courseReg.How_did_you_get_to_know_us__c;
        // Poon Koon 3/2/2021: Sync consent fields
        con.Marketing_Consent_Clause__c = courseReg.Marketing_Consent_Clause__c;
        con.How_did_you_get_to_know_us__c = courseReg.How_did_you_get_to_know_us__c;
        con.PDPA_Consent_Clause__c = courseReg.PDPA_Consent_Clause__c;   
        // Poon Koon 2021-04-22: Sync marketing channel fields
        con.Marketing_Channel_Email__c = courseReg.Marketing_Channel_Email__c;
        con.Marketing_Channel_Post__c = courseReg.Marketing_Channel_Post__c;
        con.Marketing_Channel_Telephone_call__c = courseReg.Marketing_Channel_Telephone_call__c;
        con.Marketing_Channel_Text_Messages__c = courseReg.Marketing_Channel_Text_Messages__c;
        return con;
    }
    
    
}