force-app/main/default/objects/Course_Registration__c/Course_Registration__c.object-meta.xml
<CustomObject>
    <label>Course Registration</label>
    <nameField>
        <displayFormat>REG-{0000}</displayFormat>
        <label>Course Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Registrations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Registrations</relationshipLabel>
    <relationshipName>Course_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <summarizedField>Invoice_Line_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Course_Registration__c.field-meta.xml
<CustomField>
    <fullName>Course_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Registration</label>
    <referenceTo>Course_Registration__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <label>GST Amount</label>
    <summarizedField>Invoice_Line_Item__c.GST_Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoice_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY-{000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/AuthResp__c.field-meta.xml
<CustomField>
    <fullName>AuthResp__c</fullName>
    <label>AuthResp</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Course_Registration__c.field-meta.xml
<CustomField>
    <fullName>Course_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Registration</label>
    <referenceTo>Course_Registration__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Receipt_Created__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked once the receipt has been created for a successful payment</description>
    <label>Receipt Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <formula>If(AuthResp__c=&apos;OK&apos;,&apos;Success&apos;,
If(ISBLANK(AuthResp__c),&apos;Pending&apos;,&apos;Failure&apos;))</formula>
    <label>Transaction Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RECP-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Invoice_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Invoice Generation - In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Unpaid</fullName>
    </customValue>
    <customValue>
        <fullName>Partial</fullName>
    </customValue>
    <customValue>
        <fullName>Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled - Credit Note</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled - Debit Note</fullName>
    </customValue>
    <customValue>
        <fullName>Refunded</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Invoice Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PaymentControllerTest.cls
/*************************************************************************************************************
 * @name            PaymentControllerTest
 * @author          BLR\rohit.pal <rohit.pal@crmit.com>
 * @created         09 / 10 / 2020
 * @description     Test Class for PaymentController
 * 
 * Changes (version)
 * -----------------------------------------------------------------------------------------------------------
 *              No.     Date            Author                  Description
 *              ----    ------------    --------------------    ----------------------------------------------
 * @version     1.0     2020-10-09      BLR\rohit.pal           Changes desription
 *              1.1     2020-10-31      Alvin Tayag             Removed runAs due to it being redundant by running as the same user, added Asserts and renamed method names
 *              1.2     2020-02-01      Poon Koon               Added in new test method for getting course info and payment options
**************************************************************************************************************/
@isTest(seeAllData=false isParallel = false)
private class PaymentControllerTest {
    /**
    * @description 
    * @author Rohit Pal | 10-09-2020 
    **/
    @testSetup
    static void setupTestData() {
        User thisUser = [SELECT FirstName, LastName, Email FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(thisUser) {
            Invoice__c objInvoice= TestDataFactory.createInvoice();
            objInvoice.Status__c = 'Draft';
            insert objInvoice;
            Payment__c objPayment = TestDataFactory.createPayment();
            objPayment.Transaction_Date__c = system.today();
            objPayment.AuthResp__c = 'OK';
            objPayment.Receipt_Created__c = false;
            insert objPayment;
        }
    }
    /**
    * @description : 
    * @author Rohit Pal | 10-09-2020 
    * @return void 
    **/
    static testMethod void getInvoiceInformation(){
        Test.startTest();
        Invoice__c objInvoice = [SELECT Id,
                    Name,
                    Amount__c,
                    GST_Amount__c,
                    Course_Registration__c 
            FROM Invoice__c WHERE Status__c = 'Draft' limit 1];
        PaymentController.getPaymentGateway();
        PaymentController.getInvoiceRecordInformation(objInvoice.Id);
        Test.stopTest();
    } 

    //
    /**
    * @description : 
    * @author Rohit Pal | 10-09-2020 
    * @return void 
    **/
    static testMethod void createReceiptOnSuccessfulPayment(){
        Test.startTest();
        Payment__c objPayment = [SELECT Id,
                                        Name,
                                        Invoice__c,
                                        Transaction_Status__c
                                FROM Payment__c WHERE Transaction_Date__c =: system.today() limit 1];
        List<String> result = PaymentController.handlePayment(objPayment.Id);
        PaymentController.getPaymentGateway();
        Test.stopTest();

        System.assertEquals('Success', result[0]);        

        List<Receipt__c> receipts = [SELECT Id FROM Receipt__c WHERE Payment__c =: objPayment.Id];
        System.assertEquals(1, receipts.size());
    } 
     /**
    * @description : 
    * @author Rohit Pal | 10-09-2020 
    * @return void 
    **/
    static testMethod void doNotReceiptOnSuccessfulPaymentWithReceipt(){
        Test.startTest();
        Payment__c objPayment = [SELECT Id,
                                        Name,
                                        Invoice__c,
                                        Transaction_Status__c,
                                        Receipt_Created__c,
                                        AuthResp__c
                                FROM Payment__c WHERE Transaction_Date__c =: system.today() limit 1];
        objPayment.Receipt_Created__c = True;
        update objPayment;
        List<String> result = PaymentController.handlePayment(objPayment.Id);
        PaymentController.getPaymentGateway();
        Test.stopTest();

        System.assertEquals('Success', result[0]);

        List<Receipt__c> receipts = [SELECT Id FROM Receipt__c WHERE Payment__c =: objPayment.Id];
        System.assertEquals(0, receipts.size());
    } 
    /**
    * @description : 
    * @author Rohit Pal | 10-09-2020 
    * @return void 
    **/
    static testMethod void doNotCreateReceiptOnUnsuccessfulPayment() {
        Test.startTest();
        Payment__c objPayment = [SELECT Id,
                                        Name,
                                        Invoice__c,
                                        Transaction_Status__c,
                                        Receipt_Created__c,
                                        AuthResp__c
                                FROM Payment__c WHERE Transaction_Date__c =: system.today() limit 1];
        objPayment.AuthResp__c = 'Pending';
        update objPayment;
        List<String> result = PaymentController.handlePayment(objPayment.Id);
        PaymentController.getPaymentGateway();
        Test.stopTest();

        System.assertEquals('Failure', result[0]);

        List<Receipt__c> receipts = [SELECT Id FROM Receipt__c WHERE Payment__c =: objPayment.Id];
        System.assertEquals(0, receipts.size());
    } 
    /**
    * @description : 
    * @author Rohit Pal | 10-09-2020 
    * @return void 
    **/
    static testMethod void doNotCreateReceiptOnUnsuccessfulPayment2() {
        Test.startTest();
        Payment__c objPayment = [SELECT Id,
                                        Name,
                                        Invoice__c,
                                        Transaction_Status__c,
                                        Receipt_Created__c,
                                        AuthResp__c
                                FROM Payment__c WHERE Transaction_Date__c =: system.today() limit 1];
        objPayment.AuthResp__c = '';
        update objPayment;
        List<String> result = PaymentController.handlePayment('');
        PaymentController.getPaymentGateway();
        Test.stopTest();

        System.assertEquals('Invalid Record', result[0]);
        
        List<Receipt__c> receipts = [SELECT Id FROM Receipt__c WHERE Payment__c =: objPayment.Id];
        System.assertEquals(0, receipts.size());
    }
    
        /**
    * @description : 
    * @author Poon Koon | 01-02-2021 
    * @return void 
    **/
    static testMethod void getCourseRecordInformation(){
        Test.startTest();
        Payment__c objPayment = [SELECT Id,
                                        Name,
                                        Invoice__c,
                                        Course_Registration__c
                                FROM Payment__c WHERE Course_Registration__r.Contact__r.Account.LastName = 'Test Account' limit 1];
        Invoice__c objInvoice = [SELECT Id,
                                        Name,
                                        Course_Registration__c 
                                FROM Invoice__c WHERE Id =: objPayment.Invoice__c limit 1];
        objInvoice.Course_Registration__c = objPayment.Course_Registration__c;
        update objInvoice;
        PaymentController.getPaymentGateway();
        PaymentController.getCourseRecordInformation(objInvoice.Id);
        Test.stopTest();
    } 
}